app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("attachments_test")

app$snapshot(items = list(output = "outputDataTitle"), screenshot = TRUE)

# add attachment and save scenario
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='attachments']")$click()
attachmentList <- app$findElements(".attachment-line")
expect_identical(length(attachmentList), 0L)
app$uploadFile(file_addAttachments = "../model/pickstock_with_data/README.md")
Sys.sleep(0.5)
# try deleting file and adding it back
app$waitFor("$('#btRemoveAttachment_1').click();true;", timeout = 50L)
Sys.sleep(0.2)
expect_identical(length(app$findElements(".attachment-line")), 0L)
app$uploadFile(file_addAttachments = "../model/pickstock_with_data/README.md")
Sys.sleep(0.5)
# try to upload same file again, should not result in second attachment
app$uploadFile(file_addAttachments = "../model/pickstock_with_data/README.md")
Sys.sleep(1)
attachmentList <- app$findElements(".attachment-line")
expect_identical(length(attachmentList), 1L)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)
app$setInputs(btSave = "click")
Sys.sleep(1)
app$setInputs(btSaveOutput = "click")
Sys.sleep(1)

# remove scenario from sandbox and load it again
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(0.5)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(1)

# download attachment
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='attachments']")$click()
Sys.sleep(0.1)
attachmentList <- app$findElements(".attachment-line")
attachmentList[[1]]$findElement("a")$click()
app$snapshotDownload("downloadAttachmentData", "attachment.md")

# un-check model read permissions for attachment several times, save and remove scenario from sandbox
expect_identical(length(attachmentList), 1L)
expect_identical(attachmentList[[1]]$findElement(".checkbox input")$getAttribute("checked"), "true")
attachmentList[[1]]$findElement(".checkbox input")$click()
expect_null(attachmentList[[1]]$findElement(".checkbox input")$getAttribute("checked"))
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)
app$setInputs(btSave = "click")
Sys.sleep(1)
app$setInputs(btSaveOutput = "click")
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='attachments']")$click()
Sys.sleep(0.1)
attachmentList <- app$findElements(".attachment-line")
expect_null(attachmentList[[1]]$findElement(".checkbox input")$getAttribute("checked"))
attachmentList[[1]]$findElement(".checkbox input")$click()
attachmentList[[1]]$findElement(".checkbox input")$click()
attachmentList[[1]]$findElement(".checkbox input")$click()
attachmentList[[1]]$findElement(".checkbox input")$click()
attachmentList[[1]]$findElement(".checkbox input")$click()
attachmentList[[1]]$findElement(".checkbox input")$click()
expect_null(attachmentList[[1]]$findElement(".checkbox input")$getAttribute("checked"))
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)
app$setInputs(btSave = "click")
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='attachments']")$click()
Sys.sleep(0.1)
expect_null(app$findElements(".attachment-line")[[1]]$findElement(".checkbox input")$getAttribute("checked"))
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)
app$setInputs(btSave = "click")
Sys.sleep(1)
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(0.5)

# load scenario, delete attachment and save scenario
app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='attachments']")$click()
Sys.sleep(0.1)
expect_null(app$findElements(".attachment-line")[[1]]$findElement(".checkbox input")$getAttribute("checked"))
app$waitFor("$('#btRemoveAttachment_1').click();true;", timeout = 50L)
Sys.sleep(0.2)
expect_identical(length(app$findElements(".attachment-line")), 0L)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)
app$setInputs(btSave = "click")

app$stop()
