app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("attachments_save_as_test")

app$snapshot(items = list(output = "outputDataTitle"),
             screenshot = TRUE)

saveNewDefault <- function(newName = NULL, discardAttach = FALSE){
  app$findElement("#btRemove1")$click()
  Sys.sleep(0.5)
  app$findElement(".modal-footer .bt-gms-confirm")$click()
  Sys.sleep(0.5)
  app$setInputs(btImport = "click")
  Sys.sleep(0.5)
  app$setInputs(selLoadScen = paste0("1_", user))
  expect_identical(startsWith(app$getValue("selLoadScen"), "1_"), TRUE)
  app$setInputs(btLoadScenConfirm = "click")
  Sys.sleep(1)
  app$setInputs(btSaveAs = "click")
  Sys.sleep(0.5)
  app$setInputs(scenName = newName)
  if(isTRUE(discardAttach))
    app$setInputs(newScenDiscardAttach = "click")
  Sys.sleep(0.1)
  app$findElement("#shiny-modal .bt-gms-confirm")$click()
  Sys.sleep(1)
}


#load default scenario
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(0.5)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(1)

#get user name
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='accessPerm']")$click()
Sys.sleep(1)
user <-app$getValue("editMetaWritePerm")[[1]]
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)

#save as same name (overwrite existing)
app$setInputs(btSaveAs = "click")
Sys.sleep(0.5)
expect_identical(app$findElement("#scenarioExists")$getAttribute("style"), c("display: none;"))
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(0.5)
expect_identical(app$findElement("#scenarioExists")$getAttribute("style"), c(""))
app$setInputs(btSaveConfirm = "click")
Sys.sleep(1)

#save as same name (chose new scenario name)
app$setInputs(btSaveAs = "click")
Sys.sleep(0.5)
expect_identical(app$findElement("#scenarioExists")$getAttribute("style"), c("display: none;"))
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(0.5)
expect_identical(app$findElement("#scenarioExists")$getAttribute("style"), c(""))
app$setInputs(btNewName = "click")
Sys.sleep(0.5)
app$setInputs(scenName = "newScen")
Sys.sleep(0.5)
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(1)

#add attachment, save scenario newScen
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='Attachments']")$click()
app$uploadFile(file_addAttachments = "../model/pickstock_with_data/README.md")
Sys.sleep(1)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)
app$setInputs(btSave = "click")
Sys.sleep(0.5)

#save as same name and discard attachments
app$setInputs(btSaveAs = "click")
Sys.sleep(0.5)
app$setInputs(newScenDiscardAttach = "click")
Sys.sleep(0.5)
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(0.5)
app$setInputs(btSaveConfirm = "click")
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='Attachments']")$click()
Sys.sleep(0.1)
attachmentList <- app$findElements(".attachment-line")
expect_identical(length(attachmentList), 0L)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)

#add attachment, save as new name and discard attachments
saveNewDefault("newScen2", TRUE)
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='Attachments']")$click()
Sys.sleep(0.1)
app$uploadFile(file_addAttachments = "../model/pickstock_with_data/README.md")
Sys.sleep(1)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)
app$setInputs(btSave = "click")
Sys.sleep(0.5)
app$setInputs(btSaveAs = "click")
Sys.sleep(0.5)
app$setInputs(scenName = "newScen3")
app$setInputs(newScenDiscardAttach = "click")
Sys.sleep(0.5)
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='Attachments']")$click()
Sys.sleep(0.5)
attachmentList <- app$findElements(".attachment-line")
expect_identical(length(attachmentList), 0L)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)

#add attachment, save as same name and do not discard attachments
saveNewDefault("newScen4", TRUE)
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='Attachments']")$click()
Sys.sleep(0.1)
app$uploadFile(file_addAttachments = "../model/pickstock_with_data/README.md")
Sys.sleep(1)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)
app$setInputs(btSave = "click")
Sys.sleep(0.5)
app$setInputs(btSaveAs = "click")
Sys.sleep(0.5)
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(0.5)
app$setInputs(btSaveConfirm = "click")
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='Attachments']")$click()
Sys.sleep(0.1)
attachmentList <- app$findElements(".attachment-line")
expect_identical(length(attachmentList), 1L)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)

#add attachment, save as new name and do not discard attachments
saveNewDefault("newScen5", TRUE)
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='Attachments']")$click()
Sys.sleep(0.1)
app$uploadFile(file_addAttachments = "../model/pickstock_with_data/README.md")
Sys.sleep(1)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)
app$setInputs(btSave = "click")
Sys.sleep(0.5)
app$setInputs(btSaveAs = "click")
Sys.sleep(0.5)
app$setInputs(scenName = "newScen6")
Sys.sleep(0.5)
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='Attachments']")$click()
Sys.sleep(0.1)
attachmentList <- app$findElements(".attachment-line")
expect_identical(length(attachmentList), 1L)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)

app$stop()
