app <- AppDriver$new("../../",
  name = "base_mode_scripts_test", variant = NULL,
  load_timeout = as.integer(Sys.getenv("MIRO_TEST_LOAD_TIMEOUT", "20000")),
  timeout = as.integer(Sys.getenv("MIRO_TEST_TIMEOUT", "4000"))
)

app$click(selector = "a[data-value='outputData']")
Sys.sleep(0.5)

expect_true(app$get_js("$(\"a[data-value='outputTabset_3']\").text()==='asd';"))
expect_true(app$get_js("$(\"a[data-value='outputTabset_4']\").text()==='def';"))
app$set_inputs(outputTabset = "outputTabset_3")
app$run_js("$('.btn-run-script:visible').click();")
expect_error(app$wait_for_js("$('.script-output:visible').contents().find('body').text()?.trim()==='# test1';", timeout = 10000L), NA)
app$set_inputs(outputTabset = "outputTabset_4")
app$run_js("$('.btn-run-script:visible').click();")
expect_error(app$wait_for_js("$('.script-output:visible').contents().find('body').html()?.trim()==='<p><em>asd</em><strong>bla</strong></p>';", timeout = 10000L), NA)
app$set_inputs(btSave = "click")
Sys.sleep(1)
app$set_inputs(btSaveConfirm = "click")
Sys.sleep(2)
app$click(selector = 'a[data-value="scenarios"]')
app$run_js("$('.scenSplit-button-load').eq(1).click();")
Sys.sleep(2)
app$set_inputs(contentScen_2 = "contentScen_2_8")
expect_error(app$wait_for_js("$('#scenScript_2_1').contents().find('body').text()?.trim()==='# test1';", timeout = 10000L), NA)
app$run_js("$('.scenSplit-button-load').eq(2).click();")
Sys.sleep(1)
app$set_inputs(btLoadScenConfirm = "click")
Sys.sleep(2)
app$set_inputs(contentScen_3 = "contentScen_3_9")
expect_error(app$wait_for_js("$('#scenScript_3_2').contents().find('body').html()?.trim()==='<p><em>asd</em><strong>bla</strong></p>';", timeout = 10000L), NA)
app$click(selector = "a[data-value='inputData']")
Sys.sleep(0.5)
app$set_inputs(inputTabset = "inputTabset_5")
app$set_inputs(slider_6 = 99)
app$click(selector = "a[data-value='outputData']")
Sys.sleep(0.5)
app$run_js("$('.btn-run-script:visible').click();")
expect_error(app$wait_for_js("$('.script-output:visible').contents().find('body').html()?.trim()==='<p><em>uiuiui</em></p>';", timeout = 10000L), NA)
app$click(selector = "a[data-value='inputData']")
Sys.sleep(0.5)
app$set_inputs(btSave = "click")
Sys.sleep(1)
app$set_inputs(btSaveOutput = "click")
Sys.sleep(1)
app$click(selector = "#btRemove1")
Sys.sleep(1)
app$click(selector = ".modal-footer .bt-gms-confirm")
Sys.sleep(1)
app$click(selector = "a[data-value='outputData']")
Sys.sleep(0.5)
app$run_js("$('.btn-run-script:visible').click();")
Sys.sleep(3)
app$click(selector = 'a[data-value="scenarios"]')
app$run_js("$('#refreshSandbox_2 button').click();")
expect_error(app$wait_for_js("$('#scenScript_2_1').is(':hidden')===true&&$('#scenScript_2_1_noData').is(':visible')===true;", timeout = 10000L), NA)
app$set_inputs(contentScen_2 = "contentScen_2_9")
expect_error(app$wait_for_js("$('#scenScript_2_2').contents().find('body').html()?.trim()==='<p><em>asd</em><strong>bla</strong></p>';", timeout = 10000L), NA)
app$run_js("$('#refreshSandbox_3 button').click();")
expect_error(app$wait_for_js("$('#scenScript_3_2').contents().find('body').html()?.trim()==='<p><em>uiuiui</em></p>';", timeout = 10000L), NA)

# closing scenario while script is running should terminate script
app$click(selector = "a[data-value='inputData']")
app$set_inputs(slider_6 = 99)
app$click(selector = "a[data-value='outputData']")
Sys.sleep(0.5)
app$set_inputs(outputTabset = "outputTabset_3")
app$run_js("$('.btn-run-script:visible').click();")
app$click(selector = "a[data-value='inputData']")
Sys.sleep(0.5)
app$click(selector = "#btRemove1")
Sys.sleep(0.5)
app$click(selector = ".modal-footer .bt-gms-confirm")
Sys.sleep(6)
expect_identical(readr::read_lines(file.path(testDir, "bla.txt")), "start")
app$stop()
