app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("base_mode_scripts_test")

app$snapshot(items = list(output = "outputDataTitle"), screenshot = TRUE)

app$findElement("a[data-value='outputData']")$click()
Sys.sleep(0.5)

expect_true(app$waitFor("$(\"a[data-value='outputTabset_3']\").text()==='asd'", timeout = 50))
expect_true(app$waitFor("$(\"a[data-value='outputTabset_4']\").text()==='def'", timeout = 50))
app$setInputs(outputTabset = "outputTabset_3")
expect_true(app$waitFor("$('.btn-run-script:visible').click();true;", timeout = 50))
Sys.sleep(4)
expect_true(app$waitFor("$('.script-output:visible').contents().find('body').text().trim()==='# test1'", timeout = 50))
Sys.sleep(4)
app$setInputs(outputTabset = "outputTabset_4")
expect_true(app$waitFor("$('.btn-run-script:visible').click();true;", timeout = 50))
Sys.sleep(4)
expect_true(app$waitFor("$('.script-output:visible').contents().find('body').html().trim()==='<p><em>asd</em><strong>bla</strong></p>'", timeout = 50))
app$setInputs(btSave = "click")
Sys.sleep(1)
app$setInputs(btSaveConfirm = "click")
Sys.sleep(2)
app$findElement('a[data-value="scenarios"]')$click()
app$waitFor("$('.scenSplit-button-load').eq(1).click();true;", timeout = 50)
Sys.sleep(2)
app$setInputs(contentScen_2 = "contentScen_2_8")
Sys.sleep(2)
expect_true(app$waitFor("$('#scenScript_2_1').contents().find('body').text().trim()==='# test1'", timeout = 50))
app$waitFor("$('.scenSplit-button-load').eq(2).click();true;", timeout = 50)
Sys.sleep(1)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
app$setInputs(contentScen_3 = "contentScen_3_9")
Sys.sleep(2)
expect_true(app$waitFor("$('#scenScript_3_2').contents().find('body').html().trim()==='<p><em>asd</em><strong>bla</strong></p>'", timeout = 50))
app$findElement("a[data-value='inputData']")$click()
Sys.sleep(0.5)
app$setInputs(inputTabset = "inputTabset_5")
app$setInputs(slider_6 = 99)
app$findElement("a[data-value='outputData']")$click()
Sys.sleep(0.5)
expect_true(app$waitFor("$('.btn-run-script:visible').click();true;", timeout = 50))
Sys.sleep(3L)
expect_true(app$waitFor("$('.script-output:visible').contents().find('body').html().trim()==='<p><em>uiuiui</em></p>'", timeout = 50))
app$findElement("a[data-value='inputData']")$click()
Sys.sleep(0.5)
app$setInputs(btSave = "click")
Sys.sleep(1)
app$setInputs(btSaveOutput = "click")
Sys.sleep(1)
app$findElement("#btRemove1")$click()
Sys.sleep(1)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(1)
app$findElement("a[data-value='outputData']")$click()
Sys.sleep(0.5)
expect_true(app$waitFor("$('.btn-run-script:visible').click();true;", timeout = 50))
Sys.sleep(3)
app$findElement('a[data-value="scenarios"]')$click()
app$waitFor("$('#refreshSandbox_2 button').click();true;", timeout = 50)
Sys.sleep(2)
expect_true(app$waitFor("$('#scenScript_2_1').is(':hidden')===true&&$('#scenScript_2_1_noData').is(':visible')===true", timeout = 50))
app$setInputs(contentScen_2 = "contentScen_2_9")
Sys.sleep(2)
expect_true(app$waitFor("$('#scenScript_2_2').contents().find('body').html().trim()==='<p><em>asd</em><strong>bla</strong></p>'", timeout = 50))
app$waitFor("$('#refreshSandbox_3 button').click();true;", timeout = 50)
Sys.sleep(2)
expect_true(app$waitFor("$('#scenScript_3_2').contents().find('body').html().trim()==='<p><em>uiuiui</em></p>'", timeout = 50))

# closing scenario while script is running should terminate script
app$findElement("a[data-value='inputData']")$click()
app$setInputs(slider_6 = 99)
app$findElement("a[data-value='outputData']")$click()
Sys.sleep(0.5)
app$setInputs(outputTabset = "outputTabset_3")
expect_true(app$waitFor("$('.btn-run-script:visible').click();true;", timeout = 50))
app$findElement("a[data-value='inputData']")$click()
Sys.sleep(0.5)
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(6)
expect_identical(readr::read_lines(file.path(testDir, "bla.txt")), "start")
app$stop()
