app <- AppDriver$new("../../", name = "base_mode_scripts_test", variant = NULL, load_timeout = 20000)

app$click(selector = "a[data-value='outputData']")
Sys.sleep(0.5)

expect_true(app$get_js("$(\"a[data-value='outputTabset_3']\").text()==='asd';"))
expect_true(app$get_js("$(\"a[data-value='outputTabset_4']\").text()==='def';"))
app$set_inputs(outputTabset = "outputTabset_3")
expect_true(app$get_js("$('.btn-run-script:visible').click();true;"))
Sys.sleep(4)
expect_true(app$get_js("$('.script-output:visible').contents().find('body').text().trim()==='# test1';"))
Sys.sleep(4)
app$set_inputs(outputTabset = "outputTabset_4")
expect_true(app$get_js("$('.btn-run-script:visible').click();true;"))
Sys.sleep(4)
expect_true(app$get_js("$('.script-output:visible').contents().find('body').html().trim()==='<p><em>asd</em><strong>bla</strong></p>';"))
app$set_inputs(btSave = "click")
Sys.sleep(1)
app$set_inputs(btSaveConfirm = "click")
Sys.sleep(2)
app$click(selector = 'a[data-value="scenarios"]')
app$get_js("$('.scenSplit-button-load').eq(1).click();true;")
Sys.sleep(2)
app$set_inputs(contentScen_2 = "contentScen_2_8")
Sys.sleep(2)
expect_true(app$get_js("$('#scenScript_2_1').contents().find('body').text().trim()==='# test1';"))
app$get_js("$('.scenSplit-button-load').eq(2).click();true;")
Sys.sleep(1)
app$set_inputs(btLoadScenConfirm = "click")
Sys.sleep(2)
app$set_inputs(contentScen_3 = "contentScen_3_9")
Sys.sleep(2)
expect_true(app$get_js("$('#scenScript_3_2').contents().find('body').html().trim()==='<p><em>asd</em><strong>bla</strong></p>';"))
app$click(selector = "a[data-value='inputData']")
Sys.sleep(0.5)
app$set_inputs(inputTabset = "inputTabset_5")
app$set_inputs(slider_6 = 99)
app$click(selector = "a[data-value='outputData']")
Sys.sleep(0.5)
expect_true(app$get_js("$('.btn-run-script:visible').click();true;"))
Sys.sleep(3L)
expect_true(app$get_js("$('.script-output:visible').contents().find('body').html().trim()==='<p><em>uiuiui</em></p>';"))
app$click(selector = "a[data-value='inputData']")
Sys.sleep(0.5)
app$set_inputs(btSave = "click")
Sys.sleep(1)
app$set_inputs(btSaveOutput = "click")
Sys.sleep(1)
app$click(selector = "#btRemove1")
Sys.sleep(1)
app$click(selector = ".modal-footer .bt-gms-confirm")
Sys.sleep(1)
app$click(selector = "a[data-value='outputData']")
Sys.sleep(0.5)
expect_true(app$get_js("$('.btn-run-script:visible').click();true;",))
Sys.sleep(3)
app$click(selector = 'a[data-value="scenarios"]')
app$get_js("$('#refreshSandbox_2 button').click();true;")
Sys.sleep(2)
expect_true(app$get_js("$('#scenScript_2_1').is(':hidden')===true&&$('#scenScript_2_1_noData').is(':visible')===true;"))
app$set_inputs(contentScen_2 = "contentScen_2_9")
Sys.sleep(2)
expect_true(app$get_js("$('#scenScript_2_2').contents().find('body').html().trim()==='<p><em>asd</em><strong>bla</strong></p>';"))
app$get_js("$('#refreshSandbox_3 button').click();true;")
Sys.sleep(2)
expect_true(app$get_js("$('#scenScript_3_2').contents().find('body').html().trim()==='<p><em>uiuiui</em></p>';"))

# closing scenario while script is running should terminate script
app$click(selector = "a[data-value='inputData']")
app$set_inputs(slider_6 = 99)
app$click(selector = "a[data-value='outputData']")
Sys.sleep(0.5)
app$set_inputs(outputTabset = "outputTabset_3")
expect_true(app$get_js("$('.btn-run-script:visible').click();true;"))
app$click(selector = "a[data-value='inputData']")
Sys.sleep(0.5)
app$click(selector = "#btRemove1")
Sys.sleep(0.5)
app$click(selector = ".modal-footer .bt-gms-confirm")
Sys.sleep(6)
expect_identical(readr::read_lines(file.path(testDir, "bla.txt")), "start")
app$stop()
