app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit(paste0("compare_scen_split_test_", Sys.getenv("GMSMODELNAME")))

app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
app$findElement("a[data-value='scenarios']")$click()
app$setInputs(btScenSplit1_open = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
app$setInputs(btScenSplit2_open = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)

app$snapshot(items = list(output = c("cmpScenTitle_2", "cmpScenTitle_3")), screenshot = TRUE)
app$stop()
