app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit(paste0("compare_scen_tab_test_", Sys.getenv("GMSMODELNAME")))

app$findElement("a[data-value='scenarios']")$click()
app$findElement(".btSplitView button")$click()
app$findElements(".btSplitView a[data-view='tab']")[[1]]$click()
Sys.sleep(0.5)
app$findElement("#no-scen .action-button")$click()
Sys.sleep(1)
app$setInputs(selLoadScen = paste0(c("1_", "2_"), Sys.info()[["user"]]), wait_ = FALSE, values_ = FALSE)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
app$snapshot(items = list(output = c("title_4", "title_5")), screenshot = TRUE)
app$findElement("#btScenTableView5")$click()

app$stop()