app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("comparison_mode_test")

currentUser <- Sys.info()[["user"]]

#test compare mode in tab view
app$findElement("a[data-value='scenarios']")$click()
app$findElement(".btSplitView button")$click()
app$findElements(".btSplitView a[data-view='tab']")[[1]]$click()
Sys.sleep(1)
app$snapshot(items = list(output = c("cmpScenTitle_4", "cmpScenTitle_5")), screenshot = TRUE)
app$findElement("#cmpTabNoScenWrapper .action-button")$click()
Sys.sleep(1)
scenToSelect <- paste0(c("1_", "2_"), currentUser)
app$setInputs(selLoadScen = scenToSelect, wait_ = FALSE, values_ = FALSE)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
app$findElement("#btCompareScen")$click()
Sys.sleep(0.2)
app$findElement("a[data-value='contentScen_5_2']")$click()
app$findElement("a[data-value='scen_4_']")$click()
Sys.sleep(2)
expect_true(app$waitFor("$('.tab-content div[data-value=\"contentScen_4_2\"]').is(':visible');", timeout = 50))
app$findElement("a[data-value='contentScen_4_5']")$click()
app$findElement("a[data-value='scen_5_']")$click()
Sys.sleep(2)
expect_true(app$waitFor("$('.tab-content div[data-value=\"contentScen_5_5\"]').is(':visible');", timeout = 50))

#test compare mode in split view
app$findElement(".btSplitView button")$click()
app$findElements(".btSplitView a[data-view='split']")[[1]]$click()
expect_true(app$waitFor("$('.scenSplit-button-load').get(1).click();true;", timeout = 50))
Sys.sleep(2)
app$setInputs(btScenSplit2_open = "click")
Sys.sleep(1)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
app$findElement("#btCompareScen")$click()
Sys.sleep(0.2)
app$findElement("a[data-value='contentScen_2_2']")$click()
Sys.sleep(1)
expect_true(app$waitFor("$('.tab-content div[data-value=\"contentScen_3_2\"]').is(':visible');", timeout = 50))
app$findElement("a[data-value='contentScen_3_5']")$click()
Sys.sleep(1)
expect_true(app$waitFor("$('.tab-content div[data-value=\"contentScen_2_5\"]').is(':visible');", timeout = 50))

# test download of files
app$waitFor("$('.scen-buttons-wrapper button').get(1).click()", timeout = 50)
Sys.sleep(1)
app$setInputs(exportFileType = "xls", cbSelectManuallyExp = "true", selDataToExport = c("_scalars", "abserror"))
expect_sheets_in_xls(app, "scenExportHandler", c(" Info", "abserror (Output)", "_scalars (Input)", "_index"))
Sys.sleep(1)

app$waitFor("$('.scen-buttons-wrapper button').get(1).click()", timeout = 50)
Sys.sleep(1)
app$setInputs(exportFileType = "xls")
expect_sheets_in_xls(app, "scenExportHandler", c(" Info", "_scalars_out (Output)", "stock_weight (Output)", "dowvsindex (Output)", "abserror (Output)", "pricemerge (Output)", "_scalars (Input)", "price (Input)", "_index"))
Sys.sleep(1)

app$waitFor("$('.scen-buttons-wrapper button').get(4).click()", timeout = 50)
Sys.sleep(1)
app$setInputs(exportFileType = "gdx", cbSelectManuallyExp = "true", selDataToExport = c("_scalars_out", "dowvsindex"))
Sys.sleep(1)
expect_symbols_in_gdx(app, "scenExportHandler", c("dowvsindex", "error_ratio", "error_train", "error_test",
                                                  "firstdaytraining", "lastdaytraining"))
Sys.sleep(1)
app$waitFor("$('.scen-buttons-wrapper button').get(1).click()", timeout = 50)
Sys.sleep(1)
app$setInputs(exportFileType = "gdx")
expect_symbols_in_gdx(app, "scenExportHandler", c("dowvsindex", "error_ratio", "error_train", "error_test",
                                                  "firstdaytraining", "lastdaytraining", "stock_weight",
                                                  "abserror", "pricemerge", "price", "maxstock", "trainingdays"))
Sys.sleep(1)

app$waitFor("$('.scen-buttons-wrapper button').get(1).click()", timeout = 50)
Sys.sleep(1)
app$setInputs(exportFileType = "miroscen")
expect_true(app$waitFor("$('#cbSelectManuallyExp').is(':hidden');", timeout = 50))
Sys.sleep(0.5)
expect_download_size(app, "scenExportHandler", "split_comp_download.miroscen")
Sys.sleep(1)

app$stop()
