app <- AppDriver$new("../../", name = "config_mode_widget_test", variant = NULL, load_timeout = 20000)

Sys.sleep(1)
jsonPath <- file.path("..", "model", "pickstock_configuration", "conf_pickstock_configuration")
configRaw <- suppressWarnings(jsonlite::fromJSON(file.path(jsonPath, "pickstock_configuration_expected.json"),
  simplifyDataFrame = FALSE,
  simplifyMatrix = FALSE
))
configNew <- suppressWarnings(jsonlite::fromJSON(file.path(jsonPath, "pickstock_configuration.json"),
  simplifyDataFrame = FALSE,
  simplifyMatrix = FALSE
))


# load and save all widgets
app$click(selector = "a[data-value='new_widget']")
Sys.sleep(1)
for (widgetToTest in names(configRaw$inputWidgets)) {
  app$set_inputs(widget_symbol = widgetToTest)
  Sys.sleep(1)
  app$click(selector = "button[id='saveWidget']")
  Sys.sleep(1)
}
configNew <- suppressWarnings(jsonlite::fromJSON(file.path(jsonPath, "pickstock_configuration.json"),
  simplifyDataFrame = FALSE,
  simplifyMatrix = FALSE
))

expect_identical(configRaw$inputWidgets$price$widgetType, configNew$inputWidgets$price$widgetType)
expect_identical(configRaw$inputWidgets$price$tableType, configNew$inputWidgets$price$tableType)
expect_identical(configRaw$inputWidgets$price$readonly, configNew$inputWidgets$price$readonly)
expect_identical(configRaw$inputWidgets$price$readonlyCols, configNew$inputWidgets$price$readonlyCols)
expect_identical(configRaw$inputWidgets$price$hideIndexCol, configNew$inputWidgets$price$hideIndexCol)
expect_identical(configRaw$inputWidgets$price$heatmap, configNew$inputWidgets$price$heatmap)
expect_identical(configRaw$inputWidgets$maxstock$label, configNew$inputWidgets$maxstock$label)
expect_identical(configRaw$inputWidgets$maxstock$widgetType, configNew$inputWidgets$maxstock$widgetType)
expect_identical(configRaw$inputWidgets$maxstock$alias, configNew$inputWidgets$maxstock$alias)
expect_identical(configRaw$inputWidgets$maxstock$min, configNew$inputWidgets$maxstock$min)
expect_identical(configRaw$inputWidgets$maxstock$max, configNew$inputWidgets$maxstock$max)
expect_identical(configRaw$inputWidgets$maxstock$default, configNew$inputWidgets$maxstock$default)
expect_identical(configRaw$inputWidgets$maxstock$step, configNew$inputWidgets$maxstock$step)
expect_identical(configRaw$inputWidgets$maxstock$ticks, configNew$inputWidgets$maxstock$ticks)
expect_identical(configRaw$inputWidgets$maxstock$noHcube, configNew$inputWidgets$maxstock$noHcube)
expect_identical(configRaw$inputWidgets$trainingdays$label, configNew$inputWidgets$trainingdays$label)
expect_identical(configRaw$inputWidgets$trainingdays$min, configNew$inputWidgets$trainingdays$min)
expect_identical(configRaw$inputWidgets$trainingdays$default, configNew$inputWidgets$trainingdays$default)
expect_identical(configRaw$inputWidgets$trainingdays$step, configNew$inputWidgets$trainingdays$step)
expect_identical(configRaw$inputWidgets$trainingdays$max, configNew$inputWidgets$trainingdays$max)
expect_identical(configRaw$inputWidgets$trainingdays$alias, configNew$inputWidgets$trainingdays$alias)
expect_identical(configRaw$inputWidgets$trainingdays$widgetType, configNew$inputWidgets$trainingdays$widgetType)
expect_identical(configRaw$inputWidgets$trainingdays$ticks, configNew$inputWidgets$trainingdays$ticks)
expect_identical(configRaw$inputWidgets$trainingdays$noHcube, configNew$inputWidgets$trainingdays$noHcube)
expect_identical(configRaw$inputWidgets$solver$alias, configNew$inputWidgets$solver$alias)
expect_identical(configRaw$inputWidgets$solver$widgetType, configNew$inputWidgets$solver$widgetType)
expect_identical(configRaw$inputWidgets$solver$label, configNew$inputWidgets$solver$label)
expect_identical(configRaw$inputWidgets$solver$choices, configNew$inputWidgets$solver$choices)
expect_identical(configRaw$inputWidgets$solver$selected, configNew$inputWidgets$solver$selected)
expect_identical(configRaw$inputWidgets$solver$noHcube, configNew$inputWidgets$solver$noHcube)
expect_identical(configRaw$inputWidgets$solver$clearValue, configNew$inputWidgets$solver$clearValue)
expect_identical(configRaw$inputWidgets$solver$multiple, configNew$inputWidgets$solver$multiple)
expect_identical(configRaw$inputWidgets$clearvalueset$widgetType, configNew$inputWidgets$clearvalueset$widgetType)
expect_identical(configRaw$inputWidgets$clearvalueset$alias, configNew$inputWidgets$clearvalueset$alias)
expect_identical(configRaw$inputWidgets$clearvalueset$value, configNew$inputWidgets$clearvalueset$value)
expect_identical(configRaw$inputWidgets$clearvalueset$placeholder, configNew$inputWidgets$clearvalueset$placeholder)
expect_identical(configRaw$inputWidgets$clearvalueset$clearValue, configNew$inputWidgets$clearvalueset$clearValue)
expect_identical(configRaw$inputWidgets$clearvalueset$label, configNew$inputWidgets$clearvalueset$label)
expect_identical(configRaw$inputWidgets[["_gmspar_sliderrange"]]$widgetType, configNew$inputWidgets[["_gmspar_sliderrange"]]$widgetType)
expect_identical(configRaw$inputWidgets[["_gmspar_sliderrange"]]$alias, configNew$inputWidgets[["_gmspar_sliderrange"]]$alias)
expect_identical(configRaw$inputWidgets[["_gmspar_sliderrange"]]$min, configNew$inputWidgets[["_gmspar_sliderrange"]]$min)
expect_identical(configRaw$inputWidgets[["_gmspar_sliderrange"]]$max, configNew$inputWidgets[["_gmspar_sliderrange"]]$max)
expect_identical(configRaw$inputWidgets[["_gmspar_sliderrange"]]$default, configNew$inputWidgets[["_gmspar_sliderrange"]]$default)
expect_identical(configRaw$inputWidgets[["_gmspar_sliderrange"]]$step, configNew$inputWidgets[["_gmspar_sliderrange"]]$step)
expect_identical(configRaw$inputWidgets[["_gmspar_sliderrange"]]$ticks, configNew$inputWidgets[["_gmspar_sliderrange"]]$ticks)
expect_identical(configRaw$inputWidgets[["_gmspar_sliderrange"]]$noHcube, configNew$inputWidgets[["_gmspar_sliderrange"]]$noHcube)
expect_identical(configRaw$inputWidgets[["_gmspar_sliderrange"]]$label, configNew$inputWidgets[["_gmspar_sliderrange"]]$label)
expect_identical(configRaw$inputWidgets[["_gmspar_sliderrange"]]$minStep, configNew$inputWidgets[["_gmspar_sliderrange"]]$minStep)
expect_identical(configRaw$inputWidgets[["_gmsopt_checkbox"]]$widgetType, configNew$inputWidgets[["_gmsopt_checkbox"]]$widgetType)
expect_identical(configRaw$inputWidgets[["_gmsopt_checkbox"]]$alias, configNew$inputWidgets[["_gmsopt_checkbox"]]$alias)
expect_identical(configRaw$inputWidgets[["_gmsopt_checkbox"]]$value, configNew$inputWidgets[["_gmsopt_checkbox"]]$value)
expect_identical(configRaw$inputWidgets[["_gmsopt_checkbox"]]$noHcube, configNew$inputWidgets[["_gmsopt_checkbox"]]$noHcube)
expect_identical(configRaw$inputWidgets[["_gmsopt_checkbox"]]$class, configNew$inputWidgets[["_gmsopt_checkbox"]]$class)
expect_identical(configRaw$inputWidgets[["_gmsopt_checkbox"]]$label, configNew$inputWidgets[["_gmsopt_checkbox"]]$label)
expect_identical(configRaw$inputWidgets[["_gmspar_date"]]$widgetType, configNew$inputWidgets[["_gmspar_date"]]$widgetType)
expect_identical(configRaw$inputWidgets[["_gmspar_date"]]$alias, configNew$inputWidgets[["_gmspar_date"]]$alias)
expect_identical(configRaw$inputWidgets[["_gmspar_date"]]$format, configNew$inputWidgets[["_gmspar_date"]]$format)
expect_identical(configRaw$inputWidgets[["_gmspar_date"]]$startview, configNew$inputWidgets[["_gmspar_date"]]$startview)
expect_identical(configRaw$inputWidgets[["_gmspar_date"]]$weekstart, configNew$inputWidgets[["_gmspar_date"]]$weekstart)
expect_identical(configRaw$inputWidgets[["_gmspar_date"]]$autoclose, configNew$inputWidgets[["_gmspar_date"]]$autoclose)
expect_identical(configRaw$inputWidgets[["_gmspar_date"]]$noHcube, configNew$inputWidgets[["_gmspar_date"]]$noHcube)
expect_identical(configRaw$inputWidgets[["_gmspar_date"]]$label, configNew$inputWidgets[["_gmspar_date"]]$label)
expect_identical(configRaw$inputWidgets[["_gmspar_date"]]$value, configNew$inputWidgets[["_gmspar_date"]]$value)
expect_identical(configRaw$inputWidgets[["_gmspar_date"]]$min, configNew$inputWidgets[["_gmspar_date"]]$min)
expect_identical(configRaw$inputWidgets[["_gmspar_date"]]$daysofweekdisabled, configNew$inputWidgets[["_gmspar_date"]]$daysofweekdisabled)
expect_identical(configRaw$inputWidgets[["_gmspar_daterange"]]$widgetType, configNew$inputWidgets[["_gmspar_daterange"]]$widgetType)
expect_identical(configRaw$inputWidgets[["_gmspar_daterange"]]$alias, configNew$inputWidgets[["_gmspar_daterange"]]$alias)
expect_identical(configRaw$inputWidgets[["_gmspar_daterange"]]$format, configNew$inputWidgets[["_gmspar_daterange"]]$format)
expect_identical(configRaw$inputWidgets[["_gmspar_daterange"]]$startview, configNew$inputWidgets[["_gmspar_daterange"]]$startview)
expect_identical(configRaw$inputWidgets[["_gmspar_daterange"]]$weekstart, configNew$inputWidgets[["_gmspar_daterange"]]$weekstart)
expect_identical(configRaw$inputWidgets[["_gmspar_daterange"]]$separator, configNew$inputWidgets[["_gmspar_daterange"]]$separator)
expect_identical(configRaw$inputWidgets[["_gmspar_daterange"]]$autoclose, configNew$inputWidgets[["_gmspar_daterange"]]$autoclose)
expect_identical(configRaw$inputWidgets[["_gmspar_daterange"]]$noHcube, configNew$inputWidgets[["_gmspar_daterange"]]$noHcube)
expect_identical(configRaw$inputWidgets[["_gmspar_daterange"]]$label, configNew$inputWidgets[["_gmspar_daterange"]]$label)
expect_identical(configRaw$inputWidgets[["_gmspar_textinput"]]$widgetType, configNew$inputWidgets[["_gmspar_textinput"]]$widgetType)
expect_identical(configRaw$inputWidgets[["_gmspar_textinput"]]$alias, configNew$inputWidgets[["_gmspar_textinput"]]$alias)
expect_identical(configRaw$inputWidgets[["_gmspar_textinput"]]$value, configNew$inputWidgets[["_gmspar_textinput"]]$value)
expect_identical(configRaw$inputWidgets[["_gmspar_textinput"]]$placeholder, configNew$inputWidgets[["_gmspar_textinput"]]$placeholder)
expect_identical(configRaw$inputWidgets[["_gmspar_textinput"]]$label, configNew$inputWidgets[["_gmspar_textinput"]]$label)
expect_identical(configRaw$inputWidgets[["_gmspar_numericinput"]]$widgetType, configNew$inputWidgets[["_gmspar_numericinput"]]$widgetType)
expect_identical(configRaw$inputWidgets[["_gmspar_numericinput"]]$alias, configNew$inputWidgets[["_gmspar_numericinput"]]$alias)
expect_identical(configRaw$inputWidgets[["_gmspar_numericinput"]]$value, configNew$inputWidgets[["_gmspar_numericinput"]]$value)
expect_identical(configRaw$inputWidgets[["_gmspar_numericinput"]]$min, configNew$inputWidgets[["_gmspar_numericinput"]]$min)
expect_identical(configRaw$inputWidgets[["_gmspar_numericinput"]]$decimal, configNew$inputWidgets[["_gmspar_numericinput"]]$decimal)
expect_identical(configRaw$inputWidgets[["_gmspar_numericinput"]]$decimalCharacter, configNew$inputWidgets[["_gmspar_numericinput"]]$decimalCharacter)
expect_identical(configRaw$inputWidgets[["_gmspar_numericinput"]]$digitGroupSeparator, configNew$inputWidgets[["_gmspar_numericinput"]]$digitGroupSeparator)
expect_identical(configRaw$inputWidgets[["_gmspar_numericinput"]]$label, configNew$inputWidgets[["_gmspar_numericinput"]]$label)
expect_identical(configRaw$inputWidgets[["_gmspar_numericinput"]]$max, configNew$inputWidgets[["_gmspar_numericinput"]]$max)
expect_identical(configRaw$inputWidgets[["_gmspar_numericinput"]]$sign, configNew$inputWidgets[["_gmspar_numericinput"]]$sign)


app$stop()
