app <- AppDriver$new("../../",
  name = "config_mode_graph_test", variant = NULL,
  load_timeout = as.integer(Sys.getenv("MIRO_TEST_LOAD_TIMEOUT", "20000")),
  timeout = as.integer(Sys.getenv("MIRO_TEST_TIMEOUT", "4000"))
)

Sys.sleep(2L)
jsonPath <- file.path("..", "model", "pickstock_configuration", "conf_pickstock_configuration")
configRaw <- suppressWarnings(jsonlite::fromJSON(file.path(jsonPath, "pickstock_configuration_expected.json"),
  simplifyDataFrame = FALSE,
  simplifyMatrix = FALSE
))
configNew <- suppressWarnings(jsonlite::fromJSON(file.path(jsonPath, "pickstock_configuration.json"),
  simplifyDataFrame = FALSE,
  simplifyMatrix = FALSE
))


# load and save all widgets
app$click(selector = "a[data-value='new_graph']")
Sys.sleep(1)
app$click(selector = "button[id='dbInput']")
Sys.sleep(5)
for (GraphToTest in names(configRaw$dataRendering)) {
  app$set_inputs(gams_symbols = GraphToTest)
  if (identical(GraphToTest, "hovercraft")) {
    Sys.sleep(12)
  } else {
    Sys.sleep(4)
  }
  if (identical(GraphToTest, "maptest")) {
    setOptions <- getSelectizeOptions(app, "#chart_tool")
    # langSpecificGraphs$graphOptionsSet in tools/cg_graphs.R
    expect_identical(setOptions, c("timevis", "miropivot", "custom", "leaflet"))
  }
  app$click(selector = "button[id='saveGraph']")
  Sys.sleep(1)
  app$click(selector = "button[id='saveGraphConfirm']")
  Sys.sleep(1)
}
configNew <- suppressWarnings(jsonlite::fromJSON(file.path(jsonPath, "pickstock_configuration.json"),
  simplifyDataFrame = FALSE,
  simplifyMatrix = FALSE
))

# histogram
expect_identical(configRaw$dataRendering$abserror$outType, configNew$dataRendering$abserror$outType)
expect_identical(configRaw$dataRendering$abserror$height, configNew$dataRendering$abserror$height)
expect_identical(configRaw$dataRendering$abserror$graph$tool, configNew$dataRendering$abserror$graph$tool)
expect_identical(configRaw$dataRendering$abserror$graph$type, configNew$dataRendering$abserror$graph$type)
expect_identical(configRaw$dataRendering$abserror$graph$histnorm, configNew$dataRendering$abserror$graph$histnorm)
expect_identical(configRaw$dataRendering$abserror$graph$nbins, configNew$dataRendering$abserror$graph$nbins)
expect_identical(configRaw$dataRendering$abserror$graph$barmode, configNew$dataRendering$abserror$graph$barmode)
expect_identical(configRaw$dataRendering$abserror$graph$alpha, configNew$dataRendering$abserror$graph$alpha)
expect_identical(configRaw$dataRendering$abserror$graph$cumulative, configNew$dataRendering$abserror$graph$cumulative)
expect_identical(configRaw$dataRendering$abserror$graph$horizontal, configNew$dataRendering$abserror$graph$horizontal)
expect_identical(configRaw$dataRendering$abserror$graph$title, configNew$dataRendering$abserror$graph$title)
expect_identical(configRaw$dataRendering$abserror$graph$showlegend, configNew$dataRendering$abserror$graph$showlegend)
expect_identical(configRaw$dataRendering$abserror$graph$staticPlot, configNew$dataRendering$abserror$graph$staticPlot)
expect_identical(configRaw$dataRendering$abserror$graph$xdata[["absolute error train"]]$labels, configNew$dataRendering$abserror$graph$xdata[["absolute error train"]]$labels)
expect_identical(configRaw$dataRendering$abserror$graph$xdata[["absolute error train"]]$color, configNew$dataRendering$abserror$graph$xdata[["absolute error train"]]$color)
expect_identical(configRaw$dataRendering$abserror$graph$xdata[["absolute error train"]]$alpha, configNew$dataRendering$abserror$graph$xdata[["absolute error train"]]$alpha)
expect_identical(configRaw$dataRendering$abserror$graph$xdata[["absolute error test"]]$labels, configNew$dataRendering$abserror$graph$xdata[["absolute error test"]]$labels)
expect_identical(configRaw$dataRendering$abserror$graph$xdata[["absolute error test"]]$color, configNew$dataRendering$abserror$graph$xdata[["absolute error test"]]$color)
expect_identical(configRaw$dataRendering$abserror$graph$xdata[["absolute error test"]]$alpha, configNew$dataRendering$abserror$graph$xdata[["absolute error test"]]$alpha)
expect_identical(configRaw$dataRendering$abserror$graph$xaxis$title, configNew$dataRendering$abserror$graph$xaxis$title)
expect_identical(configRaw$dataRendering$abserror$graph$yaxis$title, configNew$dataRendering$abserror$graph$yaxis$title)

# map
expect_identical(configRaw$dataRendering$schedule$outType, configNew$dataRendering$schedule$outType)
expect_identical(configRaw$dataRendering$schedule$graph$title, configNew$dataRendering$schedule$graph$title)
expect_identical(configRaw$dataRendering$schedule$graph$tool, configNew$dataRendering$schedule$graph$tool)
expect_identical(configRaw$dataRendering$schedule$graph$layersControl$options$collapsed, configNew$dataRendering$schedule$graph$layersControl$options$collapsed)
expect_identical(configRaw$dataRendering$schedule$graph$layersControl$position, configNew$dataRendering$schedule$graph$layersControl$position)
expect_identical(configRaw$dataRendering$schedule$graph$layersControl$overlayGroups, configNew$dataRendering$schedule$graph$layersControl$overlayGroups)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["1"]]$lng, configNew$dataRendering$schedule$graph$markers[["1"]]$lng)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["1"]]$lat, configNew$dataRendering$schedule$graph$markers[["1"]]$lat)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["1"]]$iconOptions$icon, configNew$dataRendering$schedule$graph$markers[["1"]]$iconOptions$icon)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["1"]]$iconOptions$iconColor, configNew$dataRendering$schedule$graph$markers[["1"]]$iconOptions$iconColor)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["1"]]$iconOptions$markerColor, configNew$dataRendering$schedule$graph$markers[["1"]]$iconOptions$markerColor)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["1"]]$labelOptions$textsize, configNew$dataRendering$schedule$graph$markers[["1"]]$labelOptions$textsize)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["1"]]$labelOptions$permanent, configNew$dataRendering$schedule$graph$markers[["1"]]$labelOptions$permanent)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["1"]]$labelOptions$style$color, configNew$dataRendering$schedule$graph$markers[["1"]]$labelOptions$style$color)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["1"]]$label, configNew$dataRendering$schedule$graph$markers[["1"]]$label)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["1"]]$group, configNew$dataRendering$schedule$graph$markers[["1"]]$group)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["2"]]$lng, configNew$dataRendering$schedule$graph$markers[["2"]]$lng)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["2"]]$lat, configNew$dataRendering$schedule$graph$markers[["2"]]$lat)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["2"]]$iconOptions$icon, configNew$dataRendering$schedule$graph$markers[["2"]]$iconOptions$icon)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["2"]]$iconOptions$iconColor, configNew$dataRendering$schedule$graph$markers[["2"]]$iconOptions$iconColor)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["2"]]$iconOptions$markerColor, configNew$dataRendering$schedule$graph$markers[["2"]]$iconOptions$markerColor)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["2"]]$labelOptions$textsize, configNew$dataRendering$schedule$graph$markers[["2"]]$labelOptions$textsize)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["2"]]$labelOptions$permanent, configNew$dataRendering$schedule$graph$markers[["2"]]$labelOptions$permanent)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["2"]]$labelOptions$style$color, configNew$dataRendering$schedule$graph$markers[["2"]]$labelOptions$style$color)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["2"]]$label, configNew$dataRendering$schedule$graph$markers[["2"]]$label)
expect_identical(configRaw$dataRendering$schedule$graph$markers[["2"]]$group, configNew$dataRendering$schedule$graph$markers[["2"]]$group)
expect_identical(configRaw$dataRendering$schedule$graph$flows[["1"]]$lng0, configNew$dataRendering$schedule$graph$flows[["1"]]$lng0)
expect_identical(configRaw$dataRendering$schedule$graph$flows[["1"]]$lat0, configNew$dataRendering$schedule$graph$flows[["1"]]$lat0)
expect_identical(configRaw$dataRendering$schedule$graph$flows[["1"]]$lng1, configNew$dataRendering$schedule$graph$flows[["1"]]$lng1)
expect_identical(configRaw$dataRendering$schedule$graph$flows[["1"]]$lat1, configNew$dataRendering$schedule$graph$flows[["1"]]$lat1)
expect_identical(configRaw$dataRendering$schedule$graph$flows[["1"]]$flow, configNew$dataRendering$schedule$graph$flows[["1"]]$flow)
expect_identical(configRaw$dataRendering$schedule$graph$flows[["1"]]$color, configNew$dataRendering$schedule$graph$flows[["1"]]$color)
expect_identical(configRaw$dataRendering$schedule$graph$flows[["1"]]$minThickness, configNew$dataRendering$schedule$graph$flows[["1"]]$minThickness)
expect_identical(configRaw$dataRendering$schedule$graph$flows[["1"]]$maxThickness, configNew$dataRendering$schedule$graph$flows[["1"]]$maxThickness)
expect_identical(configRaw$dataRendering$schedule$graph$flows[["1"]]$layerId, configNew$dataRendering$schedule$graph$flows[["1"]]$layerId)
expect_identical(configRaw$dataRendering$schedule$height, configNew$dataRendering$schedule$height)

# map without groups
expect_null(configNew$dataRendering$mapNoGroup$graph$markers[["1"]]$group)
expect_null(configNew$dataRendering$mapNoGroup$graph$markers[["2"]]$group)
expect_identical(configRaw$dataRendering$mapNoGroup$graph$markers[["1"]]$lng, configNew$dataRendering$mapNoGroup$graph$markers[["1"]]$lng)
expect_identical(configRaw$dataRendering$mapNoGroup$graph$markers[["1"]]$lat, configNew$dataRendering$mapNoGroup$graph$markers[["1"]]$lat)
expect_identical(configRaw$dataRendering$mapNoGroup$graph$markers[["1"]]$label, configNew$dataRendering$mapNoGroup$graph$markers[["1"]]$label)
expect_identical(configRaw$dataRendering$mapNoGroup$graph$markers[["2"]]$lng, configNew$dataRendering$mapNoGroup$graph$markers[["2"]]$lng)
expect_identical(configRaw$dataRendering$mapNoGroup$graph$markers[["2"]]$lat, configNew$dataRendering$mapNoGroup$graph$markers[["2"]]$lat)
expect_identical(configRaw$dataRendering$mapNoGroup$graph$markers[["2"]]$label, configNew$dataRendering$mapNoGroup$graph$markers[["2"]]$label)

# gantt chart
expect_identical(configRaw$dataRendering$gantt$outType, configNew$dataRendering$gantt$outType)
expect_identical(configRaw$dataRendering$gantt$height, configNew$dataRendering$gantt$height)
expect_identical(configRaw$dataRendering$gantt$graph$tool, configNew$dataRendering$gantt$graph$tool)
expect_identical(configRaw$dataRendering$gantt$graph$showZoom, configNew$dataRendering$gantt$graph$showZoom)
expect_identical(configRaw$dataRendering$gantt$graph$fit, configNew$dataRendering$gantt$graph$fit)
expect_identical(configRaw$dataRendering$gantt$graph$zoomFactor, configNew$dataRendering$gantt$graph$zoomFactor)
expect_identical(configRaw$dataRendering$gantt$graph$editable, configNew$dataRendering$gantt$graph$editable)
expect_identical(configRaw$dataRendering$gantt$graph$multiselect, configNew$dataRendering$gantt$graph$multiselect)
expect_identical(configRaw$dataRendering$gantt$graph$showCurrentTime, configNew$dataRendering$gantt$graph$showCurrentTime)
expect_identical(configRaw$dataRendering$gantt$graph$series[["1"]]$content, configNew$dataRendering$gantt$graph$series[["1"]]$content)
expect_identical(configRaw$dataRendering$gantt$graph$series[["1"]]$start, configNew$dataRendering$gantt$graph$series[["1"]]$start)
expect_identical(configRaw$dataRendering$gantt$graph$series[["1"]]$type, configNew$dataRendering$gantt$graph$series[["1"]]$type)
expect_identical(configRaw$dataRendering$gantt$graph$series[["1"]]$end, configNew$dataRendering$gantt$graph$series[["1"]]$end)
expect_identical(configRaw$dataRendering$gantt$graph$series[["1"]]$title, configNew$dataRendering$gantt$graph$series[["1"]]$title)
expect_identical(configRaw$dataRendering$gantt$graph$series[["1"]]$group, configNew$dataRendering$gantt$graph$series[["1"]]$group)
expect_identical(configRaw$dataRendering$gantt$graph$filter$col, configNew$dataRendering$gantt$graph$filter$col)
expect_identical(configRaw$dataRendering$gantt$graph$filter$multiple, configNew$dataRendering$gantt$graph$filter$multiple)
expect_identical(configRaw$dataRendering$gantt$graph$filter$date, configNew$dataRendering$gantt$graph$filter$date)
expect_identical(configRaw$dataRendering$gantt$graph$filter$label, configNew$dataRendering$gantt$graph$filter$label)
expect_identical(configRaw$dataRendering$gantt$graph$custom[["1"]]$time, configNew$dataRendering$gantt$graph$custom[["1"]]$time)

# valuebox
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_train"]]$options$description, configNew$dataRendering[["_scalars_out"]][["error_train"]]$options$description)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_train"]]$options$color, configNew$dataRendering[["_scalars_out"]][["error_train"]]$options$color)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_train"]]$options$icon$name, configNew$dataRendering[["_scalars_out"]][["error_train"]]$options$icon$name)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_train"]]$options$icon$lib, configNew$dataRendering[["_scalars_out"]][["error_train"]]$options$icon$lib)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_train"]]$options$round, configNew$dataRendering[["_scalars_out"]][["error_train"]]$options$round)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_test"]]$options$description, configNew$dataRendering[["_scalars_out"]][["error_test"]]$options$description)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_test"]]$options$color, configNew$dataRendering[["_scalars_out"]][["error_test"]]$options$color)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_test"]]$options$icon$name, configNew$dataRendering[["_scalars_out"]][["error_test"]]$options$icon$name)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_test"]]$options$icon$lib, configNew$dataRendering[["_scalars_out"]][["error_test"]]$options$icon$lib)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_test"]]$options$round, configNew$dataRendering[["_scalars_out"]][["error_test"]]$options$round)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_ratio"]]$options$description, configNew$dataRendering[["_scalars_out"]][["error_ratio"]]$options$description)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_ratio"]]$options$color, configNew$dataRendering[["_scalars_out"]][["error_ratio"]]$options$color)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_ratio"]]$options$icon$name, configNew$dataRendering[["_scalars_out"]][["error_ratio"]]$options$icon$name)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_ratio"]]$options$icon$lib, configNew$dataRendering[["_scalars_out"]][["error_ratio"]]$options$icon$lib)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["error_ratio"]]$options$round, configNew$dataRendering[["_scalars_out"]][["error_ratio"]]$options$round)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["firstdaytraining"]]$options$description, configNew$dataRendering[["_scalars_out"]][["firstdaytraining"]]$options$description)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["firstdaytraining"]]$options$color, configNew$dataRendering[["_scalars_out"]][["firstdaytraining"]]$options$color)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["firstdaytraining"]]$options$icon$name, configNew$dataRendering[["_scalars_out"]][["firstdaytraining"]]$options$icon$name)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["firstdaytraining"]]$options$icon$lib, configNew$dataRendering[["_scalars_out"]][["firstdaytraining"]]$options$icon$lib)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["firstdaytraining"]]$options$round, configNew$dataRendering[["_scalars_out"]][["firstdaytraining"]]$options$round)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["lastdaytraining"]]$options$description, configNew$dataRendering[["_scalars_out"]][["lastdaytraining"]]$options$description)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["lastdaytraining"]]$options$color, configNew$dataRendering[["_scalars_out"]][["lastdaytraining"]]$options$color)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["lastdaytraining"]]$options$icon$name, configNew$dataRendering[["_scalars_out"]][["lastdaytraining"]]$options$icon$name)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["lastdaytraining"]]$options$icon$lib, configNew$dataRendering[["_scalars_out"]][["lastdaytraining"]]$options$icon$lib)
expect_identical(configRaw$dataRendering[["_scalars_out"]][["lastdaytraining"]]$options$round, configNew$dataRendering[["_scalars_out"]][["lastdaytraining"]]$options$round)

# time series diagram
expect_identical(configRaw$dataRendering$dowvsindex$outType, configNew$dataRendering$dowvsindex$outType)
expect_identical(configRaw$dataRendering$dowvsindex$height, configNew$dataRendering$dowvsindex$height)
expect_identical(configRaw$dataRendering$dowvsindex$graph$tool, configNew$dataRendering$dowvsindex$graph$tool)
expect_identical(configRaw$dataRendering$dowvsindex$graph$xdata, configNew$dataRendering$dowvsindex$graph$xdata)
expect_identical(configRaw$dataRendering$dowvsindex$graph$title, configNew$dataRendering$dowvsindex$graph$title)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyOptions$logscale, configNew$dataRendering$dowvsindex$graph$dyOptions$logscale)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyOptions$stepPlot, configNew$dataRendering$dowvsindex$graph$dyOptions$stepPlot)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyOptions$stemPlot, configNew$dataRendering$dowvsindex$graph$dyOptions$stemPlot)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyOptions$fillGraph, configNew$dataRendering$dowvsindex$graph$dyOptions$fillGraph)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyOptions$fillAlpha, configNew$dataRendering$dowvsindex$graph$dyOptions$fillAlpha)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyOptions$drawPoints, configNew$dataRendering$dowvsindex$graph$dyOptions$drawPoints)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyOptions$pointShape, configNew$dataRendering$dowvsindex$graph$dyOptions$pointShape)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyOptions$pointSize, configNew$dataRendering$dowvsindex$graph$dyOptions$pointSize)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyLegend$show, configNew$dataRendering$dowvsindex$graph$dyLegend$show)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyLegend$width, configNew$dataRendering$dowvsindex$graph$dyLegend$width)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyLegend$showZeroValues, configNew$dataRendering$dowvsindex$graph$dyLegend$showZeroValues)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyLegend$labelsSeparateLines, configNew$dataRendering$dowvsindex$graph$dyLegend$labelsSeparateLines)
expect_identical(configRaw$dataRendering$dowvsindex$graph$xaxis$name, configNew$dataRendering$dowvsindex$graph$xaxis$name)
expect_identical(configRaw$dataRendering$dowvsindex$graph$xaxis$label, configNew$dataRendering$dowvsindex$graph$xaxis$label)
expect_identical(configRaw$dataRendering$dowvsindex$graph$xaxis$axisLineWidth, configNew$dataRendering$dowvsindex$graph$xaxis$axisLineWidth)
expect_identical(configRaw$dataRendering$dowvsindex$graph$xaxis$axisLabelFontSize, configNew$dataRendering$dowvsindex$graph$xaxis$axisLabelFontSize)
expect_identical(configRaw$dataRendering$dowvsindex$graph$xaxis$gridLineWidth, configNew$dataRendering$dowvsindex$graph$xaxis$gridLineWidth)
expect_identical(configRaw$dataRendering$dowvsindex$graph$xaxis$drawGrid, configNew$dataRendering$dowvsindex$graph$xaxis$drawGrid)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis$name, configNew$dataRendering$dowvsindex$graph$yaxis$name)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis$label, configNew$dataRendering$dowvsindex$graph$yaxis$label)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis$axisLineWidth, configNew$dataRendering$dowvsindex$graph$yaxis$axisLineWidth)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis$axisLabelFontSize, configNew$dataRendering$dowvsindex$graph$yaxis$axisLabelFontSize)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis$gridLineWidth, configNew$dataRendering$dowvsindex$graph$yaxis$gridLineWidth)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis$gridLineColor, configNew$dataRendering$dowvsindex$graph$yaxis$gridLineColor)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis$valueRange, configNew$dataRendering$dowvsindex$graph$yaxis$valueRange)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis$independentTicks, configNew$dataRendering$dowvsindex$graph$yaxis$independentTicks)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis2$name, configNew$dataRendering$dowvsindex$graph$yaxis2$name)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis2$label, configNew$dataRendering$dowvsindex$graph$yaxis2$label)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis2$axisLineWidth, configNew$dataRendering$dowvsindex$graph$yaxis2$axisLineWidth)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis2$axisLabelFontSize, configNew$dataRendering$dowvsindex$graph$yaxis2$axisLabelFontSize)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis2$gridLineWidth, configNew$dataRendering$dowvsindex$graph$yaxis2$gridLineWidth)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis2$drawGrid, configNew$dataRendering$dowvsindex$graph$yaxis2$drawGrid)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis2$valueRange, configNew$dataRendering$dowvsindex$graph$yaxis2$valueRange)
expect_identical(configRaw$dataRendering$dowvsindex$graph$yaxis2$independentTicks, configNew$dataRendering$dowvsindex$graph$yaxis2$independentTicks)
expect_identical(configRaw$dataRendering$dowvsindex$graph$ydata[["dj"]]$label, configNew$dataRendering$dowvsindex$graph$ydata[["dj"]]$label)
expect_identical(configRaw$dataRendering$dowvsindex$graph$ydata[["dj"]]$stepPlot, configNew$dataRendering$dowvsindex$graph$ydata[["dj"]]$stepPlot)
expect_identical(configRaw$dataRendering$dowvsindex$graph$ydata[["dj"]]$stemPlot, configNew$dataRendering$dowvsindex$graph$ydata[["dj"]]$stemPlot)
expect_identical(configRaw$dataRendering$dowvsindex$graph$ydata[["dj"]]$fillGraph, configNew$dataRendering$dowvsindex$graph$ydata[["dj"]]$fillGraph)
expect_identical(configRaw$dataRendering$dowvsindex$graph$ydata[["dj"]]$drawpoints, configNew$dataRendering$dowvsindex$graph$ydata[["dj"]]$drawpoints)
expect_identical(configRaw$dataRendering$dowvsindex$graph$ydata[["index fund"]]$label, configNew$dataRendering$dowvsindex$graph$ydata[["index fund"]]$label)
expect_identical(configRaw$dataRendering$dowvsindex$graph$ydata[["index fund"]]$stepPlot, configNew$dataRendering$dowvsindex$graph$ydata[["index fund"]]$stepPlot)
expect_identical(configRaw$dataRendering$dowvsindex$graph$ydata[["index fund"]]$stemPlot, configNew$dataRendering$dowvsindex$graph$ydata[["index fund"]]$stemPlot)
expect_identical(configRaw$dataRendering$dowvsindex$graph$ydata[["index fund"]]$fillGraph, configNew$dataRendering$dowvsindex$graph$ydata[["index fund"]]$fillGraph)
expect_identical(configRaw$dataRendering$dowvsindex$graph$ydata[["index fund"]]$drawpoints, configNew$dataRendering$dowvsindex$graph$ydata[["index fund"]]$drawpoints)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyHighlight$hideOnMouseOut, configNew$dataRendering$dowvsindex$graph$dyHighlight$hideOnMouseOut)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyHighlight$highlightCircleSize, configNew$dataRendering$dowvsindex$graph$dyHighlight$highlightCircleSize)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyHighlight$highlightSeriesOpts$strokeWidth, configNew$dataRendering$dowvsindex$graph$dyHighlight$highlightSeriesOpts$strokeWidth)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyHighlight$highlightSeriesOpts$strokeBorderWidth, configNew$dataRendering$dowvsindex$graph$dyHighlight$highlightSeriesOpts$strokeBorderWidth)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyHighlight$highlightSeriesOpts$strokeBorderColor, configNew$dataRendering$dowvsindex$graph$dyHighlight$highlightSeriesOpts$strokeBorderColor)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyHighlight$highlightSeriesBackgroundAlpha, configNew$dataRendering$dowvsindex$graph$dyHighlight$highlightSeriesBackgroundAlpha)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyRangeSelector$height, configNew$dataRendering$dowvsindex$graph$dyRangeSelector$height)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyRangeSelector$strokeColor, configNew$dataRendering$dowvsindex$graph$dyRangeSelector$strokeColor)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyRangeSelector$fillColor, configNew$dataRendering$dowvsindex$graph$dyRangeSelector$fillColor)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyRangeSelector$retainDateWindow, configNew$dataRendering$dowvsindex$graph$dyRangeSelector$retainDateWindow)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyRangeSelector$keepMouseZoom, configNew$dataRendering$dowvsindex$graph$dyRangeSelector$keepMouseZoom)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyEvent$lastdaytraining$label, configNew$dataRendering$dowvsindex$graph$dyEvent$lastdaytraining$label)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyEvent$lastdaytraining$labelLoc, configNew$dataRendering$dowvsindex$graph$dyEvent$lastdaytraining$labelLoc)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyEvent$lastdaytraining$color, configNew$dataRendering$dowvsindex$graph$dyEvent$lastdaytraining$color)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyLimit[["1"]]$limit, configNew$dataRendering$dowvsindex$graph$dyLimit[["1"]]$limit)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyLimit[["1"]]$labelLoc, configNew$dataRendering$dowvsindex$graph$dyLimit[["1"]]$labelLoc)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyLimit[["1"]]$strokePattern, configNew$dataRendering$dowvsindex$graph$dyLimit[["1"]]$strokePattern)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyLimit[["1"]]$label, configNew$dataRendering$dowvsindex$graph$dyLimit[["1"]]$label)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyLimit[["1"]]$color, configNew$dataRendering$dowvsindex$graph$dyLimit[["1"]]$color)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyAnnotation$lastdaytraining$text, configNew$dataRendering$dowvsindex$graph$dyAnnotation$lastdaytraining$text)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyAnnotation$lastdaytraining$attachAtBottom, configNew$dataRendering$dowvsindex$graph$dyAnnotation$lastdaytraining$attachAtBottom)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyAnnotation$lastdaytraining$tooltip, configNew$dataRendering$dowvsindex$graph$dyAnnotation$lastdaytraining$tooltip)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyShading[["1"]]$from, configNew$dataRendering$dowvsindex$graph$dyShading[["1"]]$from)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyShading[["1"]]$to, configNew$dataRendering$dowvsindex$graph$dyShading[["1"]]$to)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyShading[["1"]]$axis, configNew$dataRendering$dowvsindex$graph$dyShading[["1"]]$axis)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyShading[["1"]]$color, configNew$dataRendering$dowvsindex$graph$dyShading[["1"]]$color)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyShading[["2"]]$from, configNew$dataRendering$dowvsindex$graph$dyShading[["2"]]$from)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyShading[["2"]]$to, configNew$dataRendering$dowvsindex$graph$dyShading[["2"]]$to)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyShading[["2"]]$axis, configNew$dataRendering$dowvsindex$graph$dyShading[["2"]]$axis)
expect_identical(configRaw$dataRendering$dowvsindex$graph$dyShading[["2"]]$color, configNew$dataRendering$dowvsindex$graph$dyShading[["2"]]$color)

# pie chart(s)
expect_identical(configRaw$dataRendering$repc$outType, configNew$dataRendering$repc$outType)
expect_identical(configRaw$dataRendering$repc$height, configNew$dataRendering$repc$height)
expect_identical(configRaw$dataRendering$repc$graph$title, configNew$dataRendering$repc$graph$title)
expect_identical(configRaw$dataRendering$repc$graph$tool, configNew$dataRendering$repc$graph$tool)
expect_identical(configRaw$dataRendering$repc$graph$type, configNew$dataRendering$repc$graph$type)
expect_identical(configRaw$dataRendering$repc$graph$showlegend, configNew$dataRendering$repc$graph$showlegend)
expect_identical(configRaw$dataRendering$repc$graph$staticPlot, configNew$dataRendering$repc$graph$staticPlot)
expect_identical(configRaw$dataRendering$repc$graph$traces[["1"]]$labels, configNew$dataRendering$repc$graph$traces[["1"]]$labels)
expect_identical(configRaw$dataRendering$repc$graph$traces[["1"]]$values, configNew$dataRendering$repc$graph$traces[["1"]]$values)
expect_identical(configRaw$dataRendering$repc$graph$traces[["1"]]$hole, configNew$dataRendering$repc$graph$traces[["1"]]$hole)
expect_identical(configRaw$dataRendering$repc$graph$traces[["1"]]$name, configNew$dataRendering$repc$graph$traces[["1"]]$name)
expect_identical(configRaw$dataRendering$repc$graph$traces[["2"]]$labels, configNew$dataRendering$repc$graph$traces[["2"]]$labels)
expect_identical(configRaw$dataRendering$repc$graph$traces[["2"]]$values, configNew$dataRendering$repc$graph$traces[["2"]]$values)
expect_identical(configRaw$dataRendering$repc$graph$traces[["2"]]$name, configNew$dataRendering$repc$graph$traces[["2"]]$name)
expect_identical(configRaw$dataRendering$repc$graph$traces[["2"]]$hole, configNew$dataRendering$repc$graph$traces[["2"]]$hole)
expect_identical(configRaw$dataRendering$repc$graph$traces[["3"]]$labels, configNew$dataRendering$repc$graph$traces[["3"]]$labels)
expect_identical(configRaw$dataRendering$repc$graph$traces[["3"]]$values, configNew$dataRendering$repc$graph$traces[["3"]]$values)
expect_identical(configRaw$dataRendering$repc$graph$traces[["3"]]$name, configNew$dataRendering$repc$graph$traces[["3"]]$name)
expect_identical(configRaw$dataRendering$repc$graph$traces[["3"]]$hole, configNew$dataRendering$repc$graph$traces[["3"]]$hole)
expect_identical(configRaw$dataRendering$repc$graph$traces[["4"]]$labels, configNew$dataRendering$repc$graph$traces[["4"]]$labels)
expect_identical(configRaw$dataRendering$repc$graph$traces[["4"]]$values, configNew$dataRendering$repc$graph$traces[["4"]]$values)
expect_identical(configRaw$dataRendering$repc$graph$traces[["4"]]$name, configNew$dataRendering$repc$graph$traces[["4"]]$name)
expect_identical(configRaw$dataRendering$repc$graph$traces[["4"]]$hole, configNew$dataRendering$repc$graph$traces[["4"]]$hole)
expect_identical(configRaw$dataRendering$repc$graph$traces[["5"]]$labels, configNew$dataRendering$repc$graph$traces[["5"]]$labels)
expect_identical(configRaw$dataRendering$repc$graph$traces[["5"]]$values, configNew$dataRendering$repc$graph$traces[["5"]]$values)
expect_identical(configRaw$dataRendering$repc$graph$traces[["5"]]$name, configNew$dataRendering$repc$graph$traces[["5"]]$name)
expect_identical(configRaw$dataRendering$repc$graph$traces[["5"]]$hole, configNew$dataRendering$repc$graph$traces[["5"]]$hole)
expect_identical(configRaw$dataRendering$repc$graph$traces[["6"]]$labels, configNew$dataRendering$repc$graph$traces[["6"]]$labels)
expect_identical(configRaw$dataRendering$repc$graph$traces[["6"]]$values, configNew$dataRendering$repc$graph$traces[["6"]]$values)
expect_identical(configRaw$dataRendering$repc$graph$traces[["6"]]$name, configNew$dataRendering$repc$graph$traces[["6"]]$name)
expect_identical(configRaw$dataRendering$repc$graph$traces[["6"]]$hole, configNew$dataRendering$repc$graph$traces[["6"]]$hole)
expect_identical(configRaw$dataRendering$repc$graph$traces[["7"]]$labels, configNew$dataRendering$repc$graph$traces[["7"]]$labels)
expect_identical(configRaw$dataRendering$repc$graph$traces[["7"]]$values, configNew$dataRendering$repc$graph$traces[["7"]]$values)
expect_identical(configRaw$dataRendering$repc$graph$traces[["7"]]$name, configNew$dataRendering$repc$graph$traces[["7"]]$name)
expect_identical(configRaw$dataRendering$repc$graph$traces[["7"]]$hole, configNew$dataRendering$repc$graph$traces[["7"]]$hole)

# bar chart
expect_identical(configRaw$dataRendering$stock_weight$outType, configNew$dataRendering$stock_weight$outType)
expect_identical(configRaw$dataRendering$stock_weight$graph$tool, configNew$dataRendering$stock_weight$graph$tool)
expect_identical(configRaw$dataRendering$stock_weight$graph$type, configNew$dataRendering$stock_weight$graph$type)
expect_identical(configRaw$dataRendering$stock_weight$graph$barmode, configNew$dataRendering$stock_weight$graph$barmode)
expect_identical(configRaw$dataRendering$stock_weight$graph$ydata$value$label, configNew$dataRendering$stock_weight$graph$ydata$value$label)
expect_identical(configRaw$dataRendering$stock_weight$graph$ydata$value$mode, configNew$dataRendering$stock_weight$graph$ydata$value$mode)
expect_identical(configRaw$dataRendering$stock_weight$graph$ydata$value$marker$line$width, configNew$dataRendering$stock_weight$graph$ydata$value$marker$line$width)
expect_identical(configRaw$dataRendering$stock_weight$graph$ydata$value$marker$line$color, configNew$dataRendering$stock_weight$graph$ydata$value$marker$line$color)
expect_identical(configRaw$dataRendering$stock_weight$graph$xdata, configNew$dataRendering$stock_weight$graph$xdata)
expect_identical(configRaw$dataRendering$stock_weight$graph$xaxis$title, configNew$dataRendering$stock_weight$graph$xaxis$title)
expect_identical(configRaw$dataRendering$stock_weight$graph$xaxis$showgrid, configNew$dataRendering$stock_weight$graph$xaxis$showgrid)
expect_identical(configRaw$dataRendering$stock_weight$graph$xaxis$zeroline, configNew$dataRendering$stock_weight$graph$xaxis$zeroline)
expect_identical(configRaw$dataRendering$stock_weight$graph$xaxis$showticklabels, configNew$dataRendering$stock_weight$graph$xaxis$showticklabels)
expect_identical(configRaw$dataRendering$stock_weight$graph$xaxis$categoryorder, configNew$dataRendering$stock_weight$graph$xaxis$categoryorder)
expect_identical(configRaw$dataRendering$stock_weight$graph$yaxis$title, configNew$dataRendering$stock_weight$graph$yaxis$title)
expect_identical(configRaw$dataRendering$stock_weight$graph$yaxis$showgrid, configNew$dataRendering$stock_weight$graph$yaxis$showgrid)
expect_identical(configRaw$dataRendering$stock_weight$graph$yaxis$zeroline, configNew$dataRendering$stock_weight$graph$yaxis$zeroline)
expect_identical(configRaw$dataRendering$stock_weight$graph$yaxis$showticklabels, configNew$dataRendering$stock_weight$graph$yaxis$showticklabels)
expect_identical(configRaw$dataRendering$stock_weight$graph$yaxis$categoryorder, configNew$dataRendering$stock_weight$graph$yaxis$categoryorder)
expect_identical(configRaw$dataRendering$stock_weight$graph$title, configNew$dataRendering$stock_weight$graph$title)
expect_identical(configRaw$dataRendering$stock_weight$graph$showlegend, configNew$dataRendering$stock_weight$graph$showlegend)
expect_identical(configRaw$dataRendering$stock_weight$graph$staticPlot, configNew$dataRendering$stock_weight$graph$staticPlot)
expect_identical(configRaw$dataRendering$stock_weight$graph$color, configNew$dataRendering$stock_weight$graph$color)
expect_identical(configRaw$dataRendering$stock_weight$graph$filter$col, configNew$dataRendering$stock_weight$graph$filter$col)
expect_identical(configRaw$dataRendering$stock_weight$graph$filter$label, configNew$dataRendering$stock_weight$graph$filter$label)
expect_identical(configRaw$dataRendering$stock_weight$graph$filter$multiple, configNew$dataRendering$stock_weight$graph$filter$multiple)
expect_identical(configRaw$dataRendering$stock_weight$graph$filter$date, configNew$dataRendering$stock_weight$graph$filter$date)
expect_identical(configRaw$dataRendering$stock_weight$graph$width, configNew$dataRendering$stock_weight$graph$width)
expect_identical(configRaw$dataRendering$stock_weight$graph$paper_bgcolor, configNew$dataRendering$stock_weight$graph$paper_bgcolor)
expect_identical(configRaw$dataRendering$stock_weight$graph$plot_bgcolor, configNew$dataRendering$stock_weight$graph$plot_bgcolor)
expect_identical(configRaw$dataRendering$stock_weight$height, configNew$dataRendering$stock_weight$height)

# line chart
expect_identical(configRaw$dataRendering$price$outType, configNew$dataRendering$price$outType)
expect_identical(configRaw$dataRendering$price$height, configNew$dataRendering$price$height)
expect_identical(configRaw$dataRendering$price$graph$tool, configNew$dataRendering$price$graph$tool)
expect_identical(configRaw$dataRendering$price$graph$type, configNew$dataRendering$price$graph$type)
expect_identical(configRaw$dataRendering$price$graph$ydata$value$mode, configNew$dataRendering$price$graph$ydata$value$mode)
expect_identical(configRaw$dataRendering$price$graph$ydata$value$line$width, configNew$dataRendering$price$graph$ydata$value$line$width)
expect_identical(configRaw$dataRendering$price$graph$ydata$value$line$shape, configNew$dataRendering$price$graph$ydata$value$line$shape)
expect_identical(configRaw$dataRendering$price$graph$ydata$value$line$dash, configNew$dataRendering$price$graph$ydata$value$line$dash)
expect_identical(configRaw$dataRendering$price$graph$ydata$value$showlegend, configNew$dataRendering$price$graph$ydata$value$showlegend)
expect_identical(configRaw$dataRendering$price$graph$ydata$value$yaxis, configNew$dataRendering$price$graph$ydata$value$yaxis)
expect_identical(configRaw$dataRendering$price$graph$ydata$value$fill, configNew$dataRendering$price$graph$ydata$value$fill)
expect_identical(configRaw$dataRendering$price$graph$xdata, configNew$dataRendering$price$graph$xdata)
expect_identical(configRaw$dataRendering$price$graph$xaxis$title, configNew$dataRendering$price$graph$xaxis$title)
expect_identical(configRaw$dataRendering$price$graph$xaxis$showgrid, configNew$dataRendering$price$graph$xaxis$showgrid)
expect_identical(configRaw$dataRendering$price$graph$xaxis$zeroline, configNew$dataRendering$price$graph$xaxis$zeroline)
expect_identical(configRaw$dataRendering$price$graph$xaxis$showticklabels, configNew$dataRendering$price$graph$xaxis$showticklabels)
expect_identical(configRaw$dataRendering$price$graph$xaxis$categoryorder, configNew$dataRendering$price$graph$xaxis$categoryorder)
expect_identical(configRaw$dataRendering$price$graph$yaxis$title, configNew$dataRendering$price$graph$yaxis$title)
expect_identical(configRaw$dataRendering$price$graph$yaxis$categoryorder, configNew$dataRendering$price$graph$yaxis$categoryorder)
expect_identical(configRaw$dataRendering$price$graph$yaxis$showgrid, configNew$dataRendering$price$graph$yaxis$showgrid)
expect_identical(configRaw$dataRendering$price$graph$yaxis$zeroline, configNew$dataRendering$price$graph$yaxis$zeroline)
expect_identical(configRaw$dataRendering$price$graph$yaxis$showticklabels, configNew$dataRendering$price$graph$yaxis$showticklabels)
expect_identical(configRaw$dataRendering$price$graph$y2axis$title, configNew$dataRendering$price$graph$y2axis$title)
expect_identical(configRaw$dataRendering$price$graph$y2axis$showgrid, configNew$dataRendering$price$graph$y2axis$showgrid)
expect_identical(configRaw$dataRendering$price$graph$y2axis$zeroline, configNew$dataRendering$price$graph$y2axis$zeroline)
expect_identical(configRaw$dataRendering$price$graph$y2axis$showticklabels, configNew$dataRendering$price$graph$y2axis$showticklabels)
expect_identical(configRaw$dataRendering$price$graph$y2axis$categoryorder, configNew$dataRendering$price$graph$y2axis$categoryorder)
expect_identical(configRaw$dataRendering$price$graph$y2axis$rangefrom, configNew$dataRendering$price$graph$y2axis$rangefrom)
expect_identical(configRaw$dataRendering$price$graph$y2axis$rangeto, configNew$dataRendering$price$graph$y2axis$rangeto)
expect_identical(configRaw$dataRendering$price$graph$title, configNew$dataRendering$price$graph$title)
expect_identical(configRaw$dataRendering$price$graph$showlegend, configNew$dataRendering$price$graph$showlegend)
expect_identical(configRaw$dataRendering$price$graph$staticPlot, configNew$dataRendering$price$graph$staticPlot)
expect_identical(configRaw$dataRendering$price$graph$color, configNew$dataRendering$price$graph$color)

# miro pivot
expect_identical(configRaw$dataRendering$pricemerge$outType, configNew$dataRendering$pricemerge$outType)
expect_identical(configRaw$dataRendering$pricemerge$height, configNew$dataRendering$pricemerge$height)
expect_identical(configRaw$dataRendering$pricemerge$options$aggregationFunction, configNew$dataRendering$pricemerge$options$aggregationFunction)
expect_identical(configRaw$dataRendering$pricemerge$options$pivotRenderer, configNew$dataRendering$pricemerge$options$pivotRenderer)
expect_identical(configRaw$dataRendering$pricemerge$options$rows, configNew$dataRendering$pricemerge$options$rows)
expect_identical(configRaw$dataRendering$pricemerge$options$cols$uni, configNew$dataRendering$pricemerge$options$cols$uni)

# table as line chart with two axes
expect_identical(configRaw$dataRendering$pressurethickness$outType, configNew$dataRendering$pressurethickness$outType)
expect_identical(configRaw$dataRendering$pressurethickness$graph$tool, configNew$dataRendering$pressurethickness$graph$tool)
expect_identical(configRaw$dataRendering$pressurethickness$graph$type, configNew$dataRendering$pressurethickness$graph$type)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$pressure$label, configNew$dataRendering$pressurethickness$graph$ydata$pressure$label)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$pressure$mode, configNew$dataRendering$pressurethickness$graph$ydata$pressure$mode)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$pressure$line$width, configNew$dataRendering$pressurethickness$graph$ydata$pressure$line$width)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$pressure$line$shape, configNew$dataRendering$pressurethickness$graph$ydata$pressure$line$shape)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$pressure$line$dash, configNew$dataRendering$pressurethickness$graph$ydata$pressure$line$dash)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$pressure$showlegend, configNew$dataRendering$pressurethickness$graph$ydata$pressure$showlegend)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$pressure$yaxis, configNew$dataRendering$pressurethickness$graph$ydata$pressure$yaxis)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$thickness$label, configNew$dataRendering$pressurethickness$graph$ydata$thickness$label)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$thickness$mode, configNew$dataRendering$pressurethickness$graph$ydata$thickness$mode)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$thickness$line$width, configNew$dataRendering$pressurethickness$graph$ydata$thickness$line$width)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$thickness$line$shape, configNew$dataRendering$pressurethickness$graph$ydata$thickness$line$shape)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$thickness$line$dash, configNew$dataRendering$pressurethickness$graph$ydata$thickness$line$dash)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$thickness$showlegend, configNew$dataRendering$pressurethickness$graph$ydata$thickness$showlegend)
expect_identical(configRaw$dataRendering$pressurethickness$graph$ydata$thickness$yaxis, configNew$dataRendering$pressurethickness$graph$ydata$thickness$yaxis)
expect_identical(configRaw$dataRendering$pressurethickness$graph$yaxis$title, configNew$dataRendering$pressurethickness$graph$yaxis$title)
expect_identical(configRaw$dataRendering$pressurethickness$graph$yaxis$showgrid, configNew$dataRendering$pressurethickness$graph$yaxis$showgrid)
expect_identical(configRaw$dataRendering$pressurethickness$graph$yaxis$zeroline, configNew$dataRendering$pressurethickness$graph$yaxis$zeroline)
expect_identical(configRaw$dataRendering$pressurethickness$graph$yaxis$showticklabels, configNew$dataRendering$pressurethickness$graph$yaxis$showticklabels)
expect_identical(configRaw$dataRendering$pressurethickness$graph$yaxis$categoryorder, configNew$dataRendering$pressurethickness$graph$yaxis$categoryorder)
expect_identical(configRaw$dataRendering$pressurethickness$graph$y2axis$title, configNew$dataRendering$pressurethickness$graph$y2axis$title)
expect_identical(configRaw$dataRendering$pressurethickness$graph$y2axis$showgrid, configNew$dataRendering$pressurethickness$graph$y2axis$showgrid)
expect_identical(configRaw$dataRendering$pressurethickness$graph$y2axis$zeroline, configNew$dataRendering$pressurethickness$graph$y2axis$zeroline)
expect_identical(configRaw$dataRendering$pressurethickness$graph$y2axis$showticklabels, configNew$dataRendering$pressurethickness$graph$y2axis$showticklabels)
expect_identical(configRaw$dataRendering$pressurethickness$graph$y2axis$categoryorder, configNew$dataRendering$pressurethickness$graph$y2axis$categoryorder)

# animation options
expect_identical(configRaw$dataRendering$hovercraft$outType, configNew$dataRendering$hovercraft$outType)
expect_identical(configRaw$dataRendering$hovercraft$height, configNew$dataRendering$hovercraft$height)
expect_identical(configRaw$dataRendering$hovercraft$graph$tool, configNew$dataRendering$hovercraft$graph$tool)
expect_identical(configRaw$dataRendering$hovercraft$graph$type, configNew$dataRendering$hovercraft$graph$type)
expect_identical(configRaw$dataRendering$hovercraft$graph$ydata$y$mode, configNew$dataRendering$hovercraft$graph$ydata$y$mode)
expect_identical(configRaw$dataRendering$hovercraft$graph$ydata$y$fill, configNew$dataRendering$hovercraft$graph$ydata$y$fill)
expect_identical(configRaw$dataRendering$hovercraft$graph$ydata$y$marker$opacity, configNew$dataRendering$hovercraft$graph$ydata$y$marker$opacity)
expect_identical(configRaw$dataRendering$hovercraft$graph$ydata$y$marker$size, configNew$dataRendering$hovercraft$graph$ydata$y$marker$size)
expect_identical(configRaw$dataRendering$hovercraft$graph$ydata$y$marker$line$width, configNew$dataRendering$hovercraft$graph$ydata$y$marker$line$width)
expect_identical(configRaw$dataRendering$hovercraft$graph$ydata$y$showlegend, configNew$dataRendering$hovercraft$graph$ydata$y$showlegend)
expect_identical(configRaw$dataRendering$hovercraft$graph$ydata$y$yaxis, configNew$dataRendering$hovercraft$graph$ydata$y$yaxis)
expect_identical(configRaw$dataRendering$hovercraft$graph$ydata$y$frame, configNew$dataRendering$hovercraft$graph$ydata$y$frame)
expect_identical(configRaw$dataRendering$hovercraft$graph$xdata, configNew$dataRendering$hovercraft$graph$xdata)
expect_identical(configRaw$dataRendering$hovercraft$graph$xaxis$title, configNew$dataRendering$hovercraft$graph$xaxis$title)
expect_identical(configRaw$dataRendering$hovercraft$graph$xaxis$showgrid, configNew$dataRendering$hovercraft$graph$xaxis$showgrid)
expect_identical(configRaw$dataRendering$hovercraft$graph$xaxis$zeroline, configNew$dataRendering$hovercraft$graph$xaxis$zeroline)
expect_identical(configRaw$dataRendering$hovercraft$graph$xaxis$showticklabels, configNew$dataRendering$hovercraft$graph$xaxis$showticklabels)
expect_identical(configRaw$dataRendering$hovercraft$graph$xaxis$categoryorder, configNew$dataRendering$hovercraft$graph$xaxis$categoryorder)
expect_identical(configRaw$dataRendering$hovercraft$graph$xaxis$rangefrom, configNew$dataRendering$hovercraft$graph$xaxis$rangefrom)
expect_identical(configRaw$dataRendering$hovercraft$graph$xaxis$rangeto, configNew$dataRendering$hovercraft$graph$xaxis$rangeto)
expect_identical(configRaw$dataRendering$hovercraft$graph$yaxis$title, configNew$dataRendering$hovercraft$graph$yaxis$title)
expect_identical(configRaw$dataRendering$hovercraft$graph$yaxis$showgrid, configNew$dataRendering$hovercraft$graph$yaxis$showgrid)
expect_identical(configRaw$dataRendering$hovercraft$graph$yaxis$zeroline, configNew$dataRendering$hovercraft$graph$yaxis$zeroline)
expect_identical(configRaw$dataRendering$hovercraft$graph$yaxis$showticklabels, configNew$dataRendering$hovercraft$graph$yaxis$showticklabels)
expect_identical(configRaw$dataRendering$hovercraft$graph$yaxis$categoryorder, configNew$dataRendering$hovercraft$graph$yaxis$categoryorder)
expect_identical(configRaw$dataRendering$hovercraft$graph$yaxis$rangefrom, configNew$dataRendering$hovercraft$graph$yaxis$rangefrom)
expect_identical(configRaw$dataRendering$hovercraft$graph$yaxis$rangeto, configNew$dataRendering$hovercraft$graph$yaxis$rangeto)
expect_identical(configRaw$dataRendering$hovercraft$graph$y2axis$title, configNew$dataRendering$hovercraft$graph$y2axis$title)
expect_identical(configRaw$dataRendering$hovercraft$graph$y2axis$showgrid, configNew$dataRendering$hovercraft$graph$y2axis$showgrid)
expect_identical(configRaw$dataRendering$hovercraft$graph$y2axis$zeroline, configNew$dataRendering$hovercraft$graph$y2axis$zeroline)
expect_identical(configRaw$dataRendering$hovercraft$graph$y2axis$showticklabels, configNew$dataRendering$hovercraft$graph$y2axis$showticklabels)
expect_identical(configRaw$dataRendering$hovercraft$graph$y2axis$categoryorder, configNew$dataRendering$hovercraft$graph$y2axis$categoryorder)
expect_identical(configRaw$dataRendering$hovercraft$graph$color, configNew$dataRendering$hovercraft$graph$color)
expect_identical(configRaw$dataRendering$hovercraft$graph$title, configNew$dataRendering$hovercraft$graph$title)
expect_identical(configRaw$dataRendering$hovercraft$graph$showlegend, configNew$dataRendering$hovercraft$graph$showlegend)
expect_identical(configRaw$dataRendering$hovercraft$graph$staticPlot, configNew$dataRendering$hovercraft$graph$staticPlot)
expect_identical(configRaw$dataRendering$hovercraft$graph$animation$easing, configNew$dataRendering$hovercraft$graph$animation$easing)
expect_identical(configRaw$dataRendering$hovercraft$graph$animation$mode, configNew$dataRendering$hovercraft$graph$animation$mode)
expect_identical(configRaw$dataRendering$hovercraft$graph$animation$redraw, configNew$dataRendering$hovercraft$graph$animation$redraw)
expect_identical(configRaw$dataRendering$hovercraft$graph$animation$frame, configNew$dataRendering$hovercraft$graph$animation$frame)
expect_identical(configRaw$dataRendering$hovercraft$graph$animation$transition, configNew$dataRendering$hovercraft$graph$animation$transition)
expect_identical(configRaw$dataRendering$hovercraft$graph$animation$slider$hide, configNew$dataRendering$hovercraft$graph$animation$slider$hide)
expect_identical(configRaw$dataRendering$hovercraft$graph$animation$slider$fontcolor, configNew$dataRendering$hovercraft$graph$animation$slider$fontcolor)
expect_identical(configRaw$dataRendering$hovercraft$graph$animation$slider$prefix, configNew$dataRendering$hovercraft$graph$animation$slider$prefix)
expect_identical(configRaw$dataRendering$hovercraft$graph$plot_bgcolor, configNew$dataRendering$hovercraft$graph$plot_bgcolor)

app$stop()
