app <- AppDriver$new("../../", name = paste0("csv_upload_test_", Sys.getenv("GMSMODELNAME")), variant = NULL, load_timeout = 20000)

widgetSheetId <- 1L
if (identical(Sys.getenv("GMSMODELNAME"), "pickstock")) {
  widgetSheetId <- 2L
} else if (identical(Sys.getenv("GMSMODELNAME"), "transport")) {
  widgetSheetId <- 7L
}
app$set_inputs(inputTabset = paste0("inputTabset_", widgetSheetId))
if (!identical(Sys.getenv("GMSMODELNAME"), "pickstock")) {
  Sys.sleep(1)
  app$expect_values(input = paste0("slider_", c(widgetSheetId, widgetSheetId + 1L)))
}
app$set_inputs(btImport = "click")
app$set_inputs(tb_importData = "tb_importData_local")
app$upload_file(localInput = paste0("../data/", Sys.getenv("GMSMODELNAME"), ".zip"))
app$set_inputs(btImportLocal = "click")
app$set_inputs(inputTabset = paste0("inputTabset_", widgetSheetId))
app$expect_values(input = paste0("slider_", c(widgetSheetId, widgetSheetId + 1L)))
if (identical(Sys.getenv("GMSMODELNAME"), "pickstock")) {
  app$set_inputs(inputTabset = "inputTabset_1")
  expect_identical(
    length(jsonlite::fromJSON(app$get_values()$output[["in_1"]])$x$data[[1]]),
    7560L
  )
  app$click(selector = "#btRemove1")
  Sys.sleep(0.5)
  app$click(selector = ".modal-footer .bt-gms-confirm")
  Sys.sleep(0.5)
  app$set_inputs(btImport = "click")
  Sys.sleep(1)
  app$set_inputs(tb_importData = "tb_importData_local")
  app$upload_file(localInput = paste0("../data/price.csv"))
  app$set_inputs(btImportLocal = "click")
  app$set_inputs(inputTabset = paste0("inputTabset_", widgetSheetId))
  app$expect_values(input = paste0("slider_", c(widgetSheetId, widgetSheetId + 1L)))
  app$set_inputs(btImport = "click")
  Sys.sleep(1)
  app$set_inputs(tb_importData = "tb_importData_local")
  app$upload_file(localInput = paste0("../data/_scalars2.csv"))
  Sys.sleep(1)
  app$set_inputs(selInputDataLocCSV = scalarsFileName)
  Sys.sleep(0.5)
  app$set_inputs(btImportLocal = "click")
  Sys.sleep(0.5)
  app$expect_values(input = c(
    paste0("slider_", c(widgetSheetId, widgetSheetId + 1L)),
    "dropdown_4"
  ))
  app$click(selector = "#btRemove1")
  Sys.sleep(0.5)
  app$click(selector = ".modal-footer .bt-gms-confirm")
  Sys.sleep(0.5)
  app$set_inputs(btImport = "click")
  app$set_inputs(tb_importData = "tb_importData_local")
  app$upload_file(localInput = paste0("../data/price.csv"))
  app$set_inputs(btImportLocal = "click")
  Sys.sleep(1)
  app$set_inputs(inputTabset = paste0("inputTabset_", widgetSheetId - 1L))
  priceData <- getHotData(app, "in_1")
  expect_identical(priceData[[1]][1:3], c("2016-01-04", "2016-01-04", "2016-01-04"))
  expect_identical(priceData[[2]][1:3], c("AAPL", "AXP", "BA"))
  expect_identical(priceData[[3]][1:3], c(105.349998, 67.589996, 140.5))
  expect_identical(nrow(priceData), 7560L)
  app$set_inputs(btImport = "click")
  app$set_inputs(tb_importData = "tb_importData_local")
  app$upload_file(localInput = paste0("../data/price.psv"))
  Sys.sleep(1)
  expect_options(getSelectizeOptions(app, "#csvInputHdr_1"), c("-", "bla1", "date", "symbol", "value", "value2"))
  expect_identical(app$get_value(input = "selInputDataLocCSV"), "price")
  app$set_inputs(csvInputHdr_2 = "bla1")
  Sys.sleep(0.5)
  app$set_inputs(btImportLocal = "click")
  Sys.sleep(1)
  expect_error(app$wait_for_js("$('#localDataImportError').is(':visible')", timeout = 50), NA)
  expect_true(grepl("same column", app$get_text(selector = "#localDataImportError"), fixed = TRUE))
  app$set_inputs(csvInputHdr_1 = "symbol", csvInputHdr_2 = "date", csvInputHdr_3 = "value")
  app$set_inputs(btImportLocal = "click")
  Sys.sleep(0.5)
  app$set_inputs(btReplaceInputData = "click")
  priceData <- getHotData(app, "in_1")
  expect_identical(priceData[[1]][1:3], c("AAPL", "AXP", "BA"))
  expect_identical(priceData[[2]][1:3], c("2016-01-04", "2016-01-04", "2016-01-04"))
  expect_identical(priceData[[3]][1:3], c(105.349998, 67.589996, 140.5))
  expect_identical(nrow(priceData), 7560L)
  app$set_inputs(btImport = "click")
  app$set_inputs(tb_importData = "tb_importData_local")
  app$upload_file(localInput = paste0("../data/csvtest-ambig.csv"))
  Sys.sleep(1)
  expect_error(app$wait_for_js("$('#localDataImportError').is(':visible')", timeout = 50), NA)
  expect_true(grepl("could not be identified uniquely", app$get_text(selector = "#localDataImportError"), fixed = TRUE))
  app$upload_file(localInput = paste0("../data/csvtest-bad.csv"))
  Sys.sleep(1)
  expect_error(app$wait_for_js("$('#localDataImportError').is(':visible')", timeout = 50), NA)
  expect_true(grepl("is not UTF-8 encoded", app$get_text(selector = "#localDataImportError"), fixed = TRUE))
  app$upload_file(localInput = paste0("../data/csvtest-bad2.csv"))
  Sys.sleep(1)
  expect_options(getSelectizeOptions(app, "#csvInputHdr_1"), c("-", "header1header 2"))
  app$set_inputs(csvInputHdr_1 = "-")
  app$set_inputs(btImportLocal = "click")
  Sys.sleep(0.5)
  expect_error(app$wait_for_js("$('#localDataImportError').is(':visible')", timeout = 50), NA)
  expect_true(grepl("at least one column to import", app$get_text(selector = "#localDataImportError"), fixed = TRUE))
  app$upload_file(localInput = paste0("../data/price.psv"))
  Sys.sleep(1)
  app$set_inputs(csvInputHdr_1 = "date", csvInputHdr_2 = "-", csvInputHdr_3 = "value")
  app$set_inputs(btImportLocal = "click")
  Sys.sleep(0.5)
  app$set_inputs(btReplaceInputData = "click")
  Sys.sleep(2)
  priceData <- getHotData(app, "in_1")
  expect_identical(priceData[[1]][1:3], c("2016-01-04", "2016-01-04", "2016-01-04"))
  expect_identical(priceData[[2]][1:3], c("", "", ""))
  expect_identical(priceData[[3]][1:3], c(105.349998, 67.589996, 140.5))
  expect_identical(nrow(priceData), 7560L)
} else if (identical(Sys.getenv("GMSMODELNAME"), "transport")) {
  app$set_inputs(inputTabset = "inputTabset_1")
  app$set_inputs(btImport = "click")
  Sys.sleep(0.5)
  app$set_inputs(tb_importData = "tb_importData_local")
  app$upload_file(localInput = paste0("../data/a.csv"))
  app$set_inputs(btImportLocal = "click")
  app$set_inputs(btMergeInputData = "click")
  Sys.sleep(1)
  expect_equal(getHotData(app, "in_1"),
    tibble(
      i = c("Seattle", "San-Diego", "Boston"),
      value = c(123L, 600L, 456L)
    ),
    check.attributes = FALSE
  )
}
app$stop()
