app <- AppDriver$new("../../",
  name = "custom_importer_test", variant = NULL,
  load_timeout = as.integer(Sys.getenv("MIRO_TEST_LOAD_TIMEOUT", "20000")),
  timeout = as.integer(Sys.getenv("MIRO_TEST_TIMEOUT", "4000"))
)

app$set_inputs(btImport = "click")
Sys.sleep(0.5)
app$set_inputs(tb_importData = "tb_importData_external")
expect_identical(
  getSelectizeOptions(app, "#selExternalSource"),
  list("Importer without file", "Importer with file", "JSON import")
)
Sys.sleep(0.5)
expect_error(app$wait_for_js("$('#externalSourceFile_2').is(':hidden')", timeout = 50L), NA)
app$set_inputs(selExternalSource = "Importer with file")
Sys.sleep(0.5)
expect_error(app$wait_for_js("$('#externalSourceFile_2').is(':visible')", timeout = 50L), NA)
expect_error(app$wait_for_js("$('#externalSourceFile_2').attr('multiple')==='multiple'", timeout = 50L), NA)
expect_error(app$wait_for_js("$('#externalSourceFile_2').attr('accept')==='.csv,text/csv'", timeout = 50L), NA)
app$set_inputs(selExternalSource = "Importer without file")
Sys.sleep(0.1)
expect_error(app$wait_for_js("$('#externalSourceFile_2').is(':hidden')", timeout = 50L), NA)
app$set_inputs(btImportExternal = "click")
Sys.sleep(1)
expect_equivalent(getHotData(app, "in_1"), tibble(i = "isBadA", value = 0L))
app$set_inputs(inputTabset = "inputTabset_2")
expect_equivalent(getHotData(app, "in_2"), tibble(j = "isBadB", value = 0L))
expect_identical(app$get_text(selector = "#inputDataTitle"), "<HeyHey> (*)")
app$set_inputs(inputTabset = "inputTabset_5")
expect_identical(app$get_values()$input[["slider_6"]], 20L)
expect_identical(app$get_values()$input[["slider_8"]], 0.11)
app$set_inputs(inputTabset = "inputTabset_2")
app$set_inputs(btEditMeta = "click")
Sys.sleep(2)
expect_identical(app$get_values()$input$editMetaName, "HeyHey")
expect_identical(app$get_values()$input$editMetaTags, c("heyhey", "hoho"))
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(1)
app$set_inputs(btImport = "click")
Sys.sleep(0.5)
app$set_inputs(tb_importData = "tb_importData_external")
app$set_inputs(selExternalSource = "Importer with file")
app$upload_file(externalSourceFile_2 = "../data/a.csv")
Sys.sleep(0.5)
app$set_inputs(btImportExternal = "click")
Sys.sleep(0.5)
app$set_inputs(btMergeInputData = "click")
Sys.sleep(1)
expect_equivalent(getHotData(app, "in_2"), tibble(j = c("isBadB", "isGoodB"), value = c(0L, 1L)))
app$set_inputs(btEditMeta = "click")
Sys.sleep(2)
app$click(selector = '#editMetaUI a[data-value="attachments"]')
Sys.sleep(0.5)
expect_error(app$wait_for_js("$('.attachment-line a').text().trim()==='test.csv'", timeout = 50L), NA)
expect_error(app$wait_for_js("$('.attachment-line input').is(':checked')===false", timeout = 50L), NA)
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(1)
app$set_inputs(btImport = "click")
Sys.sleep(0.5)
app$set_inputs(tb_importData = "tb_importData_external")
app$set_inputs(selExternalSource = "Importer with file")
Sys.sleep(0.5)
app$set_inputs(btImportExternal = "click")
Sys.sleep(0.5)
app$set_inputs(btReplaceInputData = "click")
Sys.sleep(1)
expect_error(app$wait_for_js("$('.modal-body').is(':visible')&&$('.modal-body').text().trim()==='No file provided'"), NA)
app$stop()
