app <- AppDriver$new("../../",
  name = "custom_exporter_test", variant = NULL,
  load_timeout = as.integer(Sys.getenv("MIRO_TEST_LOAD_TIMEOUT", "20000")),
  timeout = as.integer(Sys.getenv("MIRO_TEST_TIMEOUT", "4000"))
)

app$run_js("$('.navbar-custom-menu a.dropdown-toggle')[0].get(1).click();")
app$click(selector = ".navbar-custom-menu a[onclick*='btExportScen']")
Sys.sleep(1)
app$set_inputs(exportFileType = "custom_1")
expect_error(app$wait_for_js("$('#scenRemoteExportHandler').is(':visible')&&$('#scenExportHandler').is(':hidden')", timeout = 50L), NA)
app$set_inputs(scenRemoteExportHandler = "click")
Sys.sleep(1)
expect_error(app$wait_for_js("$('.modal-body').is(':visible')&&$('.modal-body').text().trim()==='Bad, bad, bad...'", timeout = 50L), NA)
app$run_js('$(\'button[data-dismiss="modal"]:visible\').click();')
Sys.sleep(1L)

app$set_inputs(btImport = "click")
Sys.sleep(0.5)
app$set_inputs(tb_importData = "tb_importData_local")
app$upload_file(localInput = "../data/transport_full.gdx")
Sys.sleep(0.5)
app$set_inputs(btImportLocal = "click")
Sys.sleep(1L)
app$run_js("$('.navbar-custom-menu a.dropdown-toggle')[0].get(1).click();")
app$click(selector = ".navbar-custom-menu a[onclick*='btExportScen']")
Sys.sleep(1)
app$set_inputs(exportFileType = "custom_1")
app$set_inputs(scenRemoteExportHandler = "click")
Sys.sleep(1)
app$wait_for_js("$('.modal-body').is(':visible')===false;", timeout = 2000L)
app$run_js('$(\'button[data-dismiss="modal"]:visible\').click();')
Sys.sleep(1L)

app$set_inputs(btImport = "click")
Sys.sleep(0.5)
app$set_inputs(tb_importData = "tb_importData_local")
app$upload_file(localInput = "../data/transport.miroscen")
Sys.sleep(0.5)
app$set_inputs(btImportLocal = "click")
Sys.sleep(0.5)
app$set_inputs(btOverwriteScenLocal = "click")
Sys.sleep(1L)

# test custom import/export function from documentation
app$run_js("$('.navbar-custom-menu a.dropdown-toggle')[0].get(1).click();")
app$click(selector = ".navbar-custom-menu a[onclick*='btExportScen']")
Sys.sleep(1)
app$set_inputs(exportFileType = "custom_2")
Sys.sleep(0.5)
expect_true(app$get_js("$('#scenRemoteExportHandler').is(':hidden')&&$('#scenExportHandler').is(':visible');", timeout = 50L))

tempJSONFile <- tempfile()
readr::write_file(get_file_content(app, "scenExportHandler"), tempJSONFile)
expect_identical(jsonlite::read_json(tempJSONFile)$isValid, list(TRUE))
Sys.sleep(1)
app$click(selector = "#btRemove1")
Sys.sleep(0.5)
app$click(selector = ".modal-footer .bt-gms-confirm")
Sys.sleep(0.5)
expect_equivalent(getHotData(app, "in_1"), tibble(i = "", value = "NA"))

app$set_inputs(btImport = "click")
Sys.sleep(0.5)
app$set_inputs(tb_importData = "tb_importData_external")
app$set_inputs(selExternalSource = "JSON import")
app$upload_file(externalSourceFile_3 = tempJSONFile)
Sys.sleep(0.5)
app$set_inputs(btImportExternal = "click")
Sys.sleep(0.5)
expect_equivalent(getHotData(app, "in_1"), tibble(
  i = c("Seattle", "San-Diego"),
  value = c(350L, 600L)
))
expect_true(app$get_js("$('.modal-body').is(':visible')===false", timeout = 50L))
unlink(tempJSONFile)
app$stop()
