app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("custom_exporter_test")

app$snapshot(
  items = list(output = "inputDataTitle"),
  screenshot = TRUE
)

app$findElements(".navbar-custom-menu a.dropdown-toggle")[[1]]$click()
app$findElement(".navbar-custom-menu a[onclick*='btExportScen']")$click()
Sys.sleep(1)
app$setInputs(exportFileType = "custom_1")
expect_true(app$waitFor("$('#scenRemoteExportHandler').is(':visible')&&$('#scenExportHandler').is(':hidden')", timeout = 50L))
app$setInputs(scenRemoteExportHandler = "click")
Sys.sleep(1)
expect_true(app$waitFor("$('.modal-body').is(':visible')&&$('.modal-body').text().trim()==='Bad, bad, bad...'", timeout = 50L))
app$waitFor('$(\'button[data-dismiss="modal"]:visible\').click();true;', timeout = 50)
Sys.sleep(1L)

app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(tb_importData = "tb_importData_local")
app$uploadFile(localInput = "../data/transport_full.gdx")
Sys.sleep(0.5)
app$setInputs(btImportLocal = "click")
Sys.sleep(1L)
app$findElements(".navbar-custom-menu a.dropdown-toggle")[[1]]$click()
app$findElement(".navbar-custom-menu a[onclick*='btExportScen']")$click()
Sys.sleep(1)
app$setInputs(exportFileType = "custom_1")
app$setInputs(scenRemoteExportHandler = "click")
Sys.sleep(1)
expect_false(app$waitFor("$('.modal-body').is(':visible')", timeout = 2000L))
app$waitFor('$(\'button[data-dismiss="modal"]:visible\').click();true;', timeout = 50)
Sys.sleep(1L)

app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(tb_importData = "tb_importData_local")
app$uploadFile(localInput = "../data/transport.miroscen")
Sys.sleep(0.5)
app$setInputs(btImportLocal = "click")
Sys.sleep(0.5)
app$setInputs(btOverwriteScenLocal = "click")
Sys.sleep(1L)

# test custom import/export function from documentation
app$findElements(".navbar-custom-menu a.dropdown-toggle")[[1]]$click()
app$findElement(".navbar-custom-menu a[onclick*='btExportScen']")$click()
Sys.sleep(1)
app$setInputs(exportFileType = "custom_2")
Sys.sleep(0.5)
expect_true(app$waitFor("$('#scenRemoteExportHandler').is(':hidden')&&$('#scenExportHandler').is(':visible')", timeout = 50L))

tempJSONFile <- tempfile()
readr::write_file(get_file_content(app, "scenExportHandler"), tempJSONFile)
expect_identical(jsonlite::read_json(tempJSONFile)$isValid, list(TRUE))
Sys.sleep(1)
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(0.5)
expect_equivalent(getHotData(app, "in_1"), tibble(i = "", value = "NA"))

app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(tb_importData = "tb_importData_external")
app$setInputs(selExternalSource = "JSON import")
app$uploadFile(externalSourceFile_3 = tempJSONFile)
Sys.sleep(0.5)
app$setInputs(btImportExternal = "click")
Sys.sleep(0.5)
expect_equivalent(getHotData(app, "in_1"), tibble(
  i = c("Seattle", "San-Diego"),
  value = c(350L, 600L)
))
expect_true(app$waitFor("$('.modal-body').is(':visible')===false", timeout = 50L))
unlink(tempJSONFile)
app$stop()
