app <- AppDriver$new("../../",
  name = "download_files_test", variant = NULL,
  load_timeout = as.integer(Sys.getenv("MIRO_TEST_LOAD_TIMEOUT", "20000")),
  timeout = as.integer(Sys.getenv("MIRO_TEST_TIMEOUT", "4000"))
)
Sys.sleep(2)

app$set_inputs(btImport = "click")
Sys.sleep(0.5)
app$set_inputs(btLoadScenConfirm = "click")
Sys.sleep(1)

# export all file types
app$run_js("$('.navbar-custom-menu a.dropdown-toggle').get(0).click()")
app$click(selector = ".navbar-custom-menu a[onclick*='btExportScen']")
Sys.sleep(1)
app$set_inputs(exportFileType = "miroscen")
Sys.sleep(0.5)
expect_true(app$get_js("$('#shiny-modal .gmsalert-error').is(':hidden');", timeout = 50))
expect_true(app$get_js("$('#shiny-modal .choose-input').is(':hidden');", timeout = 50))
expect_download_size(app, "scenExportHandler", "scenExport.miroscen")

app$run_js("$('.navbar-custom-menu a.dropdown-toggle').get(0).click()")
app$click(selector = ".navbar-custom-menu a[onclick*='btExportScen']")
Sys.sleep(1)
app$set_inputs(exportFileType = "gdx")
Sys.sleep(0.5)
expect_true(app$get_js("$('#shiny-modal .gmsalert-error').is(':visible');", timeout = 50))
expect_true(app$get_js("$('#shiny-modal .choose-input').is(':visible');", timeout = 50))
app$expect_download("scenExportHandler", name = "scenExport.gdx")

app$run_js("$('.navbar-custom-menu a.dropdown-toggle').get(0).click()")
app$click(selector = ".navbar-custom-menu a[onclick*='btExportScen']")
Sys.sleep(1)
app$set_inputs(exportFileType = "xlsx")
Sys.sleep(0.5)
expect_true(app$get_js("$('#shiny-modal .gmsalert-error').is(':visible');", timeout = 50))
expect_true(app$get_js("$('#shiny-modal .choose-input').is(':visible');", timeout = 50))
expect_download_size(app, "scenExportHandler", "scenExport.xlsx")

app$run_js("$('.navbar-custom-menu a.dropdown-toggle').get(0).click()")
app$click(selector = ".navbar-custom-menu a[onclick*='btExportScen']")
Sys.sleep(1)
app$set_inputs(exportFileType = "csv")
Sys.sleep(0.5)
expect_true(app$get_js("$('#shiny-modal .gmsalert-error').is(':visible');", timeout = 50))
expect_true(app$get_js("$('#shiny-modal .choose-input').is(':visible');", timeout = 50))
expect_download_size(app, "scenExportHandler", "scenExport.zip")

# export all file types for manually selected symbol
app$run_js("$('.navbar-custom-menu a.dropdown-toggle').get(0).click()")
app$click(selector = ".navbar-custom-menu a[onclick*='btExportScen']")
Sys.sleep(1)
app$set_inputs(exportFileType = "gdx")
Sys.sleep(0.5)
expect_true(app$get_js("$('#shiny-modal .gmsalert-error').is(':visible');", timeout = 50))
expect_true(app$get_js("$('#shiny-modal .choose-input').is(':visible');", timeout = 50))
app$set_inputs(cbSelectManuallyExp = TRUE)
app$set_inputs(selDataToExport = "a")
app$expect_download("scenExportHandler", name = "scenExport_manual.gdx")

app$run_js("$('.navbar-custom-menu a.dropdown-toggle').get(0).click()")
app$click(selector = ".navbar-custom-menu a[onclick*='btExportScen']")
Sys.sleep(1)
app$set_inputs(exportFileType = "xlsx")
Sys.sleep(0.5)
expect_true(app$get_js("$('#shiny-modal .gmsalert-error').is(':visible');", timeout = 50))
expect_true(app$get_js("$('#shiny-modal .choose-input').is(':visible');", timeout = 50))
app$set_inputs(cbSelectManuallyExp = TRUE)
app$set_inputs(selDataToExport = "a")
expect_download_size(app, "scenExportHandler", "scenExport_manual.xlsx")

app$run_js("$('.navbar-custom-menu a.dropdown-toggle').get(0).click()")
app$click(selector = ".navbar-custom-menu a[onclick*='btExportScen']")
Sys.sleep(1)
app$set_inputs(exportFileType = "csv")
Sys.sleep(0.5)
expect_true(app$get_js("$('#shiny-modal .gmsalert-error').is(':visible');", timeout = 50))
expect_true(app$get_js("$('#shiny-modal .choose-input').is(':visible');", timeout = 50))
app$set_inputs(cbSelectManuallyExp = TRUE)
app$set_inputs(selDataToExport = "a")
app$expect_download("scenExportHandler", name = "scenExport_manual.csv")

app$stop()
