app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("hcube_test")

context("UI tests - Hypercube mode - load/import/export data")

#load base scenario
Sys.sleep(3)
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(1)
app$setInputs(btImport = "click")
Sys.sleep(1)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
#check/set some widget configurations
app$setInputs(inputTabset = "inputTabset_1")
app$setInputs(inputTabset1 = "inputTabset1_1")
expect_true(app$waitFor("$('div[data-value=\"inputTabset1_1\"] #hcubeStep_3').is(':visible');", 50))
expect_true(app$waitFor("$('div[data-value=\"inputTabset1_1\"] .irs-slider.from i').is(':visible');", 50))
app$snapshot(items = list(input = c("slider_3", "hcubeStep_3")), screenshot = TRUE)
app$setInputs(slider_3 = c(1,3), hcubeStep_3 = 2)
# export maxstock csv, change values manually afterwards again for csv import check
app$findElements(".navbar-custom-menu a.dropdown-toggle")[[1]]$click()
app$findElement(".navbar-custom-menu a[onclick*='btExportScen']")$click()
Sys.sleep(1)
app$setInputs(exportFileType = "csv")
Sys.sleep(0.5)
app$setInputs(cbSelectManuallyExp = "click")
app$setInputs(selDataToExport = c("_scalars"))
expect_download_size(app, "scenExportHandler", "scalarExport.csv")
app$setInputs(slider_3 = c(10,15), hcubeStep_3 = 1)
app$setInputs(inputTabset1 = "inputTabset1_2")
expect_error(app$findElement("$('div[data-value=\"inputTabset1_2\"] .irs-slider.from i')")$click())
app$snapshot(items = list(input = "slider_4"), screenshot = TRUE)
app$setInputs(slider_4 = c(2))
app$setInputs(inputTabset1 = "inputTabset1_4")
expect_true(app$waitFor("$('div[data-value=\"inputTabset1_4\"] #hcubeMode_7').is(':visible');", 50))
expect_error(app$findElement("$('div[data-value=\"inputTabset1_4\"] #hcubeStep_7')")$click())
app$setInputs(hcubeMode_7 = TRUE)
Sys.sleep(0.5)
expect_true(app$waitFor("$('div[data-value=\"inputTabset1_4\"] #hcubeStep_7').is(':visible');", 50))
app$setInputs(hcubeMode_7 = FALSE)
app$setInputs(inputTabset = "inputTabset_3")
app$snapshot(items = list(input = c("dropdown_5")), screenshot = TRUE)
app$setInputs(dropdown_5 = c("CPLEX","CBC","SCIP"))

#import local file for maxstock (manual)
app$setInputs(btImport = "click")
app$setInputs(tb_importData = "tb_importData_local")
app$uploadFile(localInput = paste0("../data/", "pickstock_hcube_slider_values.csv"))
Sys.sleep(1)
app$setInputs(cbSelectManuallyLoc = "click")
app$setInputs(selInputDataLoc = c("maxstock"))
app$findElement("#btImportLocal")$click()
Sys.sleep(2)

#check some widget configurations
app$setInputs(inputTabset = "inputTabset_1")
app$setInputs(inputTabset1 = "inputTabset1_1")
app$snapshot(items = list(input = c("slider_3", "hcubeStep_3")), screenshot = TRUE)
app$setInputs(inputTabset1 = "inputTabset1_2")
app$snapshot(items = list(input = c("slider_4", "hcubeStep_4")), screenshot = TRUE)

#save new scenario, remove from sandbox, load again
app$setInputs(btSaveAs = "click")
app$setInputs(scenName = "newHcubeScen")
Sys.sleep(0.5)
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(1)
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(1)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(1)
app$setInputs(inputTabset = "inputTabset_1")
app$setInputs(inputTabset1 = "inputTabset1_1")
Sys.sleep(1)
app$snapshot(items = list(input = c("slider_3", "hcubeStep_3")), screenshot = TRUE)
app$setInputs(inputTabset1 = "inputTabset1_2")
app$snapshot(items = list(input = c("slider_4", "hcubeStep_4")), screenshot = TRUE)
app$setInputs(inputTabset = "inputTabset_3")
app$snapshot(items = list(input = c("dropdown_5")), screenshot = TRUE)

#export xlsx and csv
app$findElements(".navbar-custom-menu a.dropdown-toggle")[[1]]$click()
app$findElement(".navbar-custom-menu a[onclick*='btExportScen']")$click()
Sys.sleep(1)
app$setInputs(exportFileType = "xls")
Sys.sleep(0.5)
expect_download_size(app, "scenExportHandler", "xlsExport.xlsx")

app$findElements(".navbar-custom-menu a.dropdown-toggle")[[1]]$click()
app$findElement(".navbar-custom-menu a[onclick*='btExportScen']")$click()
Sys.sleep(1)
app$setInputs(exportFileType = "csv")
Sys.sleep(0.5)
expect_download_size(app, "scenExportHandler", "csvExport.zip")

# 1) solve manually and 2) submit
app$setInputs(inputTabset = "inputTabset_1")
app$setInputs(inputTabset1 = "inputTabset1_1")
app$setInputs(slider_3 = c(1,3), hcubeStep_3 = 1)
app$setInputs(inputTabset1 = "inputTabset1_2")
app$setInputs(slider_4 = c(75))
app$setInputs(inputTabset = "inputTabset_3")
app$snapshot(items = list(input = c("dropdown_5")), screenshot = TRUE)
app$setInputs(dropdown_5 = c("CPLEX"))

app$setInputs(btSolve = "click")
Sys.sleep(1)
app$findElement(".modal-footer i[onclick*='$(this).next().slideToggle();']")$click()
Sys.sleep(1)
app$setInputs(hcubeSolve_dl = "click")
Sys.sleep(0.5)
expect_download_size(app, "btHcubeAll_dl", "manaulSubmit.zip")
Sys.sleep(2)
app$setInputs(btSolve = "click")
Sys.sleep(2)
addSelectizeOption(app, "#newHcubeTags", "this")
addSelectizeOption(app, "#newHcubeTags", "is")
addSelectizeOption(app, "#newHcubeTags", "a")
addSelectizeOption(app, "#newHcubeTags", "test")
selectSelectizeOption(app, "#newHcubeTags", "this")
selectSelectizeOption(app, "#newHcubeTags", "is")
selectSelectizeOption(app, "#newHcubeTags", "a")
selectSelectizeOption(app, "#newHcubeTags", "test")
app$setInputs(btHcubeAll = "click")
Sys.sleep(7)
app$findElement("#sidebarItemExpanded a[data-value='importData']")$click()
app$setInputs(btManualImport = "click")
Sys.sleep(1)
app$uploadFile(hcubeImport = paste0("../data/", "4upload.zip"))
Sys.sleep(1)
addSelectizeOption(app, "#hcubeTags", "manual submission")
addSelectizeOption(app, "#hcubeTags", "test")
selectSelectizeOption(app, "#hcubeTags", "manual submission")
selectSelectizeOption(app, "#hcubeTags", "test")
app$setInputs(btUploadHcube = "click")
Sys.sleep(5)
app$findElement('#refreshActiveJobs')$click()
Sys.sleep(3)
expect_true(app$waitFor(paste0("$('#jImport_output td')[0].textContent==='", Sys.info()[["user"]], "'"), timeout = 50)) 
expect_true(app$waitFor("$('#jImport_output td')[2].innerText==='thisisatest'", timeout = 50))
addSelectizeOption(app, "#jImport_output select[id*='jTag_']", "addTag")
selectSelectizeOption(app, "#jImport_output select[id*='jTag_']", "addTag")
app$findElements("#jImport_output button[onclick*='importJob']")[[1]]$click()
Sys.sleep(3)

#check job history
app$findElement("#btShowHistory")$click()
Sys.sleep(1)
expect_true(app$waitFor("$('#shiny-modal tr').length===3", timeout = 50))
app$findElement("#shiny-modal .btn-default")$click()
Sys.sleep(1)

#submit unsolved only and discard job
app$findElement("#sidebarItemExpanded a[data-value='inputData']")$click()
app$setInputs(inputTabset = "inputTabset_1")
app$setInputs(inputTabset1 = "inputTabset1_1")
app$snapshot(items = list(input = c("slider_3", "hcubeStep_3")), screenshot = TRUE)
app$setInputs(slider_3 = c(1,10), hcubeStep_3 = 1)
app$setInputs(btSolve = "click")
Sys.sleep(1)
addSelectizeOption(app, "#newHcubeTags", "discard")
addSelectizeOption(app, "#newHcubeTags", "test")
selectSelectizeOption(app, "#newHcubeTags", "discard")
selectSelectizeOption(app, "#newHcubeTags", "test")
app$setInputs(btHcubeNew = "click")
Sys.sleep(7)
app$findElement("#sidebarItemExpanded a[data-value='importData']")$click()
app$findElement('#refreshActiveJobs')$click()
Sys.sleep(3)
app$findElements("#jImport_output button[onclick*='showJobProgress']")[[1]]$click()
Sys.sleep(1)
expect_true(app$waitFor("$('#shiny-modal .progress-bar.progress-bar-striped.active').is(':visible');", 50))
expect_error(app$findElement("#shiny-modal .btn-default")$click(), NA)
app$findElements("#jImport_output button[onclick*='discardJob']")[[1]]$click()
Sys.sleep(0.5)
app$findElement("#confirmModal .bt-gms-confirm")$click()
Sys.sleep(1)
expect_true(app$waitFor("$('#jImport_output td').length===0"))

#load scenarios
app$findElement("#sidebarItemExpanded a[data-value='loadResults']")$click()
Sys.sleep(0.5)
app$setInputs(btSendQuery = "click")
Sys.sleep(2)

app$stop()