app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("hcube_test")

context("UI tests - Hypercube mode - load/import/export data")

#load base scenario
Sys.sleep(3)
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(1)
app$setInputs(btImport = "click")
Sys.sleep(1)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
#check/set some widget configurations
app$setInputs(inputTabset = "inputTabset_1")
app$setInputs(inputTabset1 = "inputTabset1_1")
expect_true(app$waitFor("$('div[data-value=\"inputTabset1_1\"] #hcubeStep_3').is(':visible');", 50))
expect_true(app$waitFor("$('div[data-value=\"inputTabset1_1\"] .irs-slider.from i').is(':visible');", 50))
app$snapshot(items = list(input = c("slider_3", "hcubeStep_3")), screenshot = TRUE)
app$setInputs(slider_3 = c(1,3), hcubeStep_3 = 2)
# export maxstock csv, change values manually afterwards again for csv import check
app$findElements(".navbar-custom-menu a.dropdown-toggle")[[1]]$click()
app$findElement(".navbar-custom-menu a[onclick*='btExportScen']")$click()
Sys.sleep(1)
app$setInputs(exportFileType = "csv")
Sys.sleep(0.5)
app$setInputs(cbSelectManuallyExp = "click")
app$setInputs(selDataToExport = c("_scalars"))
expect_download_size(app, "scenExportHandler", "scalarExport.csv")
app$setInputs(slider_3 = c(10,15), hcubeStep_3 = 1)
app$setInputs(inputTabset1 = "inputTabset1_2")
expect_error(app$findElement("$('div[data-value=\"inputTabset1_2\"] .irs-slider.from i')")$click())
app$snapshot(items = list(input = "slider_4"), screenshot = TRUE)
app$setInputs(slider_4 = c(2))
app$setInputs(inputTabset1 = "inputTabset1_4")
expect_true(app$waitFor("$('div[data-value=\"inputTabset1_4\"] #hcubeMode_7').is(':visible');", 50))
expect_error(app$findElement("$('div[data-value=\"inputTabset1_4\"] #hcubeStep_7')")$click())
app$setInputs(hcubeMode_7 = TRUE)
Sys.sleep(0.5)
expect_true(app$waitFor("$('div[data-value=\"inputTabset1_4\"] #hcubeStep_7').is(':visible');", 50))
app$setInputs(hcubeMode_7 = FALSE)
app$setInputs(inputTabset = "inputTabset_3")
app$snapshot(items = list(input = c("dropdown_5")), screenshot = TRUE)
app$setInputs(dropdown_5 = c("CPLEX","CBC","SCIP"))

#import local file for maxstock (manual)
app$setInputs(btImport = "click")
app$setInputs(tb_importData = "tb_importData_local")
app$uploadFile(localInput = paste0("../data/", "pickstock_hcube_slider_values.csv"))
Sys.sleep(1)
app$setInputs(cbSelectManuallyLoc = "click")
app$setInputs(selInputDataLoc = c("maxstock"))
app$findElement("#btImportLocal")$click()
Sys.sleep(2)

#check some widget configurations
app$setInputs(inputTabset = "inputTabset_1")
app$setInputs(inputTabset1 = "inputTabset1_1")
app$snapshot(items = list(input = c("slider_3", "hcubeStep_3")), screenshot = TRUE)
app$setInputs(inputTabset1 = "inputTabset1_2")
app$snapshot(items = list(input = c("slider_4", "hcubeStep_4")), screenshot = TRUE)

#save new scenario, remove from sandbox, load again
app$setInputs(btSaveAs = "click")
app$setInputs(scenName = "newHcubeScen")
Sys.sleep(0.5)
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(1)
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(1)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(1)
app$setInputs(inputTabset = "inputTabset_1")
app$setInputs(inputTabset1 = "inputTabset1_1")
Sys.sleep(1)
app$snapshot(items = list(input = c("slider_3", "hcubeStep_3")), screenshot = TRUE)
app$setInputs(inputTabset1 = "inputTabset1_2")
app$snapshot(items = list(input = c("slider_4", "hcubeStep_4")), screenshot = TRUE)
app$setInputs(inputTabset = "inputTabset_3")
app$snapshot(items = list(input = c("dropdown_5")), screenshot = TRUE)

#export xlsx and csv
app$findElements(".navbar-custom-menu a.dropdown-toggle")[[1]]$click()
app$findElement(".navbar-custom-menu a[onclick*='btExportScen']")$click()
Sys.sleep(1)
app$setInputs(exportFileType = "xls")
Sys.sleep(0.5)
expect_download_size(app, "scenExportHandler", "xlsExport.xlsx")

app$findElements(".navbar-custom-menu a.dropdown-toggle")[[1]]$click()
app$findElement(".navbar-custom-menu a[onclick*='btExportScen']")$click()
Sys.sleep(1)
app$setInputs(exportFileType = "csv")
Sys.sleep(0.5)
expect_download_size(app, "scenExportHandler", "csvExport.zip")

# 1) solve manually and 2) submit
app$setInputs(inputTabset = "inputTabset_1")
app$setInputs(inputTabset1 = "inputTabset1_1")
app$setInputs(slider_3 = c(1,3), hcubeStep_3 = 1)
app$setInputs(inputTabset1 = "inputTabset1_2")
app$setInputs(slider_4 = c(75))
app$setInputs(inputTabset = "inputTabset_3")
app$snapshot(items = list(input = c("dropdown_5")), screenshot = TRUE)
app$setInputs(dropdown_5 = c("CPLEX"))

app$setInputs(btSolve = "click")
Sys.sleep(1)
app$findElement(".modal-footer i[onclick*='$(this).next().slideToggle();']")$click()
Sys.sleep(1)
app$snapshot(screenshot = TRUE)
app$setInputs(hcubeSolve_dl = "click")
Sys.sleep(0.5)
app$snapshot(screenshot = TRUE)
expect_download_size(app, "btHcubeAll_dl", "manaulSubmit.zip")
Sys.sleep(2)
app$snapshot(screenshot = TRUE)
app$setInputs(btSolve = "click")
Sys.sleep(2)
addSelectizeOption(app, "#newHcubeTags", "this")
addSelectizeOption(app, "#newHcubeTags", "is")
addSelectizeOption(app, "#newHcubeTags", "a")
addSelectizeOption(app, "#newHcubeTags", "test")
selectSelectizeOption(app, "#newHcubeTags", "this")
selectSelectizeOption(app, "#newHcubeTags", "is")
selectSelectizeOption(app, "#newHcubeTags", "a")
selectSelectizeOption(app, "#newHcubeTags", "test")
app$setInputs(btHcubeAll = "click")
Sys.sleep(7)
app$findElement("#sidebarItemExpanded a[data-value='importData']")$click()
# app$setInputs(btManualImport = "click")
# Sys.sleep(1)
# app$uploadFile(hcubeImport = paste0("../data/", "4upload.zip"))
# Sys.sleep(1)
# addSelectizeOption(app, "#hcubeTags", "manual submission")
# addSelectizeOption(app, "#hcubeTags", "test")
# selectSelectizeOption(app, "#hcubeTags", "manual submission")
# selectSelectizeOption(app, "#hcubeTags", "test")
# app$snapshot(screenshot = TRUE)
# app$setInputs(btUploadHcube = "click")
# Sys.sleep(5)
# app$snapshot(screenshot = TRUE)
app$findElement('#refreshActiveJobs')$click()
Sys.sleep(3)
app$snapshot(screenshot = TRUE)
expect_true(app$waitFor(paste0("$('#jImport_output td')[0].textContent==='", Sys.info()[["user"]], "'"), timeout = 50)) 
expect_true(app$waitFor("$('#jImport_output td')[2].innerText==='thisisatest'", timeout = 50))
addSelectizeOption(app, "#jImport_output select[id*='jTag_']", "addTag")
selectSelectizeOption(app, "#jImport_output select[id*='jTag_']", "addTag")
app$snapshot(screenshot = TRUE)
app$findElements("#jImport_output button[onclick*='importJob']")[[1]]$click()
Sys.sleep(3)
app$snapshot(screenshot = TRUE)

#check job history
app$findElement("#btShowHistory")$click()
Sys.sleep(1)
app$snapshot(screenshot = TRUE)
expect_true(app$waitFor("$('#shiny-modal tr').length===3", timeout = 50))
app$findElement("#shiny-modal .btn-default")$click()
Sys.sleep(1)

#submit unsolved only and discard job
app$findElement("#sidebarItemExpanded a[data-value='inputData']")$click()
app$setInputs(inputTabset = "inputTabset_1")
app$setInputs(inputTabset1 = "inputTabset1_1")
app$snapshot(items = list(input = c("slider_3", "hcubeStep_3")), screenshot = TRUE)
app$setInputs(slider_3 = c(1,10), hcubeStep_3 = 1)
app$snapshot(screenshot = TRUE)
app$setInputs(btSolve = "click")
Sys.sleep(1)
addSelectizeOption(app, "#newHcubeTags", "discard")
addSelectizeOption(app, "#newHcubeTags", "test")
selectSelectizeOption(app, "#newHcubeTags", "discard")
selectSelectizeOption(app, "#newHcubeTags", "test")
app$setInputs(btHcubeNew = "click")
Sys.sleep(7)
app$findElement("#sidebarItemExpanded a[data-value='importData']")$click()
app$findElement('#refreshActiveJobs')$click()
Sys.sleep(3)
app$snapshot(screenshot = TRUE)
app$findElements("#jImport_output button[onclick*='showJobProgress']")[[1]]$click()
Sys.sleep(1)
app$snapshot(screenshot = TRUE)
expect_true(app$waitFor("$('#shiny-modal .progress-bar.progress-bar-striped.active').is(':visible');", 50))
expect_error(app$findElement("#shiny-modal .btn-default")$click(), NA)
app$findElements("#jImport_output button[onclick*='discardJob']")[[1]]$click()
Sys.sleep(0.5)
app$snapshot(screenshot = TRUE)
app$findElement("#confirmModal .bt-gms-confirm")$click()
Sys.sleep(1)
expect_true(app$waitFor("$('#jImport_output td').length===0"))
app$snapshot(screenshot = TRUE)

#load scenarios
app$findElement("#sidebarItemExpanded a[data-value='loadResults']")$click()
Sys.sleep(0.5)
app$setInputs(btSendQuery = "click")
Sys.sleep(2)
app$snapshot(screenshot = TRUE)




# app$setInputs(selLoadScen = paste0("1_", Sys.info()[["user"]]))
# expect_identical(startsWith(app$getValue("selLoadScen"), "1_"), TRUE)
# app$setInputs(btLoadScenConfirm = "click")
# Sys.sleep(1)
# #try to solve and to submit (not logged in)
# app$findElement(".btSolve .dropdown-toggle")$click()
# app$findElement(".sidebar-menu a[onclick*='Solve model']")$click()
# Sys.sleep(0.5)
# expect_error(app$findElement("#shiny-modal .btn-default")$click(), NA)
# Sys.sleep(1)
# app$findElement(".btSolve .dropdown-toggle")$click()
# app$findElement(".sidebar-menu a[onclick*='Submit job']")$click()
# Sys.sleep(0.5)
# expect_error(app$findElement("#shiny-modal .btn-default")$click(), NA)
# 
# #login with wrong credentials (test each field)
# context("UI tests - asynchronous solve - login with wrong credentials")
# app$findElement("#btRemoteExecLogin")$click()
# Sys.sleep(1)
# app$setInputs(remoteCredUrl = paste0(Sys.getenv("ENGINE_URL"), "s"))
# app$setInputs(remoteCredUser = Sys.getenv("ENGINE_USER"))
# app$setInputs(remoteCredPass = Sys.getenv("ENGINE_PASSWORD"))
# app$setInputs(remoteCredNs = Sys.getenv("ENGINE_NS"))
# app$setInputs(remoteCredReg = FALSE)
# app$setInputs(remoteCredRemember = TRUE)
# Sys.sleep(0.5)
# app$findElement("#shiny-modal .bt-gms-confirm")$click()
# Sys.sleep(2)
# expect_true(app$waitFor("$('#remoteLoginHostNotFound').is(':visible');", timeout = 50))
# Sys.sleep(5)
# app$setInputs(remoteCredUrl = Sys.getenv("ENGINE_URL"))
# app$setInputs(remoteCredUser = paste0(Sys.getenv("ENGINE_USER"), "s"))
# app$findElement("#shiny-modal .bt-gms-confirm")$click()
# Sys.sleep(2)
# expect_true(app$waitFor("$('#remoteLoginInvalidCred').is(':visible');", timeout = 50))
# Sys.sleep(5)
# app$setInputs(remoteCredUser = Sys.getenv("ENGINE_USER"))
# app$setInputs(remoteCredPass = paste0(Sys.getenv("ENGINE_PASSWORD"), "s"))
# app$findElement("#shiny-modal .bt-gms-confirm")$click()
# Sys.sleep(2)
# expect_true(app$waitFor("$('#remoteLoginInvalidCred').is(':visible');", timeout = 50))
# Sys.sleep(5)
# app$setInputs(remoteCredPass = Sys.getenv("ENGINE_PASSWORD"))
# app$setInputs(remoteCredNs = paste0(Sys.getenv("ENGINE_NS"), "s"))
# app$findElement("#shiny-modal .bt-gms-confirm")$click()
# Sys.sleep(2)
# expect_true(app$waitFor("$('#remoteLoginNsNotFound').is(':visible');", timeout = 50))
# Sys.sleep(5)
# #check that model is registered (it's not) and try to solve
# app$setInputs(remoteCredNs = Sys.getenv("ENGINE_NS"))
# app$setInputs(remoteCredReg = TRUE)
# Sys.sleep(1)
# app$findElement("#shiny-modal .bt-gms-confirm")$click()
# Sys.sleep(1)
# app$findElement(".btSolve .dropdown-toggle")$click()
# app$findElement(".sidebar-menu a[onclick*='Solve model']")$click()
# Sys.sleep(8)
# app$snapshot(items = list(output = c("modelStatus")), screenshot = FALSE)
# # expect_identical(app$waitFor("if ($('#modelStatus')[0].textContent.match('^Run did not terminate successfully: Host could not be reached').length) true", timeout = 50), TRUE)
# 
# #correctly login and remember credentials
# context("UI tests - asynchronous solve - login and solve both synchronous and asynchronous")
# app$findElement("#remoteExecLogoutDiv")$click()
# Sys.sleep(1)
# app$findElement("#confirmModal .bt-gms-confirm")$click()
# Sys.sleep(1)
# app$findElement("#btRemoteExecLogin")$click()
# Sys.sleep(1)
# app$setInputs(remoteCredUrl = Sys.getenv("ENGINE_URL"))
# app$setInputs(remoteCredUser = Sys.getenv("ENGINE_USER"))
# app$setInputs(remoteCredPass = Sys.getenv("ENGINE_PASSWORD"))
# app$setInputs(remoteCredNs = Sys.getenv("ENGINE_NS"))
# app$setInputs(remoteCredReg = FALSE)
# app$setInputs(remoteCredRemember = TRUE)
# Sys.sleep(1)
# app$findElement("#shiny-modal .bt-gms-confirm")$click()
# Sys.sleep(1)
# expect_false(app$waitFor("$('#shiny-modal .btn-default').is(':visible');", timeout = 50))
# 
# #solve 3 jobs synchronous, interrupt first one, stop app before last one finishes
# app$findElement("#sidebarItemExpanded a[data-value='inputData']")$click()
# app$findElement(".btSolve .dropdown-toggle")$click()
# app$findElement(".sidebar-menu a[onclick*='Solve model']")$click()
# Sys.sleep(3)
# app$findElement("#btInterrupt")$click()
# Sys.sleep(8)
# app$findElement("#sidebarItemExpanded a[data-value='gamsinter']")$click()
# app$findElement("#logFileTabsset a[data-value='mirolog']")$click()
# expect_identical(app$waitFor("$('#miroLogFile')[0].textContent.length == 0", timeout = 50), TRUE)
# app$findElement("#sidebarItemExpanded a[data-value='inputData']")$click()
# app$findElement(".btSolve .dropdown-toggle")$click()
# app$findElement(".sidebar-menu a[onclick*='Solve model']")$click()
# Sys.sleep(40)
# expect_error(app$findElement("#outputTableView")$click(), NA)
# app$findElement("#sidebarItemExpanded a[data-value='inputData']")$click()
# app$findElement(".btSolve .dropdown-toggle")$click()
# app$findElement(".sidebar-menu a[onclick*='Solve model']")$click()
# Sys.sleep(3)
# app$stop()
# Sys.sleep(22)
# app <- ShinyDriver$new("../../", loadTimeout = 20000)
# Sys.sleep(5)
# expect_error(app$findElement("#shiny-modal button[onclick*='showJobsDialog']")$click(), NA)
# Sys.sleep(1)
# expect_error(app$findElements("#jImport_output button[onclick*='discardJob']")[[1]]$click(), NA)
# Sys.sleep(1)
# app$findElement("#confirmModal .bt-gms-confirm")$click()
# Sys.sleep(3)
# 
# #solve asynchronous 3 jobs, interrupt last one
# app$findElement("a[data-value='inputData']")$click()
# app$findElement(".btSolve .dropdown-toggle")$click()
# app$findElement(".sidebar-menu a[onclick*='Submit job']")$click()
# Sys.sleep(1)
# app$setInputs(jobSubmissionName = "test1")
# app$findElement("#btSubmitAsyncJob")$click()
# Sys.sleep(5)
# app$findElement(".btSolve .dropdown-toggle")$click()
# app$findElement(".sidebar-menu a[onclick*='Submit job']")$click()
# Sys.sleep(1)
# app$setInputs(jobSubmissionName = "test2")
# app$findElement("#btSubmitAsyncJob")$click()
# Sys.sleep(5)
# app$findElement(".btSolve .dropdown-toggle")$click()
# app$findElement(".sidebar-menu a[onclick*='Submit job']")$click()
# Sys.sleep(1)
# app$setInputs(jobSubmissionName = "test3")
# app$findElement("#btSubmitAsyncJob")$click()
# Sys.sleep(5)
# app$findElement(".btSolve .dropdown-toggle")$click()
# app$findElement(".sidebar-menu a[onclick*='Submit job']")$click()
# Sys.sleep(1)
# app$setInputs(jobSubmissionName = "test4")
# app$findElement("#btSubmitAsyncJob")$click()
# Sys.sleep(5)
# 
# #joblist section
# context("UI tests - asynchronous solve - joblist section")
# app$findElement("#sidebarItemExpanded a[data-value='gamsinter']")$click()
# app$findElement('#shiny-tab-gamsinter a[data-value="joblist"]')$click()
# app$findElement('#refreshActiveJobs')$click()
# Sys.sleep(3)
# expect_true(app$waitFor(paste0("$('#jImport_output td')[0].textContent==='", Sys.info()[["user"]], "'"), timeout = 50)) 
# expect_true(app$waitFor("$('#jImport_output td')[2].textContent==='test4'", timeout = 50)) 
# expect_true(app$waitFor("$('#jImport_output td')[7].textContent==='test3'", timeout = 50)) 
# expect_true(app$waitFor("$('#jImport_output td')[4].childElementCount===1", timeout = 50)) 
# 
# #discard test4
# expect_error(app$findElements("#jImport_output button[onclick*='discardJob']")[[1]]$click(), NA)
# Sys.sleep(1)
# app$findElement("#confirmModal .bt-gms-confirm")$click()
# Sys.sleep(3)
# expect_true(app$waitFor("$('#jImport_output td')[2].textContent==='test3'", timeout = 50)) 
# 
# #restart app
# app$stop()
# Sys.sleep(20)
# app <- ShinyDriver$new("../../", loadTimeout = 20000)
# Sys.sleep(5)
# expect_error(app$findElement("#shiny-modal button[onclick*='showJobsDialog']")$click(), NA)
# Sys.sleep(1)
# 
# #expect to be logged in. log out and test whether user can import/delete scenario or see log
# expect_error(app$findElement("#remoteExecLogoutDiv")$click(), NA)
# Sys.sleep(1)
# app$findElement("#confirmModal .bt-gms-confirm")$click()
# Sys.sleep(1)
# app$findElements("#jImport_output button[onclick*='downloadJobData']")[[1]]$click()
# Sys.sleep(0.5)
# expect_true(app$waitFor("$('#fetchJobsError').is(':visible');", timeout = 50))
# Sys.sleep(1)
# 
# #try to download a second time due to an bug that occurred here before
# app$findElements("#jImport_output td button[onclick*='downloadJobData']")[[1]]$click()
# Sys.sleep(0.5)
# expect_true(app$waitFor("$('#fetchJobsError').is(':visible');", timeout = 50))
# Sys.sleep(1)
# app$findElements("#jImport_output button[onclick*='showJobLog']")[[1]]$click()
# Sys.sleep(0.5)
# expect_true(app$waitFor("$('#asyncMiroLogContainer')[0].textContent.match('^An unexpected error occurred.').length===1", timeout = 50))
# app$findElement("#shiny-modal .btn-default")$click()
# Sys.sleep(0.5)
# app$findElements("#jImport_output button[onclick*='discardJob']")[[1]]$click()
# Sys.sleep(0.5)
# app$findElement("#confirmModal .bt-gms-confirm")$click()
# Sys.sleep(0.5)
# expect_true(app$waitFor("$('#fetchJobsError').is(':visible');", timeout = 50))
# 
# #login and inspect get results
# app$findElement("#btRemoteExecLogin")$click()
# Sys.sleep(1)
# app$setInputs(remoteCredUrl = Sys.getenv("ENGINE_URL"))
# app$setInputs(remoteCredUser = Sys.getenv("ENGINE_USER"))
# app$setInputs(remoteCredPass = Sys.getenv("ENGINE_PASSWORD"))
# app$setInputs(remoteCredNs = Sys.getenv("ENGINE_NS"))
# app$setInputs(remoteCredReg = FALSE)
# app$setInputs(remoteCredRemember = TRUE)
# Sys.sleep(1)
# app$findElement("#shiny-modal .bt-gms-confirm")$click()
# Sys.sleep(1)
# 
# #download job test3 and test2 directly one after the other. test3 will be imported to sandbox test2 can be imported afterwards
# app$findElements("#jImport_output button[onclick*='downloadJobData']")[[1]]$click()
# Sys.sleep(8)
# expect_error(app$findElement("#outputTableView")$click(), NA)
# app$findElement("#sidebarItemExpanded a[data-value='gamsinter']")$click()
# app$findElement('#shiny-tab-gamsinter a[data-value="joblist"]')$click()
# app$findElement('#refreshActiveJobs')$click()
# Sys.sleep(3)
# app$findElements("#jImport_output button[onclick*='downloadJobData']")[[1]]$click()
# Sys.sleep(3)
# app$findElement("#shiny-modal button[data-dismiss='modal']")$click()
# Sys.sleep(1)
# app$findElements("#jImport_output button[onclick*='importJob']")[[1]]$click()
# Sys.sleep(1)
# expect_error(app$findElement("#shiny-modal .bt-gms-confirm")$click(), NA)
# Sys.sleep(2)
# 
# #show test1 log 
# expect_error(app$findElement("#outputTableView")$click(), NA)
# app$findElement("#sidebarItemExpanded a[data-value='gamsinter']")$click()
# app$findElement('#shiny-tab-gamsinter a[data-value="joblist"]')$click()
# app$findElement('#refreshActiveJobs')$click()
# Sys.sleep(3)
# app$findElements("#jImport_output button[onclick*='showJobLog']")[[1]]$click()
# Sys.sleep(1)
# #no error message in log
# expect_true(app$waitFor("/^An unexpected error occurred/.test($('#asyncMiroLogContainer')[0].textContent)===false", timeout = 50))
# app$findElement("#shiny-modal .btn-default")$click()
# Sys.sleep(0.5)
# 
# #discard test1 job
# app$findElements("#jImport_output button[onclick*='discardJob']")[[1]]$click()
# Sys.sleep(0.5)
# app$findElement("#confirmModal .bt-gms-confirm")$click()
# Sys.sleep(1)
# expect_true(app$waitFor("$('#jImport_output td').length===0"))
# 
# #check job history
# app$findElement("#btShowHistory")$click()
# Sys.sleep(1)
# expect_true(app$waitFor("$('#shiny-modal tr').length===8", timeout = 50))
# app$findElement("#shiny-modal .btn-default")$click()
# Sys.sleep(1)

app$stop()