app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("hcube_engine_test")

context("UI tests - Hypercube mode with Engine")

#load base scenario
Sys.sleep(3)
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(1)
app$setInputs(btImport = "click")
Sys.sleep(1)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
#check/set some widget configurations
app$setInputs(inputTabset = "inputTabset_1")
app$setInputs(inputTabset1 = "inputTabset1_1")
app$setInputs(slider_3 = c(1,12), hcubeStep_3 = 1)
app$snapshot(items = list(input = c("slider_3", "hcubeStep_3")), screenshot = TRUE)
app$setInputs(inputTabset1 = "inputTabset1_2")
app$setInputs(slider_4 = c(75))
app$setInputs(inputTabset1 = "inputTabset1_4")
app$setInputs(hcubeMode_7 = FALSE)
app$setInputs(inputTabset = "inputTabset_3")
app$setInputs(dropdown_5 = c("CPLEX"))

# 1) submit
app$setInputs(btSolve = "click")
Sys.sleep(2)
addSelectizeOption(app, "#newHcubeTags", "a")
addSelectizeOption(app, "#newHcubeTags", "b")
addSelectizeOption(app, "#newHcubeTags", "c")
addSelectizeOption(app, "#newHcubeTags", "d")
selectSelectizeOption(app, "#newHcubeTags", "a")
selectSelectizeOption(app, "#newHcubeTags", "b")
selectSelectizeOption(app, "#newHcubeTags", "c")
selectSelectizeOption(app, "#newHcubeTags", "d")
app$setInputs(btHcubeAll = "click")
Sys.sleep(7)
app$findElement("#sidebarItemExpanded a[data-value='importData']")$click()
app$findElement('#refreshActiveJobs')$click()
Sys.sleep(1)
expect_true(app$waitFor(paste0("$('#jImport_output td')[0].textContent==='", Sys.info()[["user"]], "'"), timeout = 50)) 
expect_true(app$waitFor("$('#jImport_output td')[2].innerText==='abcd'", timeout = 50))
expect_error(app$findElements("#jImport_output button[onclick*='showJobProgress']")[[1]]$click(), NA)
Sys.sleep(1)
expect_true(app$waitFor("$('#shiny-modal .progress-bar.progress-bar-striped.active').is(':visible');", 50))
expect_error(app$findElement("#shiny-modal .btn-default")$click(), NA)
Sys.sleep(15)
app$findElement('#refreshActiveJobs')$click()
Sys.sleep(1)
expect_error(app$findElements("#jImport_output button[onclick*='downloadJob']")[[1]]$click(), NA)
Sys.sleep(10)
app$findElement('#refreshActiveJobs')$click()
Sys.sleep(1)
expect_true(app$waitFor("$('#shiny-modal').is(':visible');", 50))
expect_error(app$findElement("#shiny-modal #btHcubeImportNew")$click(), NA)
Sys.sleep(7)
expect_false(identical(app$waitFor("$('#jImport_output td')[2].innerText==='abcd'", timeout = 50), TRUE))

app$stop()