app <- AppDriver$new("../../",
  name = "input_table_pivot_cols_test", variant = NULL,
  load_timeout = as.integer(Sys.getenv("MIRO_TEST_LOAD_TIMEOUT", "20000")),
  timeout = as.integer(Sys.getenv("MIRO_TEST_TIMEOUT", "4000"))
)
Sys.sleep(2)
app$set_inputs(inputTabset = "inputTabset_3")
app$set_inputs(btImport = "click")
Sys.sleep(0.5)
app$set_inputs(tb_importData = "tb_importData_local")
app$upload_file(localInput = "../data/transport.xlsx")
Sys.sleep(0.5)
app$set_inputs(btImportLocal = "click")
Sys.sleep(1L)
app$run_js("HTMLWidgets.getInstance(document.getElementById('in_3')).hot.setDataAtCell(0,1,'Inf');")
Sys.sleep(0.5)
app$run_js("$('.navbar-custom-menu a.dropdown-toggle')[0].get(1).click();")
app$click(selector = ".navbar-custom-menu a[onclick*='btExportScen']")
Sys.sleep(1)
app$set_inputs(exportFileType = "csv", cbSelectManuallyExp = "true")
Sys.sleep(0.5)
app$set_inputs(selDataToExport = c("d"))
Sys.sleep(1)
data <- readr::read_csv(get_file_content(app, "scenExportHandler"))
expect_identical(dplyr::filter(data, i == "Seattle", j == "New-york")[["value"]], Inf)
app$stop()
