app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("interrupt_model_test")

Sys.sleep(2)
app$setInputs(inputTabset = "inputTabset_1")
Sys.sleep(0.5)
app$setInputs(slider_2 = 15)
app$setInputs(slider_3 = 200)
app$setInputs(btSolve = "click")
Sys.sleep(0.5)
expect_true(app$waitFor("$('#logStatusContainer').is(':visible')", timeout = 5000L))
Sys.sleep(0.5)
app$setInputs(btInterrupt = "click")
Sys.sleep(0.5)
expect_true(app$waitFor("$('#logStatusContainer').is(':hidden')", timeout = 5000L))
Sys.sleep(0.5)
app$snapshot(
  items = list(output = "outputDataTitle"),
  screenshot = TRUE
)
expect_error(app$findElement("#outputTableView")$click(), NA)
app$findElement("#sidebarItemExpanded a[data-value='gamsinter']")$click()
expect_true(app$waitFor("$('#logStatusContainer').is(':visible')", timeout = 5000L))
expect_true(app$waitFor("$('#logStatusContainer').text().includes('Problem aborted')",
  timeout = 5000L
))
expect_true(app$waitFor("$('#btInterrupt .fa-skull').is(':visible')", timeout = 50L))
# when solving again, hardkill button should be reset
app$findElement("#sidebarItemExpanded a[data-value='inputData']")$click()
Sys.sleep(0.5)
app$setInputs(inputTabset = "inputTabset_3")
app$setInputs(dropdown_4 = "CBC")
app$setInputs(btSolve = "click")
Sys.sleep(0.5)
expect_true(app$waitFor("$('#logStatusContainer').is(':visible')", timeout = 5000L))
expect_true(app$waitFor("$('#btInterrupt .fa-skull').is(':visible')===false", timeout = 50L))
app$setInputs(btInterrupt = "click")
Sys.sleep(0.5)
expect_true(app$waitFor("$('#btInterrupt .fa-skull').is(':visible')", timeout = 50L))
app$waitFor("$('#btInterrupt').is(':enabled')", timeout = 2000L)
app$setInputs(btInterrupt = "click")
Sys.sleep(1)
expect_true(app$waitFor("$('#modelStatus').text().includes('interrupted')", timeout = 5000L))
app$stop()
