app <- AppDriver$new("../../", name = paste0("load_from_db_test_", Sys.getenv("GMSMODELNAME")), variant = NULL, load_timeout = 20000)

app$set_inputs(btImport = "click")
Sys.sleep(0.5)
expect_error(app$wait_for_js("$('#selLoadScen+.selectize-control').is(':visible');", timeout = 3000L), NA)
expect_identical(startsWith(app$get_value(input = "selLoadScen"), "1_"), TRUE)
app$set_inputs(btLoadScenConfirm = "click")
Sys.sleep(1)
app$click(selector = "#btRemove1")
Sys.sleep(0.5)
app$click(selector = ".modal-footer .bt-gms-confirm")
Sys.sleep(0.5)
app$set_inputs(btImport = "click")
Sys.sleep(0.5)
app$set_inputs(btLoadScenConfirm = "click")
Sys.sleep(1)
app$set_inputs(btSaveAs = "click")
Sys.sleep(0.5)
app$set_inputs(btNewName = "click")
app$set_inputs(scenName = "test123")
Sys.sleep(0.5)
app$click(selector = "#dialogSaveInit .bt-gms-confirm")
Sys.sleep(1)
app$click(selector = "#btRemove1")
Sys.sleep(0.5)
app$click(selector = ".modal-footer .bt-gms-confirm")
Sys.sleep(0.5)
app$set_inputs(btImport = "click")
Sys.sleep(0.5)
expect_error(app$wait_for_js("$('#selLoadScen+.selectize-control').is(':visible');", timeout = 3000L), NA)
expect_identical(startsWith(app$get_value(input = "selLoadScen"), "2_"), TRUE)
app$expect_values(input = "slider_2")
app$stop()
