app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit(paste0("load_from_db_test_", Sys.getenv("GMSMODELNAME")))

app$setInputs(btImport = "click")
Sys.sleep(0.5)
expect_identical(startsWith(app$getValue("selLoadScen"), "1_"), TRUE)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(1)
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(0.5)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(1)
app$setInputs(btSaveAs = "click")
Sys.sleep(0.5)
app$setInputs(btNewName = "click")
app$setInputs(scenName = "test123")
Sys.sleep(0.5)
app$findElement("#dialogSaveInit .bt-gms-confirm")$click()
Sys.sleep(1)
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(0.5)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
expect_identical(startsWith(app$getValue("selLoadScen"), "2_"), TRUE)
app$snapshot(items = list(input = "slider_2"), screenshot = TRUE)
app$stop()
