app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("mirolog_test")
app$snapshot(
  items = list(output = "inputDataTitle"),
  screenshot = TRUE
)
app$setInputs(btImport = "click")
Sys.sleep(1)
app$setInputs(tb_importData = "tb_importData_local", wait_ = FALSE, values_ = FALSE)
app$uploadFile(localInput = "../data/pickstock_negative_price.gdx")
app$setInputs(btImportLocal = "click")
app$setInputs(btOverwriteInput = "click")
Sys.sleep(1)
app$setInputs(btSolve = "click")
Sys.sleep(3L)
expect_true(app$waitFor("$('#valErr_price').is(':visible');", timeout = 50L))
expect_true(app$waitFor("$('#valErr_price').text().includes('negative')", timeout = 50L))
expect_true(app$waitFor("$('#valErr_price li').click();true;", timeout = 50L))
expect_true(app$waitFor("$('#modelStatus').is(':visible')===false;", timeout = 50L))
expect_true(app$waitFor("$('#valErr_price li').dblclick();true;", timeout = 50L))
Sys.sleep(1)
expect_true(app$waitFor("$('#modelStatus').is(':visible')&&$('#miroLogContainer').is(':visible')&&$('#miroLogContainer').text().includes('Symbol IBM  has negative price at the date: 2016-01-04')&&$('#miroLogContainer').text().includes('Symbol GS   has negative price at the date: 2016-01-12');", timeout = 50L))
app$findElement('a[data-value="inputData"]')$click()
Sys.sleep(0.5)
app$findElement("#btRemove1")$click()
Sys.sleep(1)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(1)
expect_true(app$waitFor("$('#valErr_price').is(':visible')===false;", timeout = 50L))
app$findElement('a[data-value="gamsinter"]')$click()
Sys.sleep(0.5)
expect_true(app$waitFor("$('#modelStatus').text()===''&&$('#miroLogContainer').text()==='';", timeout = 50L))
app$setInputs(logFileTabsset = "log")
Sys.sleep(0.5)
expect_true(app$waitFor("$('#logStatusContainer').text()==='';", timeout = 50L))
app$setInputs(logFileTabsset = "listfile")
Sys.sleep(0.5)
expect_true(app$waitFor("$('#listFileContainer').text()==='';", timeout = 50L))
app$stop()
