app <- AppDriver$new("../../", name = "mirolog_test", variant = NULL, load_timeout = 20000)
app$set_inputs(btImport = "click")
Sys.sleep(1)
app$set_inputs(tb_importData = "tb_importData_local", wait_ = FALSE)
app$upload_file(localInput = "../data/pickstock_negative_price.gdx")
app$set_inputs(btImportLocal = "click")
app$set_inputs(btReplaceInputData = "click")
Sys.sleep(1)
app$set_inputs(btSolve = "click")
Sys.sleep(4L)
expect_true(app$get_js("$('#valErr_price').is(':visible');", timeout = 50L))
expect_true(app$get_js("$('#valErr_price').text().includes('negative');", timeout = 50L))
expect_error(app$get_js("$('#valErr_price li').click();", timeout = 50L), NA)
expect_true(app$get_js("$('#modelStatus').is(':visible')===false;", timeout = 50L))
expect_error(app$get_js("$('#valErr_price li').dblclick();", timeout = 50L), NA)
Sys.sleep(1)
expect_true(app$get_js("$('#modelStatus').is(':visible')&&$('#miroLogContainer').is(':visible')&&$('#miroLogContainer').text().includes('Symbol IBM  has negative price at the date: 2016-01-04')&&$('#miroLogContainer').text().includes('Symbol GS   has negative price at the date: 2016-01-12');", timeout = 50L))
app$click(selector = 'a[data-value="inputData"]')
Sys.sleep(0.5)
app$click(selector = "#btRemove1")
Sys.sleep(1)
app$click(selector = ".modal-footer .bt-gms-confirm")
Sys.sleep(2L)
expect_true(app$get_js("$('#valErr_price').is(':visible')===false;"))
app$click(selector = 'a[data-value="gamsinter"]')
Sys.sleep(0.5)
expect_true(app$get_js("$('#modelStatus').text()===''&&$('#miroLogContainer').text()==='';", timeout = 50L))
app$set_inputs(logFileTabsset = "log")
Sys.sleep(0.5)
expect_true(app$get_js("$('#logStatusContainer').text()==='';", timeout = 50L))
app$set_inputs(logFileTabsset = "listfile")
Sys.sleep(0.5)
expect_true(app$get_js("$('#listFileContainer').text()==='';", timeout = 50L))
app$stop()
