app <- AppDriver$new("../../", name = "mirolog_test", variant = NULL, load_timeout = 20000)
app$set_inputs(btImport = "click")
Sys.sleep(1)
app$set_inputs(tb_importData = "tb_importData_local", wait_ = FALSE)
app$upload_file(localInput = "../data/pickstock_negative_price.gdx")
app$set_inputs(btImportLocal = "click")
app$set_inputs(btReplaceInputData = "click")
Sys.sleep(1)
app$set_inputs(btSolve = "click")
expect_error(app$wait_for_js("$('#valErr_price').is(':visible');", timeout = 10000L), NA)
expect_error(app$wait_for_js("$('#valErr_price').text().includes('negative');", timeout = 2000L), NA)
app$run_js("$('#valErr_price li').click();")
expect_true(app$get_js("$('#modelStatus').is(':visible')===false;", timeout = 50L))
app$run_js("$('#valErr_price li').dblclick();")
expect_error(app$wait_for_js("$('#modelStatus').is(':visible')&&$('#miroLogContainer').is(':visible')&&$('#miroLogContainer').text().includes('Symbol IBM  has negative price at the date: 2016-01-04')&&$('#miroLogContainer').text().includes('Symbol GS   has negative price at the date: 2016-01-12');", timeout = 5000L), NA)
app$click(selector = 'a[data-value="inputData"]')
Sys.sleep(0.5)
app$click(selector = "#btRemove1")
Sys.sleep(1)
app$click(selector = ".modal-footer .bt-gms-confirm")
Sys.sleep(1L)
expect_error(app$wait_for_js("$('#valErr_price').is(':visible')===false;", timeout = 5000L), NA)
app$click(selector = 'a[data-value="gamsinter"]')
Sys.sleep(0.5)
expect_error(app$wait_for_js("$('#modelStatus').text()===''&&$('#miroLogContainer').text()==='';", timeout = 5000L), NA)
app$set_inputs(logFileTabsset = "log")
Sys.sleep(0.5)
expect_error(app$wait_for_js("$('#logStatusContainer').text()==='';", timeout = 5000L), NA)
app$set_inputs(logFileTabsset = "listfile")
Sys.sleep(0.5)
expect_error(app$wait_for_js("$('#listFileContainer').text()==='';", timeout = 5000L), NA)
app$stop()
