app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("miroscenio_test")

app$setInputs(inputTabset = "inputTabset_7")
Sys.sleep(1)
app$snapshot(
  items = list(input = paste0("slider_", c("7", "8"))),
  screenshot = TRUE
)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
scenariosInDb <- getSelectizeAliases(app, "#selLoadScen")
expect_true(any(startsWith(scenariosInDb, "I am a scenario (")))
app$setInputs(tb_importData = "tb_importData_local")
app$uploadFile(localInput = paste0("../data/transport.miroscen"))
app$setInputs(btImportLocal = "click")
app$setInputs(inputTabset = "inputTabset_7")
Sys.sleep(1)
app$snapshot(
  items = list(input = paste0("slider_", c("7", "8"))),
  screenshot = TRUE
)
Sys.sleep(0.5)
app$setInputs(btEditMeta = "click")
Sys.sleep(1)
app$findElement('#editMetaUI a[data-value="Views"]')$click()
Sys.sleep(1)
expect_identical(length(app$findElements("#currentViewsTable tbody tr")), 1L)
app$findElement('#editMetaUI a[data-value="Attachments"]')$click()
Sys.sleep(1)
attachmentList <- app$findElements(".attachment-line")
expect_identical(length(attachmentList), 2L)
expect_identical(attachmentList[[1]]$findElement(".checkbox input")$getAttribute("checked"), "true")
expect_identical(attachmentList[[2]]$findElement(".checkbox input")$getAttribute("checked"), NULL)
app$findElement('#editMetaUI a[data-value="General options"]')$click()
Sys.sleep(1)
expect_identical(app$getValue("editMetaName"), "Test Scenario")
expect_identical(app$getValue("editMetaTags"), list("asd", "def"))
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)
app$findElements(".navbar-custom-menu a.dropdown-toggle")[[1]]$click()
app$findElement(".navbar-custom-menu a[onclick*='btExportScen']")$click()
Sys.sleep(1)
app$setInputs(exportFileType = "miroscen")
Sys.sleep(0.5)
expect_true(app$waitFor("$('#shiny-modal .gmsalert-error').is(':hidden');", 50))
expect_true(app$waitFor("$('#shiny-modal .choose-input').is(':hidden');", 50))
expect_files_in_zip(app, "scenExportHandler", c(
  "data.gdx", "metadata.json", "views.json",
  "attachments/", "attachments/scalars.csv",
  "attachments/bad1.miroscen"
))
app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(tb_importData = "tb_importData_local")
app$uploadFile(localInput = paste0("../data/transport.miroscen"))
app$setInputs(btImportLocal = "click")
expect_true(app$waitFor("$('#importDataClearSandbox').is(':visible');", 50))
expect_true(app$waitFor("$('#importDataOverwrite').is(':hidden');", 50))
expect_true(app$waitFor("$('#importDataOverwrite').is(':hidden');", 50))
expect_true(app$waitFor("$('#btReplaceInputData').is(':hidden');", 50))
expect_true(app$waitFor("$('#btMergeInputData').is(':hidden');", 50))
expect_true(app$waitFor("$('#btOverwriteScenLocal').is(':visible');", 50))
app$stop()
