app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("multiple_symbol_renderer_input")
app$setInputs(btImport = "click")
app$setInputs(tb_importData = "tb_importData_local")
app$uploadFile(localInput = "../data/transport.gdx")
app$setInputs(btImportLocal = "click")
Sys.sleep(2)
expect_true(app$waitFor("$('#btRefreshGraphIn').is(':hidden')", timeout = 50))
app$setInputs(btGraphIn = "click")
Sys.sleep(0.5)
expect_true(app$waitFor("$('#btRefreshGraphIn').is(':visible')", timeout = 50))
app$snapshot(items = list(output = "in_1-custom-test"), screenshot = TRUE)
app$setInputs(inputTabset = "inputTabset_5")
app$setInputs(dropdown_9 = "mip")
app$setInputs(inputTabset = "inputTabset_1")
Sys.sleep(0.5)
expect_true(app$waitFor("$('#btRefreshGraphIn').is(':visible')", timeout = 50))
app$setInputs(btRefreshGraphIn = "click")
Sys.sleep(0.5)
app$snapshot(items = list(output = "in_1-custom-test"), screenshot = TRUE)
app$setInputs(btGraphIn = "click")
Sys.sleep(0.5)
expect_true(app$waitFor("$('#btRefreshGraphIn').is(':hidden')", timeout = 50))
app$waitFor("HTMLWidgets.getInstance(document.getElementById('in_1')).hot.setDataAtCell(0,1,300);true;", timeout = 50L)
Sys.sleep(0.5)
app$setInputs(inputTabset = "inputTabset_5")
app$setInputs(inputTabset = "inputTabset_1")
Sys.sleep(0.5)
expect_true(app$waitFor("$('#btRefreshGraphIn').is(':hidden')", timeout = 50))
app$setInputs(btGraphIn = "click")
Sys.sleep(0.5)
app$snapshot(items = list(output = "in_1-custom-test"), screenshot = TRUE)
app$stop()
