app <- AppDriver$new("../../",
  name = "multiple_symbol_renderer_input", variant = NULL,
  load_timeout = as.integer(Sys.getenv("MIRO_TEST_LOAD_TIMEOUT", "20000")),
  timeout = as.integer(Sys.getenv("MIRO_TEST_TIMEOUT", "4000"))
)
app$set_inputs(btImport = "click")
app$set_inputs(tb_importData = "tb_importData_local")
app$upload_file(localInput = "../data/transport.gdx")
app$set_inputs(btImportLocal = "click")
Sys.sleep(2)
expect_true(app$get_js("$('#btRefreshGraphIn').is(':hidden')", timeout = 50))
app$set_inputs(btGraphIn = "click")
Sys.sleep(0.5)
expect_true(app$get_js("$('#btRefreshGraphIn').is(':visible')", timeout = 50))
app$expect_values(output = "in_1-custom-test")
app$set_inputs(inputTabset = "inputTabset_5")
app$set_inputs(dropdown_9 = "mip")
app$set_inputs(inputTabset = "inputTabset_1")
Sys.sleep(0.5)
expect_true(app$get_js("$('#btRefreshGraphIn').is(':visible')", timeout = 50))
app$set_inputs(btRefreshGraphIn = "click")
Sys.sleep(0.5)
app$expect_values(output = "in_1-custom-test")
app$set_inputs(btGraphIn = "click")
Sys.sleep(0.5)
expect_true(app$get_js("$('#btRefreshGraphIn').is(':hidden')", timeout = 50))
app$run_js("HTMLWidgets.getInstance(document.getElementById('in_1')).hot.setDataAtCell(0,1,300);", timeout = 50L)
Sys.sleep(0.5)
app$set_inputs(inputTabset = "inputTabset_5")
app$set_inputs(inputTabset = "inputTabset_1")
Sys.sleep(0.5)
expect_true(app$get_js("$('#btRefreshGraphIn').is(':hidden')", timeout = 50))
app$set_inputs(btGraphIn = "click")
Sys.sleep(0.5)
app$expect_values(output = "in_1-custom-test")
app$stop()
