app <- ShinyDriver$new("../../", loadTimeout = 20000)

app$snapshotInit("output_attach_test_2")
app$snapshot(
  items = list(output = "outputDataTitle"),
  screenshot = TRUE
)
app$findElement("#btRemove1")$click()
Sys.sleep(1)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(1)
app$setInputs(btImport = "click")
Sys.sleep(1)
app$snapshot(
  items = list(output = "outputDataTitle"),
  screenshot = TRUE
)
expect_identical(startsWith(app$getValue("selLoadScen"), "1_"), TRUE)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(1)
app$setInputs(btSolve = "click")
Sys.sleep(4)
app$setInputs(btEditMeta = "click")
Sys.sleep(2)
app$findElement("[data-value='attachments']")$click()
app$snapshot(
  items = list(output = "modelStatus"),
  screenshot = TRUE
)
expect_error(app$findElement("#outputTableView")$click())
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)

# should not have switched to input section as no MIRO log errors
expect_error(app$findElement("#btRemove1")$click())
app$findElement("a[data-value='inputData']")$click()
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(0.5)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
expect_identical(startsWith(app$getValue("selLoadScen"), "1_"), TRUE)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(2)
app$findElement("[data-value='attachments']")$click()
app$findElement("#btRemoveAttachment_1")$click()
attachmentList <- app$findElements(".attachment-line")
expect_identical(length(attachmentList), 2L)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)
app$findElement("a[data-value='inputData']")$click()
app$setInputs(btSolve = "click")
Sys.sleep(4)
app$findElement("#shiny-modal .btn")$click()
Sys.sleep(1)
app$setInputs(btSaveAs = "click")
Sys.sleep(0.5)
app$setInputs(scenName = "test1234")
Sys.sleep(0.5)
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(0.5)
app$findElement("a[data-value='attachments']")$click()
Sys.sleep(0.1)
attachmentList <- app$findElements(".attachment-line")
expect_identical(length(attachmentList), 4L)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)

# old scenario should still have the 3 attachments it had before
# (removing attachment was never saved)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(0.5)
app$setInputs(btOverwriteScen = "click")
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(2)
app$findElement("[data-value='attachments']")$click()
attachmentList <- app$findElements(".attachment-line")
expect_identical(length(attachmentList), 3L)

# solve with report.put should give compilation error
# removing attachment and solving again should not give error
# as report.put should have been deleted also from sandbox
app$setInputs(btSolve = "click")
Sys.sleep(4)
expect_error(app$findElement("#outputTableView")$click())
app$setInputs(btEditMeta = "click")
Sys.sleep(2)
app$findElement("[data-value='attachments']")$click()
app$findElement("#btRemoveAttachment_1")$click()
attachmentList <- app$findElements(".attachment-line")
expect_identical(length(attachmentList), 2L)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)
app$findElement("a[data-value='inputData']")$click()
app$setInputs(btSolve = "click")
Sys.sleep(1)
app$setInputs(btRunNoCheckHash = "click")
Sys.sleep(4)
app$findElement("#shiny-modal .btn")$click()

app$stop()
