app <- AppDriver$new("../../", name = "output_attach_test_2", variant = NULL, load_timeout = 20000)
app$click(selector = "#btRemove1")
Sys.sleep(1)
app$click(selector = ".modal-footer .bt-gms-confirm")
Sys.sleep(1.5)
app$expect_values(output = "inputDataTitle")
app$set_inputs(btImport = "click")
Sys.sleep(1)
expect_identical(startsWith(app$get_values()$input[["selLoadScen"]], "1_"), TRUE)
app$set_inputs(btLoadScenConfirm = "click")
Sys.sleep(1)
app$set_inputs(btSolve = "click")
Sys.sleep(4)
app$set_inputs(btEditMeta = "click")
Sys.sleep(2)
app$run_js("$('[data-value=\\'attachments\\']').get(0).click()")
app$expect_values(output = "modelStatus")
expect_true(app$get_js("$('#outputTableView').get(0).getBoundingClientRect().height===0"))
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(1)
# should not have switched to input section as no MIRO log errors
expect_true(app$get_js("$('#btRemove1').get(0).getBoundingClientRect().height===0"))
app$click(selector = "a[data-value='inputData']")
app$click(selector = "#btRemove1")
Sys.sleep(0.5)
app$click(selector = ".modal-footer .bt-gms-confirm")
Sys.sleep(0.5)
app$set_inputs(btImport = "click")
Sys.sleep(0.5)
expect_identical(startsWith(app$get_values()$input[["selLoadScen"]], "1_"), TRUE)
app$set_inputs(btLoadScenConfirm = "click")
Sys.sleep(1)
app$set_inputs(btEditMeta = "click")
Sys.sleep(2)
app$run_js("$('[data-value=\\'attachments\\']').get(0).click()")
app$run_js("$('#btRemoveAttachment_1').click();")
attachmentList <- app$get_js("$('.attachment-line').length")
expect_identical(attachmentList, 2L)
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(1)
app$click(selector = "a[data-value='inputData']")
app$set_inputs(btSolve = "click")
Sys.sleep(4)
app$click(selector = "#shiny-modal .btn")
Sys.sleep(1)
app$set_inputs(btSaveAs = "click")
Sys.sleep(0.5)
app$set_inputs(scenName = "test1234")
Sys.sleep(0.5)
app$click(selector = "#shiny-modal #dialogSaveInit .bt-gms-confirm")
Sys.sleep(1)
app$set_inputs(btEditMeta = "click")
Sys.sleep(0.5)
app$run_js("$('[data-value=\\'attachments\\']').get(0).click()")
Sys.sleep(0.1)
attachmentList <- app$get_js("$('.attachment-line').length")
expect_identical(attachmentList, 4L)
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(0.5)

# old scenario should still have the 3 attachments it had before
# (removing attachment was never saved)
app$set_inputs(btImport = "click")
Sys.sleep(0.5)
app$set_inputs(btLoadScenConfirm = "click")
Sys.sleep(0.5)
app$set_inputs(btOverwriteScen = "click")
Sys.sleep(1)
app$set_inputs(btEditMeta = "click")
Sys.sleep(2)
app$run_js("$('[data-value=\\'attachments\\']').get(0).click()")
attachmentList <- app$get_js("$('.attachment-line').length")
expect_identical(attachmentList, 3L)

# solve with report.put should give compilation error
# removing attachment and solving again should not give error
# as report.put should have been deleted also from sandbox
app$set_inputs(btSolve = "click")
Sys.sleep(4)
expect_true(app$get_js("$('#outputTableView').get(0).getBoundingClientRect().height===0"))
app$set_inputs(btEditMeta = "click")
Sys.sleep(2)
app$run_js("$('[data-value=\\'attachments\\']').get(0).click()")
app$run_js("$('#btRemoveAttachment_1').click();")
attachmentList <- app$get_js("$('.attachment-line').length")
expect_identical(attachmentList, 2L)
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(1)
app$click(selector = "a[data-value='inputData']")
app$set_inputs(btSolve = "click")
Sys.sleep(1)
app$set_inputs(btRunNoCheckHash = "click")
Sys.sleep(4)
app$click(selector = "#shiny-modal .btn")

app$stop()
