app <- AppDriver$new("../../",
  name = "symbol_groups_test", variant = NULL,
  load_timeout = as.integer(Sys.getenv("MIRO_TEST_LOAD_TIMEOUT", "20000")),
  timeout = as.integer(Sys.getenv("MIRO_TEST_TIMEOUT", "4000"))
)
app$view()
Sys.sleep(2)
expect_identical(app$get_js("$('a[data-value=inputTabset_1]').text()"), "group 1")
expect_identical(app$get_js("$('a[data-value=inputTabset_2]').text()"), "group 2")
expect_identical(app$get_js("$('a[data-value=inputTabset_3]').text()"), "group 3")
expect_identical(app$get_js("$('a[data-value=inputTabset_4]').text()"), "")
expect_identical(app$get_js("$('a[data-value=inputTabset1_1]').text()"), "test2")
expect_identical(app$get_js("$('a[data-value=inputTabset1_2]').text()"), "test4")
expect_true(app$get_js("$('#data-in_2').is(':visible') && $('#data-in_2').parent().attr('class')==='tab-pane active'"))
app$set_inputs(inputTabset1 = "inputTabset1_2")
Sys.sleep(0.5)
expect_true(app$get_js("$('#data-in_4').is(':visible') && $('#data-in_4').parent().attr('class')==='tab-pane active'"))
app$set_inputs(inputTabset = "inputTabset_2")
Sys.sleep(0.5)
expect_true(app$get_js("$('#data-in_3').is(':visible') && $('#data-in_3').parent().attr('class')==='col-sm-4'"))
expect_true(app$get_js("$('#data-in_6').is(':visible') && $('#data-in_6').parent().attr('class')==='col-sm-4'"))
app$set_inputs(inputTabset = "inputTabset_3")
Sys.sleep(0.5)
expect_true(app$get_js("$('#data-in_5').is(':visible') && $('#data-in_5').parent().attr('class')==='col-sm-12'"))
expect_true(app$get_js("$('#data-in_1').is(':visible') && $('#data-in_1').parent().attr('class')==='col-sm-12'"))

app$click(selector = "a[data-value='outputData']")
Sys.sleep(1)
expect_identical(app$get_js("$('a[data-value=outputTabset_1]').text()"), "Output group 1")
expect_identical(app$get_js("$('a[data-value=outputTabset_2]').text()"), "Output group 2")
expect_identical(app$get_js("$('a[data-value=outputTabset_3]').text()"), "out5")
expect_identical(app$get_js("$('a[data-value=outputTabset_4]').text()"), "")
expect_true(app$get_js("$('#scenGraph_1_1').is(':visible') && $('#scenGraph_1_1').parent().attr('class')==='col-sm-12'"))
expect_true(app$get_js("$('#scenGraph_1_3').is(':visible') && $('#scenGraph_1_3').parent().attr('class')==='col-sm-12'"))
app$set_inputs(outputTabset = "outputTabset_2")
Sys.sleep(0.5)
expect_identical(app$get_js("$('a[data-value=outputTabset_2_1]').text()"), "out2")
expect_identical(app$get_js("$('a[data-value=outputTabset_2_2]').text()"), "out4")
expect_true(app$get_js("$('#scenGraph_1_2').is(':visible') && $('#scenGraph_1_2').parent().attr('class')==='tab-pane active'"))
app$set_inputs(outputTabset_2 = "outputTabset_2_2")
Sys.sleep(0.5)
expect_true(app$get_js("$('#scenGraph_1_4').is(':visible') && $('#scenGraph_1_4').parent().attr('class')==='tab-pane active'"))
app$set_inputs(outputTabset = "outputTabset_3")
Sys.sleep(0.5)
expect_true(app$get_js("$('#scenGraph_1_5').is(':visible') && $('#scenGraph_1_5').parent().attr('class')==='tab-pane active'"))

app$stop()
