app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("symbol_order_test")

# input symbol order
expect_true(app$waitFor("$('a[data-value=\"inputTabset_1\"]').text()==='Scalars';", timeout = 50))
expect_true(app$waitFor("$('a[data-value=\"inputTabset_2\"]').text()==='Advanced options';", timeout = 50))
expect_true(app$waitFor("$('a[data-value=\"inputTabset_3\"]').text()==='Price';", timeout = 50))
expect_true(app$waitFor("$('a[data-value=\"inputTabset_4\"]').text()==='Input widgets';", timeout = 50))
app$snapshot(items = list(output = c("inputDataTitle")), screenshot = TRUE)
app$findElement('a[data-value="outputData"]')$click()
Sys.sleep(1L)
app$findElement('a[data-value="outputTabset_2"]')$click()
Sys.sleep(1L)
expect_true(app$waitFor("$('a[data-value=\"outputTabset_1\"]').text()==='Output Scalars';", timeout = 50))
expect_true(app$waitFor("$('a[data-value=\"outputTabset_2\"]').text()==='Dow Jones vs. Index Fund';", timeout = 50))
expect_true(app$waitFor("$('a[data-value=\"outputTabset_3\"]').text()==='weight';", timeout = 50))
expect_true(app$waitFor("$('a[data-value=\"outputTabset_4\"]').text()==='Price (stocks & dow jones)';", timeout = 50))
expect_true(app$waitFor("$('a[data-value=\"outputTabset_2_1\"]').text()==='dow jones vs. index fund';", timeout = 50))
expect_true(app$waitFor("$('a[data-value=\"outputTabset_2_2\"]').text()==='absolute error';", timeout = 50))
app$stop()
