app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("views_save_as_test")

app$snapshot(items = list(output = "outputDataTitle"),
             screenshot = TRUE)

saveNewDefault <- function(newName = NULL, discard = FALSE){
  app$findElement("#btRemove1")$click()
  Sys.sleep(0.5)
  app$findElement(".modal-footer .bt-gms-confirm")$click()
  Sys.sleep(0.5)
  app$setInputs(btImport = "click")
  Sys.sleep(0.5)
  app$setInputs(selLoadScen = paste0("1_", user))
  expect_identical(startsWith(app$getValue("selLoadScen"), "1_"), TRUE)
  app$setInputs(btLoadScenConfirm = "click")
  Sys.sleep(1)
  app$setInputs(btSaveAs = "click")
  Sys.sleep(1)
  app$setInputs(scenName = newName)
  if(isTRUE(discard))
    app$setInputs(newScenDiscardViews = "click")
  Sys.sleep(0.1)
  app$findElement("#shiny-modal .bt-gms-confirm")$click()
  Sys.sleep(1)
}


#load default scenario
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(0.5)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(1)

#get user name
app$setInputs(btEditMeta = "click")
Sys.sleep(1)
app$findElement("a[data-value='accessPerm']")$click()
Sys.sleep(1)
user <- app$getValue("editMetaWritePerm")[[1]]
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)

#add view, save scenario newScen
app$setInputs(btEditMeta = "click")
Sys.sleep(1)
app$findElement('#editMetaUI a[data-value="Views"]')$click()
app$uploadFile(file_addViews = "../data/good-views.json")
Sys.sleep(1)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)
app$setInputs(btSave = "click")
Sys.sleep(0.5)

#save as same name and discard views
app$setInputs(btSaveAs = "click")
Sys.sleep(0.5)
app$setInputs(newScenDiscardViews = "click")
Sys.sleep(0.5)
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(0.5)
app$setInputs(btSaveConfirm = "click")
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(1)
app$findElement("a[data-value='Views']")$click()
Sys.sleep(1)
expect_identical(length(app$findElements("#currentViewsTable tbody tr")), 0L)
Sys.sleep(0.5)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)

#add view, save as new name and discard views
saveNewDefault("newScen2", TRUE)
app$setInputs(btEditMeta = "click")
Sys.sleep(1)
app$findElement("a[data-value='Views']")$click()
Sys.sleep(0.1)
app$uploadFile(file_addViews = "../data/good-views.json")
Sys.sleep(1)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)
app$setInputs(btSave = "click")
Sys.sleep(0.5)
app$setInputs(btSaveAs = "click")
Sys.sleep(1)
app$setInputs(scenName = "newScen3")
app$setInputs(newScenDiscardViews = "click")
Sys.sleep(0.5)
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(1)
app$findElement("a[data-value='Views']")$click()
Sys.sleep(1)
expect_identical(length(app$findElements("#currentViewsTable tbody tr")), 0L)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)

#add view, save as same name and do not discard views
saveNewDefault("newScen4", TRUE)
app$setInputs(btEditMeta = "click")
Sys.sleep(1)
app$findElement("a[data-value='Views']")$click()
Sys.sleep(0.5)
app$uploadFile(file_addViews = "../data/good-views.json")
Sys.sleep(1)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)
app$setInputs(btSave = "click")
Sys.sleep(0.5)
app$setInputs(btSaveAs = "click")
Sys.sleep(1)
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(1)
app$setInputs(btSaveConfirm = "click")
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(1)
app$findElement("a[data-value='Views']")$click()
Sys.sleep(1)
expect_identical(length(app$findElements("#currentViewsTable tbody tr")), 1L)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)

#add view, save as new name and do not discard views
saveNewDefault("newScen5", TRUE)
app$setInputs(btEditMeta = "click")
Sys.sleep(1)
app$findElement("a[data-value='Views']")$click()
Sys.sleep(0.1)
app$uploadFile(file_addViews = "../data/good-views.json")
Sys.sleep(1)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(1)
app$setInputs(btSave = "click")
Sys.sleep(0.5)
app$setInputs(btSaveAs = "click")
Sys.sleep(0.5)
app$setInputs(scenName = "newScen6")
Sys.sleep(0.5)
app$findElement("#shiny-modal .bt-gms-confirm")$click()
Sys.sleep(1)
app$setInputs(btEditMeta = "click")
Sys.sleep(1)
app$findElement("a[data-value='Views']")$click()
Sys.sleep(1)
expect_identical(length(app$findElements("#currentViewsTable tbody tr")), 1L)
app$setInputs(btUpdateMeta = "click")
Sys.sleep(0.5)

# delete scenario
Sys.sleep(0.5)
app$setInputs(btDelete = "click")
Sys.sleep(0.5)
app$setInputs(btDeleteConfirm = "click")
app$setInputs(btRemoveDeletedConfirm = "click")
Sys.sleep(0.5)

app$stop()

