app <- AppDriver$new("../../", name = "views_save_as_test", variant = NULL, load_timeout = 20000)

app$expect_values(output = "inputDataTitle")

saveNewDefault <- function(newName = NULL, discard = FALSE) {
  app$click(selector = "#btRemove1")
  Sys.sleep(0.5)
  app$click(selector = ".modal-footer .bt-gms-confirm")
  Sys.sleep(0.5)
  app$set_inputs(btImport = "click")
  Sys.sleep(0.5)
  app$set_inputs(selLoadScen = paste0("1_", user))
  expect_identical(startsWith(app$get_values()$input[["selLoadScen"]], "1_"), TRUE)
  app$set_inputs(btLoadScenConfirm = "click")
  Sys.sleep(1)
  app$set_inputs(btSaveAs = "click")
  Sys.sleep(1)
  app$set_inputs(scenName = newName)
  if (isTRUE(discard)) {
    app$set_inputs(newScenDiscardViews = "click")
  }
  Sys.sleep(0.1)
  app$click(selector = "#shiny-modal #dialogSaveInit .bt-gms-confirm")
  Sys.sleep(1)
}


# load default scenario
app$click(selector = "#btRemove1")
Sys.sleep(0.5)
app$click(selector = ".modal-footer .bt-gms-confirm")
Sys.sleep(0.5)
app$set_inputs(btImport = "click")
Sys.sleep(0.5)
app$set_inputs(btLoadScenConfirm = "click")
Sys.sleep(1)

# get user name
app$set_inputs(btEditMeta = "click")
Sys.sleep(1)
app$click(selector = "a[data-value='accessPerm']")
Sys.sleep(1)
user <- app$get_values()$input[["editMetaWritePerm"]][[1]]
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(0.5)

# add view, save scenario newScen
app$set_inputs(btEditMeta = "click")
Sys.sleep(1)
app$click(selector = '#editMetaUI a[data-value="views"]')
app$upload_file(file_addViews = "../data/good-views.json")
Sys.sleep(1)
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(1)
app$set_inputs(btSave = "click")
Sys.sleep(0.5)

# save as same name and discard views
app$set_inputs(btSaveAs = "click")
Sys.sleep(0.5)
app$set_inputs(newScenDiscardViews = "click")
Sys.sleep(0.5)
app$click(selector = "#shiny-modal #dialogSaveInit .bt-gms-confirm")
Sys.sleep(0.5)
app$set_inputs(btSaveConfirm = "click")
Sys.sleep(1)
app$set_inputs(btEditMeta = "click")
Sys.sleep(1)
app$click(selector = "a[data-value='views']")
Sys.sleep(1)
expect_identical(app$get_js("$('#currentViewsTable tbody tr').length"), 0L)
Sys.sleep(0.5)
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(0.5)

# add view, save as new name and discard views
saveNewDefault("newScen2", TRUE)
app$set_inputs(btEditMeta = "click")
Sys.sleep(1)
app$click(selector = "a[data-value='views']")
Sys.sleep(0.1)
app$upload_file(file_addViews = "../data/good-views.json")
Sys.sleep(1)
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(1)
app$set_inputs(btSave = "click")
Sys.sleep(0.5)
app$set_inputs(btSaveAs = "click")
Sys.sleep(1)
app$set_inputs(scenName = "newScen3")
app$set_inputs(newScenDiscardViews = "click")
Sys.sleep(0.5)
app$click(selector = "#shiny-modal #dialogSaveInit .bt-gms-confirm")
Sys.sleep(1)
app$set_inputs(btEditMeta = "click")
Sys.sleep(1)
app$click(selector = "a[data-value='views']")
Sys.sleep(1)
expect_identical(app$get_js("$('#currentViewsTable tbody tr').length"), 0L)
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(0.5)

# add view, save as same name and do not discard views
saveNewDefault("newScen4", TRUE)
app$set_inputs(btEditMeta = "click")
Sys.sleep(1)
app$click(selector = "a[data-value='views']")
Sys.sleep(0.5)
app$upload_file(file_addViews = "../data/good-views.json")
Sys.sleep(1)
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(1)
app$set_inputs(btSave = "click")
Sys.sleep(0.5)
app$set_inputs(btSaveAs = "click")
Sys.sleep(1)
app$click(selector = "#shiny-modal #dialogSaveInit .bt-gms-confirm")
Sys.sleep(1)
app$set_inputs(btSaveConfirm = "click")
Sys.sleep(1)
app$set_inputs(btEditMeta = "click")
Sys.sleep(1)
app$click(selector = "a[data-value='views']")
Sys.sleep(1)
expect_identical(app$get_js("$('#currentViewsTable tbody tr').length"), 1L)
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(0.5)

# add view, save as new name and do not discard views
saveNewDefault("newScen5", TRUE)
app$set_inputs(btEditMeta = "click")
Sys.sleep(1)
app$click(selector = "a[data-value='views']")
Sys.sleep(0.1)
app$upload_file(file_addViews = "../data/good-views.json")
Sys.sleep(1)
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(1)
app$set_inputs(btSave = "click")
Sys.sleep(0.5)
app$set_inputs(btSaveAs = "click")
Sys.sleep(0.5)
app$set_inputs(scenName = "newScen6")
Sys.sleep(0.5)
app$click(selector = "#shiny-modal #dialogSaveInit .bt-gms-confirm")
Sys.sleep(1)
app$set_inputs(btEditMeta = "click")
Sys.sleep(1)
app$click(selector = "a[data-value='views']")
Sys.sleep(1)
expect_identical(app$get_js("$('#currentViewsTable tbody tr').length"), 1L)
app$set_inputs(btUpdateMeta = "click")
Sys.sleep(0.5)

# delete scenario
Sys.sleep(0.5)
app$set_inputs(btDelete = "click")
Sys.sleep(0.5)
app$set_inputs(btDeleteConfirm = "click")
app$set_inputs(btRemoveDeletedConfirm = "click")
Sys.sleep(0.5)

app$stop()
