repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: end-of-file-fixer
        exclude: |
            (?x)^(
                src/tests/data/good-views.json|
                src/tests/data/good-views2.json|
                src/tests/data/bad-views.json|
                src/tests/data/bad-views2.json|
                src/tests/data/pivot-comp-views.json|
                src/tests/shinytest/views_metadata_test-expected/views.json|
                src/tests/shinytest/views_metadata_test-expected/views2.json|
                src/tests/shinytest/views_import_test-expected/views.json|
                src/www/default_.*\.css.*|
                src/www/miro.*\.js.*|
                server/admin/www/model_update\.js.*
            )$
    -   id: trailing-whitespace
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.3.2'
    hooks:
    -   id: prettier
        files: \.(html)$
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.3.0
    hooks:
    -   id: eslint
        args: [--fix]
        exclude: |
            (?x)^(
                src/.*|
                server/.*|
            )$
        additional_dependencies:
        -   eslint@8.3.0
        -   eslint-plugin-import@2.25.3
        -   eslint-config-airbnb-base@15.0.0
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
        exclude: |
            (?x)^(
                r-src/.*|
                scripts/globals.R|
            )$
