repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: end-of-file-fixer
        exclude: |
            (?x)^(
                src/tests/data/good-views.json|
                src/tests/data/good-views2.json|
                src/tests/data/bad-views.json|
                src/tests/data/bad-views2.json|
                src/tests/data/pivot-comp-views.json|
                src/tests/shinytest/views_metadata_test-expected/views.json|
                src/tests/shinytest/views_metadata_test-expected/views2.json|
                src/tests/shinytest/views_import_test-expected/views.json|
                src/www/skin_.*|
                src/www/miro.*\.js.*
            )$
    -   id: trailing-whitespace
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.3.2'
    hooks:
    -   id: prettier
        files: \.(html)$
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
        exclude: |
            (?x)^(
                r-src/.*|
                scripts/globals.R|
            )$
