app <- ShinyDriver$new("../../", loadTimeout = 20000)
app$snapshotInit("comparison_mode_test")

currentUser <- Sys.info()[["user"]]

#test compare mode in tab view
app$findElement("a[data-value='scenarios']")$click()
app$findElement(".btSplitView button")$click()
app$findElements(".btSplitView a[data-view='tab']")[[1]]$click()
Sys.sleep(1)
app$snapshot(items = list(output = c("title_4", "title_5")), screenshot = TRUE)
app$findElement("#no-scen .action-button")$click()
Sys.sleep(1)
scenToSelect <- paste0(c("1_", "2_"), currentUser)
app$setInputs(selLoadScen = scenToSelect, wait_ = FALSE, values_ = FALSE)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
app$findElement("#btCompareScen")$click()
Sys.sleep(0.2)
app$findElement("a[data-value='contentScen_5_2']")$click()
app$findElement("a[data-value='scen_4_']")$click()
expect_true(app$waitFor("$('.tab-content div[data-value=\"contentScen_4_2\"]').is(':visible');", timeout = 50))
app$findElement("a[data-value='contentScen_4_5']")$click()
app$findElement("a[data-value='scen_5_']")$click()
expect_true(app$waitFor("$('.tab-content div[data-value=\"contentScen_5_5\"]').is(':visible');", timeout = 50))

#test compare mode in split view
app$findElement(".btSplitView button")$click()
app$findElements(".btSplitView a[data-view='split']")[[1]]$click()
app$setInputs(btScenSplit1_open = "click")
Sys.sleep(1)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
app$setInputs(btScenSplit2_open = "click")
Sys.sleep(1)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
app$findElement("#btCompareScen")$click()
Sys.sleep(0.2)
app$findElement("a[data-value='contentScen_2_2']")$click()
expect_true(app$waitFor("$('.tab-content div[data-value=\"contentScen_3_2\"]').is(':visible');", timeout = 50))
app$findElement("a[data-value='contentScen_3_5']")$click()
expect_true(app$waitFor("$('.tab-content div[data-value=\"contentScen_2_5\"]').is(':visible');", timeout = 50))

app$stop()