app <- ShinyDriver$new("../", loadTimeout = 10000)
app$snapshotInit("compare_scen_split_test")

app$setInputs(sidebarMenuId = "scenarios", wait_ = FALSE, values_ = FALSE)
app$setInputs(btScenSplit1_open = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
app$setInputs(btScenSplit2_open = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
vals <- app$getAllValues()$input
noStocks_left <- length(vals[["tab_2_1-datatable_rows_all"]])
noStocks_right <- length(vals[["tab_3_1-datatable_rows_all"]])
expect_gt(noStocks_left, 1)
expect_gt(noStocks_right, 1)
app$snapshot(items = list(output = c("title_2", "title_3")), screenshot = TRUE)
app$stop()
