app <- ShinyDriver$new("../", loadTimeout = 10000)
app$snapshotInit("compare_scen_tab_test")

app$setInputs(sidebarMenuId = "scenarios", wait_ = FALSE, values_ = FALSE)
app$setInputs(btSplitView = "click")
app$setInputs(btLoadScen = "click")
Sys.sleep(2)
app$setInputs(selLoadScen = c("1_test", "2_test"), wait_ = FALSE, values_ = FALSE)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(2)
app$setInputs(table_5 = "click")
vals <- app$getAllValues()
noStocks_table <- length(vals$input[["tab_5_1-datatable_rows_all"]])
noStocks_graph <- length(jsonlite::fromJSON(vals$output[["tab_5_1-graph"]])$x$data$labels[[1]])
expect_gt(noStocks_table, 1)
expect_gt(noStocks_graph, 1)
app$snapshot(items = list(output = c("title_4", "title_5")), screenshot = TRUE)
app$stop()