app <- ShinyDriver$new("../", loadTimeout = 10000)
app$snapshotInit("excel_upload_overwrite_test")

app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(tb_importData = "tb_importData_local", wait_ = FALSE, values_ = FALSE)
app$uploadFile(localInput = "data/pickstock.xlsx")
app$setInputs(btCheckSnameLocal = "click")
app$setInputs(btOverwriteLocal = "click")
Sys.sleep(2)
app$setInputs(inputTabset = "inputTabset_2", wait_ = FALSE, values_ = FALSE)
Sys.sleep(2)
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$setInputs(btSave = "click")
Sys.sleep(1)
app$stop()
