app <- ShinyDriver$new("../", loadTimeout = 10000)
app$snapshotInit(paste0("gams_interrupt_test_", Sys.getenv("GMSMODELNAME")))

app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$findElement("#btLoadScenConfirm2")$click()
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
Sys.sleep(2)
app$setInputs(btSolve = "click")
app$setInputs(btInterrupt = "click")
Sys.sleep(13)
app$snapshot(items = list(output = c("modelStatus")), screenshot = TRUE)
