app <- ShinyDriver$new("../", loadTimeout = 10000)
app$snapshotInit("gams_interrupt_test")

app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$setInputs(btSolve = "click")
Sys.sleep(2)
app$setInputs(btInterrupt = "click")
Sys.sleep(13)
app$snapshot(items = list(output = c("modelStatus")), screenshot = TRUE)
