app <- ShinyDriver$new("../", loadTimeout = 10000)
app$snapshotInit(paste0("load_from_db_test_", Sys.getenv("GMSMODELNAME")))

app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$findElement("#btLoadScenConfirm2")$click()
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$setInputs(btSave = "click")
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(0.5)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
if(identical(Sys.getenv("GMSMODELNAME"), "kport")){
  app$setInputs(tb_importData = "tb_importData_local")
  app$uploadFile(localInput = paste0("data/kport.xlsx"))
  app$findElement(css = "#btCheckSnameLocal")$click()
  app$setInputs(btOverwriteScen = "click")
}else{
  app$findElement("#btLoadScenConfirm2")$click()
  Sys.sleep(0.3)
}
Sys.sleep(0.5)
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$setInputs(btSolve = "click")
if(identical(Sys.getenv("GMSMODELNAME"), "pickstock_live")){
  Sys.sleep(50)
}else{
  Sys.sleep(15)
}
switch(Sys.getenv("GMSMODELNAME"), 
       "pickstock" = {
         app$setInputs(outputTabset = "outputTabset_2", wait_ = FALSE, values_ = FALSE)
         app$setInputs(outputTableView = "click")
         Sys.sleep(0.5)
         noStocks <- length(app$getAllValues()$input[["tab_1-datatable_rows_all"]])
         expect_gt(noStocks, 1)
         app$snapshot(items = list(input = c("table-out_2-datatable_rows_all")), screenshot = TRUE)
       },
       "pickstock_live" = {
         app$setInputs(outputTabset = "outputTabset_2", wait_ = FALSE, values_ = FALSE)
         app$setInputs(outputTableView = "click")
         Sys.sleep(0.5)
         noStocks <- length(app$getAllValues()$input[["table-out_2-datatable_rows_all"]])
         expect_gt(noStocks, 1)
         app$snapshot(items = list(input = c("table-out_2-datatable_rows_all")), screenshot = TRUE)
       },
       "transport" = ,
       "transport_live" = {
         app$setInputs(outputTableView = "click")
         Sys.sleep(0.5)
         noRows <- length(app$getAllValues()$input[["table-out_1-datatable_rows_all"]])
         expect_equal(noRows, 6)
         app$snapshot(items = list(input = c("table-out_1-datatable_rows_all")), screenshot = TRUE)
       })
app$setInputs(btSave = "click", wait_ = FALSE, values_ = FALSE)
Sys.sleep(0.5)
app$setInputs(sidebarMenuId = "inputData", wait_ = FALSE, values_ = FALSE)
Sys.sleep(0.5)
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(0.5)
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
Sys.sleep(0.5)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$findElement("#btLoadScenConfirm2")$click()
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$setInputs(btSaveAs = "click", wait_ = FALSE, values_ = FALSE)
Sys.sleep(0.5)
app$setInputs(scenName = "test1234", wait_ = FALSE, values_ = FALSE)
app$setInputs(btCheckName = "click", wait_ = FALSE, values_ = FALSE)
app$setInputs(btSave = "click", wait_ = FALSE, values_ = FALSE)
Sys.sleep(2)
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
Sys.sleep(0.5)
app$findElement("#btRemove1")$click()
Sys.sleep(0.5)
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$findElement(".modal-footer .bt-gms-confirm")$click()
Sys.sleep(0.5)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
scenName1 <- app$getValue("selLoadScen", "input")
app$setInputs(btSortTime = "click")
scenName2 <- app$getValue("selLoadScen", "input")
expect_false(identical(scenName2, scenName1))
app$setInputs(btSortName = "click")
app$setInputs(btSortName = "click")
expect_false(identical(scenName2, scenName1))
app$stop()
