app <- ShinyDriver$new("../", loadTimeout = 10000)
app$snapshotInit("load_from_db")

app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$setInputs(btSave = "click")
app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$setInputs(btLoadScenConfirm = "click")
Sys.sleep(0.3)
app$setInputs(btOverwriteScen = "click")
Sys.sleep(0.5)
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$setInputs(btSolve = "click")
Sys.sleep(15)
app$setInputs(contentCurrent = "contentCurrent_2", wait_ = FALSE, values_ = FALSE)
app$setInputs(outputTableView = "click")
Sys.sleep(0.5)
app$snapshot(items = list(output = c("table-out_2-datatable")), screenshot = TRUE)
app$setInputs(btSave = "click", wait_ = FALSE, values_ = FALSE)
Sys.sleep(0.5)
app$setInputs(sidebarMenuId = "inputData", wait_ = FALSE, values_ = FALSE)
Sys.sleep(0.5)
app$setInputs(btRemove = "click", wait_ = FALSE, values_ = FALSE)
Sys.sleep(0.5)
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$setInputs(btRemoveConfirm = "click")
Sys.sleep(0.5)
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$setInputs(btImport = "click")
Sys.sleep(0.5)
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$setInputs(btLoadScenConfirm = "click")
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
app$setInputs(btSaveAs = "click", wait_ = FALSE, values_ = FALSE)
Sys.sleep(0.5)
app$setInputs(scenName = "test1234", wait_ = FALSE, values_ = FALSE)
app$setInputs(btCheckName = "click", wait_ = FALSE, values_ = FALSE)
app$setInputs(btSave = "click", wait_ = FALSE, values_ = FALSE)
Sys.sleep(2)
app$snapshot(items = list(output = c("in_1")), screenshot = TRUE)
