# Copyright GAMS Development Corp. All Rights Reserved.
# SPDX-License-Identifier: GPL-3.0-only

global:
  rootPath: '/'
  # Global Docker image registry
  imageRegistry: ''
  # imagePullSecrets:
  #   - registryKeySecretName
  imagePullSecrets: []
  # nodeSelector: Node labels for pod assignment
  nodeSelector: {}
  # tolerations: tolerations for pod assignment
  tolerations: []
  # nodeSelector: Node labels for pod assignment of stateful sets (database)
  nodeSelectorSts: {}
  # tolerationsSts: tolerations for pod assignment of stateful sets (database)
  tolerationsSts: []
  networkPolicy:
    enabled: true
    # The IP adress of the Kubernetes API Server.
    # kubectl get svc kubernetes -n default -o jsonpath='{.spec.clusterIP}'
    apiServerIp: ''
image:
  # Global tag of the images. If not specified, AppVersion is used.
  tag: ''

proxy:
  image:
    registry: docker.io/gams
    repository: miro-proxy
    tag: ''
  resources:
    requests:
      cpu: '100m'
      memory: 250Mi
    limits:
      cpu: '2000m'
      memory: 500Mi
  service:
    type: ClusterIP # ClusterIP or NodePort
    # only relevant if type is NodePort. If not provided, a random port within the NodePort range is used.
    nodePort: ''
  networkPolicy:
    # Add extra ingress rules to the NetworkPolicy
    # (only relevent if global.networkPolicy.enabled is true)
    # Example:
    #   - ports:
    #     - protocol: TCP
    #       port: 9090
    #   from:
    #     - namespaceSelector:
    #         matchLabels:
    #           name: monitoring
    #     - podSelector:
    #         matchLabels:
    #           app: prometheus
    extraIngress: []
  config:
    title: GAMS MIRO Server
    language: en # en, de or cn
    maxTotalInstances: -1 # -1 for unlimited
    maxUploadSizeMB: 200
    forceSignedApps: false
    disableReadonlyMode: false
    anonymousReadonlyMode: false
    authentication: webservice # webservice or openid
    openid:
      authUrl: ''
      tokenUrl: ''
      jwksUrl: ''
      logoutUrl: ''
      clientId: ''
      clientSecret: ''
    engine:
      apiUrl: ''
      namespace: ''
      anonymousUser: ''
      anonymousPassword: ''
    metrics:
      enabled: false
      port: 9090

auth:
  image:
    registry: docker.io/gams
    repository: miro-auth
    tag: ''
  resources:
    requests:
      cpu: '100m'
      memory: 250Mi
    limits:
      cpu: '400m'
      memory: 500Mi
  service:
    type: ClusterIP # ClusterIP or NodePort
    # only relevant if type is NodePort. If not provided, a random port within the NodePort range is used.
    nodePort: ''
  networkPolicy:
    # Add extra ingress rules to the NetworkPolicy
    # (only relevent if global.networkPolicy.enabled is true)
    # Example:
    #   - ports:
    #     - protocol: TCP
    #       port: 9090
    #   from:
    #     - namespaceSelector:
    #         matchLabels:
    #           name: monitoring
    #     - podSelector:
    #         matchLabels:
    #           app: prometheus
    extraIngress: []

miro:
  image:
    registry: docker.io/gams
    repository: miro-ui
    tag: ''
  resources:
    requests:
      cpu: '450m'
      memory: 1700Mi
    limits:
      cpu: '2000m'
      memory: 1700Mi

admin:
  image:
    registry: docker.io/gams
    repository: miro-admin
    tag: ''
  resources:
    requests:
      cpu: '450m'
      memory: 1700Mi
    limits:
      cpu: '2000m'
      memory: 1700Mi

db:
  image:
    registry: docker.io
    repository: postgres
    tag: '17-alpine'
  user: 'GMSMASTER'
  password: ''
  name: 'gamsmiro'
  volumeSize: 5Gi
  resources:
    requests:
      cpu: '100m'
      memory: 1024Mi
    limits:
      cpu: '400m'
      memory: 3072Mi

persistence:
  type: 'local' # local or efs
  efs:
    fileSystemId: 'fs-12345678' # The EFS File System ID
    accessPointId: '' # Optional, for EFS Access Points
    storageClass: 'efs-sc' # EFS storage class. NOTE: You need to manually install this storage class in the cluster!
    mountTargets: [] # relevant if global.networkPolicy.enabled is "true"
  local:
    path: '/mnt/localstorage'

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001

## @param commonLabels Labels to add to all deployed resources
##
commonLabels: {}

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls: false
  tlsSecretName: ''
  hostname: example.com
