FROM gams/miro-ui

USER root

COPY additional_packages .

RUN R -e "packageList=trimws(readLines('additional_packages'));\
packageList=packageList[packageList!=''];\
packageList=packageList[!(packageList %in% installed.packages()[,'Package'])];\
for(packageToInstall in packageList){install.packages(packageToInstall,repos='https://cloud.r-project.org/',dependencies=c('Depends','Imports','LinkingTo'))}"

USER miro

EXPOSE 3838

CMD ["R", "-e", "shiny::runApp('/home/miro/app', port = 3838, host = '0.0.0.0')"]
