version: "3.7"
services:
  ui:
    image: miro-ui
    build:
      context: ../
      args:
        - R_BASE_VERSION=${R_BASE_VERSION}
      dockerfile: ./server/ui/Dockerfile
    restart: "no"
    command: /bin/true
  admin:
    image: miro-admin
    build: ./admin/
    restart: "no"
    command: /bin/true
  auth_test:
    image: miro-auth-test
    build:
      context: ./auth/
      dockerfile: Dockerfile.test
    ports:
      - 8081:1234
    environment:
      PORT: 1234
      ENGINE_URL: ${GMS_MIRO_ENGINE_HOST}
      ENGINE_NS: ${GMS_MIRO_ENGINE_NS}
      ENGINE_USER: ${ENGINE_USER}
      ENGINE_PASSWORD: ${ENGINE_PASSWORD}
      GMS_MIRO_DATABASE: gamsmiro
      GMS_MIRO_DATABASE_HOST: miroserver-db
      GMS_MIRO_DATABASE_USER: GMSMASTER
      GMS_MIRO_DATABASE_PWD:  ${GMS_MIRO_DATABASE_PWD}
      SESSION_TIMEOUT: 43200
    restart: always
    volumes:
      - ../src:/home/miro/app
      - ./admin:/home/miro/admin
      - ./data:/home/miro/admin/data
      - ./models:/home/miro/admin/models
      - ./auth/app:/app
    networks:
      - gamsmiro-network
  dockerproxy:
    image: miro-sproxy
    build: ./docker-socket-proxy/
    environment:
      - CONTAINERS=1
      - CONTAINERS_CREATE=1
      - POST=1
    restart: always
    ports:
      - 2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - gamsmiro-internal-network
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: GMSMASTER
      POSTGRES_PASSWORD: ${GMS_MIRO_DATABASE_PWD}
      POSTGRES_DB: gamsmiro
    volumes:
      - db-data-miro:/var/lib/postgresql/data
    networks:
      gamsmiro-network:
        aliases:
        - miroserver-db
  proxy:
    image: miro-proxy
    build:
      context: ./
      dockerfile: ./proxy/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./data:/home/miroproxy/data
      - ./models:/home/miroproxy/models
      - ./logs:/logs
    restart: always
    environment:
      GMS_MIRO_DATABASE: gamsmiro
      GMS_MIRO_DATABASE_USER: GMSMASTER
      GMS_MIRO_DATABASE_PWD:  ${GMS_MIRO_DATABASE_PWD}
      GMS_MIRO_UI_IMAGE: miro-ui
      GMS_MIRO_ADMIN_IMAGE: miro-admin
      GMS_MIRO_MODEL_DIR: ${PWD}/models
      GMS_MIRO_DATADIR: ${PWD}/data
      GMS_MIRO_ENGINE_HOST: ${GMS_MIRO_ENGINE_HOST}
      GMS_MIRO_ENGINE_NS: ${GMS_MIRO_ENGINE_NS}
      GMS_MIRO_ENGINE_ANONYMOUS_USER: ${GMS_MIRO_ENGINE_ANONYMOUS_USER}
      GMS_MIRO_ENGINE_ANONYMOUS_PWD: ${GMS_MIRO_ENGINE_ANONYMOUS_PWD}
    networks:
      - gamsmiro-network
      - gamsmiro-internal-network

volumes:
  db-data-miro:

networks:
  gamsmiro-network:
    name: miroserver-network
  gamsmiro-internal-network:
    internal: true
