apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: miro-server-low-priority
value: 1
preemptionPolicy: Never
globalDefault: false
description: "This priority class is used for low priority containers (e.g. placeholders for auto-scaling) and will not cause other pods to be preempted."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miro-server-app-placeholder
  namespace: miro
spec:
  selector:
    matchLabels:
      app: miro-server-app-placeholder
  template:
    metadata:
      labels:
        app: miro-server-app-placeholder
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      nodeSelector:
        eks.amazonaws.com/nodegroup: hercules-private-worker-ek-group-miro
      tolerations:
        - effect: NoSchedule
          key: reserved
          value: miro
      priorityClassName: miro-server-low-priority
      containers:
      - name: sleep
        image: busybox:latest
        command:
          - sh
          - "-c"
          - while true; do sleep 30; done;
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 1000m
            memory: 1024Mi
