{
 "title": "MIRO Server Usage",
 "time": { "from": "now-30m", "timezone": "browser", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "prefix", "label": "Metric Prefix" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(${prefix}absolute_users_logged_in{miroserver_realm=~\".+\"}, namespace)"
    }
   },
   {
    "name": "realm",
    "query": {
     "query": "label_values(${prefix}absolute_users_logged_in{namespace=~\"$namespace\"}, miroserver_realm)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(${prefix}absolute_users_logged_in{namespace=~\"$namespace\",miroserver_realm=~\"$realm\"}, miroserver_instance)"
    }
   },
   {
    "name": "spec_id",
    "label": "app",
    "query": {
     "query": "label_values(${prefix}absolute_apps_running{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\"}, spec_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard shows the active usage of MIRO Server.\n\n**Tips:**\n\n- use the filters on the top of page\n- change the time range in the top-right corner of the page\n- disable the automatic refresh (in the top-right corner) if the dashboard takes a long time to load"
   }
  },
  { "title": "Startup Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Startup Time",
   "type": "timeseries",
   "description": "The time it took for an application to start up. Starts counting after the user opens the app until the app is visible to the user.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(${prefix}startupTime_seconds_sum{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) / (sum(rate(${prefix}startupTime_seconds_count{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) != 0)",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  { "title": "Fine-grained timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Container Schedule Time",
   "type": "timeseries",
   "description": "The time it took Kubernetes to assign the container to a node. If a scale-up was required, this includes the time needed to create a new node. This is not available for apps that use pre-initialization or container-sharing. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(${prefix}containerScheduleTime_seconds_sum{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) / (sum(rate(${prefix}containerScheduleTime_seconds_count{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) != 0)",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  { "title": "Fine-grained timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Image Pull Time",
   "type": "timeseries",
   "description": "The time it took to pull the container image. This is not available for apps that use pre-initialization or container-sharing.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(${prefix}imagePullTime_seconds_sum{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) / (sum(rate(${prefix}imagePullTime_seconds_count{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) != 0)",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  {
   "title": "Container Initialization Time",
   "type": "timeseries",
   "description": "The time it took for the container runtime to initialize the container (after the container was created, but before the application process was started). This is not available for apps that use pre-initialization or container-sharing.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\nsum(rate(${prefix}containerStartupTime_seconds_sum{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id)\n/ (sum(rate(${prefix}containerStartupTime_seconds_count{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) != 0)\n)\n-\n(\nsum(rate(${prefix}imagePullTime_seconds_sum{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id)\n/ (sum(rate(${prefix}imagePullTime_seconds_count{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) != 0)\n)\n -\n(\n sum(rate(${prefix}containerScheduleTime_seconds_sum{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id)\n / (sum(rate(${prefix}containerScheduleTime_seconds_count{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) != 0)\n)\n\n",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  {
   "title": "Application Startup Time",
   "type": "timeseries",
   "description": "The time it took for the application process (e.g. Shiny) to start and become fully ready (i.e. reachable over HTTP). For apps that use pre-initialization or container-sharing this is the time the user has to wait to be assigned to a seat.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(${prefix}applicationStartupTime_seconds_sum{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) / (sum(rate(${prefix}applicationStartupTime_seconds_count{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) != 0)",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Usage Time",
   "type": "timeseries",
   "description": "The time an app instance has been used by the user. This is only recorded after the app instance is (automatically) stopped.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(${prefix}usageTime_seconds_sum{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) / (sum(rate(${prefix}usageTime_seconds_count{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval])) by (spec_id) != 0)",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  {
   "title": "Apps",
   "type": "timeseries",
   "description": "The number of app instances running.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (spec_id) (${prefix}absolute_apps_running{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"} > 0)",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "description": "The number of logged-in users. This includes inactive users.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (miroserver_realm) (${prefix}absolute_users_logged_in{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\"})",
     "legendFormat": "Users ({{miroserver_realm}})"
    }
   ]
  },
  {
   "title": "Users Active",
   "type": "timeseries",
   "description": "The number of active users. This only includes users that have been using MIRO Server in the last minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (miroserver_realm) (${prefix}absolute_users_active{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\"})",
     "legendFormat": "Users ({{miroserver_realm}})"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Auth failures",
   "type": "timeseries",
   "description": "The number of failed log-in attempts. If there are no failed attempts, the panel will show the text `No data`.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (spec_id) (round(increase(${prefix}authFailed_total{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\"}[$__rate_interval]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App start failures",
   "type": "timeseries",
   "description": "The number of app instances that failed to start. This counts the time a user sees the `Failed to start...` page.  If there are no failures, the panel will show the text `No data`.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (spec_id) (round(increase(${prefix}startFailed_total{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval]))) > 0",
     "legendFormat": "{{spec_id}}"
    }
   ]
  },
  {
   "title": "App crashes",
   "type": "timeseries",
   "description": "The number of app instances that crashed (but only after the app instance has successfully started up). This counts the time a user sees the ` This app has crashed and has been stopped.` page. If there are no crashes, the panel will show the text `No data`.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (spec_id) (round(increase(${prefix}appCrashes_total{namespace=~\"$namespace\",miroserver_realm=~\"$realm\",miroserver_instance=~\"$instance\",spec_id=~\"$spec_id\"}[$__rate_interval]))) > 0",
     "legendFormat": "{{spec_id}}"
    }
   ]
  }
 ]
}