FROM miro-auth

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    python3-pip

RUN pip3 install --no-cache-dir pytest httpx psycopg2-binary

USER miro

CMD ["pytest"]
