FROM --platform=linux/amd64 miro-auth

RUN python -m pip install --no-cache-dir \
    pytest \
    httpx \
    psycopg2-binary \
    pytest-cov

USER miro

WORKDIR /app/app

CMD ["sleep", "infinity"]
