FROM docker:27

ARG KIND_VERSION=v0.25.0
ARG HELM_VERSION=v3.16.3
ARG KUBECTL_VERSION=v1.31.3

RUN apk add --no-cache \
    jq \
    curl \
    tar \
    bash \
    python3 \
    py3-pip \
    && pip install --no-cache-dir --break-system-packages pytest selenium \
    && rm -rf /var/cache/apk/*

# Install kind
RUN curl -Lo /usr/local/bin/kind "https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-amd64" && \
    chmod +x /usr/local/bin/kind

# Install helm
RUN curl -Lo helm.tar.gz "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz" && \
    tar -zxvf helm.tar.gz && \
    mv linux-amd64/helm /usr/local/bin/helm && \
    chmod +x /usr/local/bin/helm && \
    rm -rf helm.tar.gz linux-amd64

# Install kubectl
RUN curl -Lo /usr/local/bin/kubectl "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" && \
    chmod +x /usr/local/bin/kubectl
