FROM docker:27

ENV PIP_NO_CACHE_DIR=1 \
  PIP_DISABLE_PIP_VERSION_CHECK=1 \
  PIP_DEFAULT_TIMEOUT=100

RUN apk update && apk upgrade \
  && apk add --no-cache \
    bash \
    python3 \
    python3-dev \
    py3-pip


RUN pip3 install pytest selenium --break-system-packages
