kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: '0.0.0.0'
  apiServerPort: 6443
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          certSANs:
            - "docker"
    extraMounts:
      - hostPath: ./mnt
        containerPath: /home/mnt
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        listenAddress: '0.0.0.0' # Optional, defaults to "0.0.0.0"
        protocol: tcp # Optional, defaults to tcp
      - containerPort: 30081
        hostPort: 30081
        listenAddress: '0.0.0.0' # Optional, defaults to "0.0.0.0"
        protocol: tcp # Optional, defaults to tcp
