{{- /*
Copyright GAMS Development Corp. All Rights Reserved.
SPDX-License-Identifier: GPL-3.0-only
*/}}

{{- if and .Values.proxy.config.forceSignedApps.enabled .Values.proxy.config.forceSignedApps.acceptedPublicKeysPEM }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-pk-cm
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.global.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
{{- range $index, $key := .Values.proxy.config.forceSignedApps.acceptedPublicKeysPEM }}
  key-{{$index}}.pem: {{ $key | quote }}
{{- end }}
{{- end }}
