{{- /*
Copyright GAMS Development Corp. All Rights Reserved.
SPDX-License-Identifier: GPL-3.0-only
*/}}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-proxy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-proxy
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cm-proxy.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Release.Name }}-proxy-sa
      automountServiceAccountToken: true
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
{{- include "common.images.renderPullSecrets" ( dict "images" (list .Values.proxy.image) "context" $) | nindent 6}}
      {{- if .Values.global.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.global.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.global.tolerations "context" $) | nindent 8 }}
      {{- end }}
      priorityClassName: {{ .Release.Name }}-system-priority
      initContainers:
      - name: init-create-directories
        image: busybox:latest
        command:
          - sh
          - "-c"
          - |
            mkdir -p /home/miroproxy/mnt/data
            chmod -R g+rwX /home/miroproxy/mnt/data
            mkdir -p /home/miroproxy/mnt/models
            chmod -R g+rwX /home/miroproxy/mnt/models
            [ -f "/home/miroproxy/mnt/data/specs.yaml" ] || echo 'c3BlY3M6Ci0gYWNjZXNzR3JvdXBzOgogIC0gYWRtaW5zCiAgY29udGFpbmVyRW52OgogICAgTUlST19BUElfVkVSU0lPTjogJzEnCiAgZGVzY3JpcHRpb246IE1JUk8gU2VydmVyIEFkbWluIFBhbmVsCiAgZGlzcGxheU5hbWU6IEFkbWluCiAgaWQ6IGFkbWluCiAgbG9nb1VSTDogfgo=' | base64 -d > /home/miroproxy/mnt/data/specs.yaml
        volumeMounts:
        - name: shared-data
          mountPath: /home/miroproxy/mnt
      containers:
      - name: proxy
        image: {{ include "common.images.image" (dict "imageRoot" (dict "registry" .Values.proxy.image.registry "repository" .Values.proxy.image.repository "tag" (coalesce .Values.proxy.image.tag .Values.image.tag .Chart.AppVersion)) "global" .Values.global) }}
        resources:
{{ toYaml .Values.proxy.resources | indent 10 }}
        ports:
        - containerPort: 8080
        - containerPort: 9090
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 9090
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 15
        env:
        - name: GMS_MIRO_TARGET_IMG_DIR
          value: "/home/miroproxy/mnt/data/img"
        - name: GMS_MIRO_DATABASE_PWD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: db_password
        - name: GMS_MIRO_ENGINE_ANONYMOUS_PWD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: engine_anonymous_password
        volumeMounts:
        - name: shared-data
          mountPath: /home/miroproxy/mnt
        - name: config-volume
          mountPath: /home/miroproxy/application.yml
          subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-proxy-config
        {{- if eq .Values.persistence.type "local" }}
        - name: shared-data
          hostPath:
            path: {{ .Values.persistence.local.path }}
            type: DirectoryOrCreate
        {{- else if eq .Values.persistence.type "efs" }}
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-efs-pvc
        {{- end }}
