{{- /*
Copyright GAMS Development Corp. All Rights Reserved.
SPDX-License-Identifier: GPL-3.0-only
*/}}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-auth
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-auth
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
{{- include "common.images.renderPullSecrets" ( dict "images" (list .Values.auth.image) "context" $) | nindent 6}}
      {{- if .Values.global.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.global.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.global.tolerations "context" $) | nindent 8 }}
      {{- end }}
      initContainers:
      - name: init-create-directories
        image: busybox:latest
        command:
          - sh
          - "-c"
          - |
            mkdir -p /home/miro/admin/mnt/data
            mkdir -p /home/miro/admin/mnt/models
        volumeMounts:
        - name: shared-data
          mountPath: /home/miro/admin/mnt
      containers:
      - name: auth
        image: {{ include "common.images.image" (dict "imageRoot" (dict "registry" .Values.auth.image.registry "repository" .Values.auth.image.repository "tag" (coalesce .Values.auth.image.tag .Values.image.tag .Chart.AppVersion)) "global" .Values.global) }}
        resources:
{{ toYaml .Values.auth.resources | indent 10 }}
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: ENGINE_URL
          value: "{{ .Values.proxy.config.engine.apiUrl }}"
        - name: ENGINE_NS
          value: "{{ .Values.proxy.config.engine.namespace }}"
        - name: GMS_MIRO_DATABASE
          value: "{{ .Values.db.name }}"
        - name: GMS_MIRO_DATABASE_USER
          value: "{{ .Values.db.user }}"
        - name: DATA_DIR
          value: "/home/miro/admin/mnt/data"
        - name: MODEL_DIR
          value: "/home/miro/admin/mnt/models"
        - name: APP_CONFIG_FILE_PATH
          value: "/home/miro/admin/application.yml"
        - name: GMS_MIRO_DATABASE_PWD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: db_password
        volumeMounts:
        - name: shared-data
          mountPath: /home/miro/admin/mnt
        - name: config-volume
          mountPath: /home/miro/admin/application.yml
          subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-proxy-config
        {{- if eq .Values.persistence.type "local" }}
        - name: shared-data
          hostPath:
            path: {{ .Values.persistence.local.path }}
            type: DirectoryOrCreate
        {{- else if eq .Values.persistence.type "efs" }}
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-efs-pvc
        {{- end }}
