apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "common.names.fullname" . }}-pc-sys
value: 1000000
globalDefault: false
description: "This priority class is used for pods critical for the MIRO Server instance to function."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "common.names.fullname" . }}-pc-app
value: 500000
globalDefault: false
description: "This priority class is used for MIRO application containers."
