{{- /*
Copyright GAMS Development Corp. All Rights Reserved.
SPDX-License-Identifier: GPL-3.0-only
*/}}

{{- if eq .Values.persistence.type "efs" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-efs-pv
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.efs.storageClass }}
  csi:
    driver: efs.csi.aws.com
    {{- if .Values.persistence.efs.accessPointId }}
    volumeHandle: {{ .Values.persistence.efs.fileSystemId }}::{{ .Values.persistence.efs.accessPointId }}
    {{- else}}
    volumeHandle: {{ .Values.persistence.efs.fileSystemId }}
    {{- end }}
{{- end }}
