---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ .Release.Name }}-proxy-sa
  namespace: {{ .Release.Namespace | quote }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-proxy-role
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-proxy-rb
  namespace: {{ .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-proxy-sa
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-proxy-role
  apiGroup: rbac.authorization.k8s.io
