{{- /*
Copyright GAMS Development Corp. All Rights Reserved.
SPDX-License-Identifier: GPL-3.0-only
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.global.commonLabels "context" $ ) | nindent 4 }}
type: Opaque
data:
  db_password: {{ .Values.db.password | b64enc | quote }}
  engine_anonymous_password: {{ .Values.proxy.config.engine.anonymousPassword | b64enc | quote }}
