{{- /*
Copyright GAMS Development Corp. All Rights Reserved.
SPDX-License-Identifier: GPL-3.0-only
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.global.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  db_password: {{ .Values.db.password | b64enc | quote }}
  engine_anonymous_password: {{ .Values.proxy.config.engine.anonymousPassword | b64enc | quote }}
  container_log_s3_access_secret: {{ .Values.proxy.config.containerLogBackend.s3.secretAccessKey | b64enc | quote }}
