{{- /*
Copyright GAMS Development Corp. All Rights Reserved.
SPDX-License-Identifier: GPL-3.0-only
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-secdb
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.global.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ required "secrets.dbPassword is required" .Values.secrets.dbPassword | b64enc | quote }}
