{{- /*
Copyright GAMS Development Corp. All Rights Reserved.
SPDX-License-Identifier: GPL-3.0-only
*/}}

{{- if eq .Values.proxy.config.authentication "none" }}

{{- $anonUser := (required "proxy.config.engine.anonymousUser is required when proxy.config.authentication is 'none'." .Values.proxy.config.engine.anonymousUser) | trim -}}
{{- if eq $anonUser "" -}}
{{- fail "proxy.config.engine.anonymousUser cannot be empty or only whitespace when proxy.config.authentication is 'none'." -}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-seceng
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.global.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  anonymousPassword: {{ required "secrets.engineAnonymousPassword is required if proxy.config.authentication is 'none'" .Values.secrets.engineAnonymousPassword | quote }}
{{- end }}
