apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secrets
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  db_password: {{ .Values.db.password | b64enc }}
  engine_anonymous_password: {{ .Values.proxy.config.engine.anonymousPassword | b64enc }}
