{{- /*
Copyright GAMS Development Corp. All Rights Reserved.
SPDX-License-Identifier: GPL-3.0-only
*/}}

{{- if eq .Values.proxy.config.authentication "openid" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-secoidc
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.global.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  clientSecret: {{ required "secrets.oidcClientSecret is required if proxy.config.authentication is 'openid'" .Values.secrets.oidcClientSecret | quote }}
{{- end }}
