{{- /*
Copyright GAMS Development Corp. All Rights Reserved.
SPDX-License-Identifier: GPL-3.0-only
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  selector:
    app: {{ .Release.Name }}-proxy
  ports:
    - port: 8080
      targetPort: 8080
      {{- if (and (or (eq .Values.proxy.service.type "NodePort") (eq .Values.proxy.service.type "LoadBalancer")) (not (empty .Values.proxy.service.nodePort))) }}
      nodePort: {{ .Values.proxy.service.nodePort }}
      {{- else if eq .Values.proxy.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
