{{- /*
Copyright GAMS Development Corp. All Rights Reserved.
SPDX-License-Identifier: GPL-3.0-only
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-auth
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.global.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.auth.service.type }}
  selector:
    app: {{ include "common.names.fullname" . }}-auth
  ports:
    - port: 8081
      targetPort: 8081
      {{- if (and (or (eq .Values.auth.service.type "NodePort") (eq .Values.auth.service.type "LoadBalancer")) (not (empty .Values.auth.service.nodePort))) }}
      nodePort: {{ .Values.auth.service.nodePort }}
      {{- else if eq .Values.auth.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
