apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-auth
  ports:
    - port: 8081
      targetPort: {{ .Values.auth.port }}
