{{- /*
Copyright GAMS Development Corp. All Rights Reserved.
SPDX-License-Identifier: GPL-3.0-only
*/}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-{{ .Release.Name }}-db
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      automountServiceAccountToken: false
{{- include "common.images.renderPullSecrets" ( dict "images" (list .Values.db.image) "context" $) | nindent 6}}
      {{- if .Values.global.nodeSelectorSts }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.global.nodeSelectorSts "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.global.tolerationsSts }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.global.tolerationsSts "context" $) | nindent 8 }}
      {{- end }}
      priorityClassName: {{ .Release.Name }}-system-priority
      containers:
      - name: db
        image: "{{ .Values.db.image.registry }}/{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        resources:
{{ toYaml .Values.db.resources | indent 10 }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: {{ .Values.db.user }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: db_password
        - name: POSTGRES_DB
          value: {{ .Values.db.name }}
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-db-pvc
