proxy:
  title: GAMS MIRO Server
  template-path: ./templates/2col
  favicon-path: ./favicon.ico
  model-dir: ${GMS_MIRO_MODEL_DIR}
  data-dir: ${GMS_MIRO_DATADIR}
  miro-lang: en
  port: 8080
  heartbeat-rate: 10000
  heartbeat-timeout: 120000
  same-site-cookie: Lax
  admin-groups: admins
  container-log-path: /logs/container-logs
  force-signed-apps: false
  disable-readonly-mode: false
  anonymous-readonly-mode: false
  authentication: webservice
  openid:
    auth-url: https://login.microsoftonline.com/<your-tenant-id>/oauth2/v2.0/authorize
    token-url: https://login.microsoftonline.com/<your-tenant-id>/oauth2/v2.0/token
    jwks-url: https://login.microsoftonline.com/<your-tenant-id>/discovery/v2.0/keys
    logout-url: https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri=http%3A%2F%2Fwww.yourmiroserver.com%2Flogout-success
    client-id: xxx
    client-secret: yyy
  database:
    host: miroserver-db
    port: 5432
    name: ${GMS_MIRO_DATABASE}
    username: ${GMS_MIRO_DATABASE_USER}
    password: ${GMS_MIRO_DATABASE_PWD}
  engine:
    host: ${GMS_MIRO_ENGINE_HOST}
    ns: ${GMS_MIRO_ENGINE_NS}
    anonymous-user: ${GMS_MIRO_ENGINE_ANONYMOUS_USER}
    anonymous-pwd: ${GMS_MIRO_ENGINE_ANONYMOUS_PWD}
  docker:
    url: http://dockerproxy:2375
    internal-networking: true
    container-network: miroserver-network
    miro-image-name: ${GMS_MIRO_UI_IMAGE}
    admin-image-name: ${GMS_MIRO_ADMIN_IMAGE}
logging:
  file:
    /logs/miroproxy.log

spring:
  application.name: GAMS MIRO Server
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  frame-options: sameorigin
  secure-cookies: false
  forward-headers-strategy: native
  servlet:
    session.timeout: 21600
    context-path: /
